---
layout: 2017/x
---
:skip-front-matter:

= Problem Set 3: Game of Fifteen

== tl;dr

[start=0]
. Watch https://video.cs50.net/2016/fall/lectures/3[Week 3's lecture].
. Search and sort some numbers.
. Implement the Game of Fifteen.
. Submit your code.
. Submit a form.

== Help

For help with Week 3 and Problem Set 3:

* Watch Zamyla's walkthroughs herein.
* Start a https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/[discussion] with classmates.

== Reminders

* Use `help50` as needed.
* Use `eprintf` as needed.
* Use `debug50` as needed.

== Getting Started

Alright, here we go again!

Log into https://cs50.io/[cs50.io] and execute

[source]
----
update50
----

within a terminal window to make sure your workspace is up-to-date.

Next, execute

[source]
----
mkdir ~/workspace/pset3/
----

at your prompt in order to make a directory called `pset3` in your `workspace` directory.

Now execute

[source]
----
cd ~/workspace/pset3/
----

and your prompt should resemble the below.

[source]
----
~/workspace/pset3/ $
----

== What to Do

. Implement either of:
+
--
* link:../../../../problems/find/less/find.html[Find], less comfortable
* link:../../../../problems/find/more/find.html[Find], more comfortable
--
+
. Implement link:../../../../problems/fifteen/fifteen.html[Game of Fifteen]

== How to Submit

Be sure you've signed up for a https://github.com/join[GitHub account], per Problem Set 0, and that you've logged into and authorized https://cs50.me/[CS50.me] at least once, per Problem Set 1!

=== Step 1 of 2

* Update your IDE:
+
[source]
----
update50
----
* Submit the less-comfortable version of `find` (if you implemented it):
+
[source]
----
cd ~/workspace/pset3/find/
submit50 2017/x/find/less
----
* Submit the more-comfortable version of `find` (if you implemented it):
+
[source]
----
cd ~/workspace/pset3/find/
submit50 2017/x/find/more
----
* Submit `fifteen`:
+
[source]
----
cd ~/workspace/pset3/fifteen/
submit50 2017/x/fifteen
----

=== Step 2 of 2

Submit https://forms.cs50.net/2017/x/psets/3[this form]!

This was Problem Set 3.
