---
layout: 2018/ap
---
:skip-front-matter:

= Problem: Calc 2.0

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], the `#cs50ap` channel on https://cs50x.slack.com[CS50x Slack] (after signing up), or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

== tl;dr

Implement an improved command line calculator, per the below

[source, subs=quotes]
----
$ [underline]#./calc2 + - / 4 2 24 x 8 9#
50.000000
----

include::../../../honesty.adoc[]

== Assessment

Your work on this problem set will be evaluated along three axes primarily.

Correctness::
 To what extent is your code consistent with our specifications and free of bugs?
Design::
 To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?
Style::
 To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Adding any Updates

Start off by opening up CS50 IDE and then type

[source,bash]
----
update50
----

within a terminal window to make sure your workspace is up-to-date. If you somehow closed your terminal window (and can't find it!), make sure that *Console* is checked under the *View* menu, then click the green, circled plus (+) in CS50 IDE's bottom half, then select *New Terminal*. If you need a hand, do just ask via the channels noted at the top of this specification.

Next, navigate to your `workspace` directory and create a new subdirectory inside of it called `unitA` (Remember how?) Then navigate inside that directory. (Remember how?)

Finally, take a few minutes to watch Doug's video on stacks.

video::9Tp8wHD66lw[youtube]

== Divide and Conquer, again

In this problem, you will be tasked with implementing a not so simple command-line based calculator program. (Hmm... http://docs.cs50.net/2018/ap/problems/calc/calc.html[that sounds familiar].) Your program will accept inputs like this (wherein underlined text represents user input):

[source,subs=quotes]
----
~/workspace/unitA/ $ [underline]#./calc2 + - 3 4 5#
4.000000
----

or, indeed like this (allowing the user to perform some basic floating-point arithmetic)

[source,subs=quotes]
----
username@ide50:~/workspace/unitA/ $ [underline]#./calc2 x - 3.4 5.6 7.9#
-17.3799999
----

such that the user can perform all five of the basic math operations that C permits -- addition, subtraction, multiplication, division, and modulo.

But wait. Part of that isn't familiar.

[source,bash]
----
x - 3.4 5.6 7.9
----

What's that?

That, actually, is what is known as __prefix notation__. Though not as common as the __infix notation__ we all learned about in elementary school, it turns out that prefix notation and its closely related cousin __postfix notation__ (also known, respectively, as Polish and Reverse Polish notation) are much easier for machines to parse.

Converting the above to more familiar infix notation would result in the expression `(3.4 - 5.6) x 7.9`. For more on prefix notation, check out https://en.wikipedia.org/wiki/Polish_notation[its Wikipedia page] and/or Google!

Obviously, you're going to need to do math at some point, but you may have already done that. Can you leverage some of your code from your first version of Calc?

== Stacks on Stacks on Stacks

So, how should we go about implementing this prefix calculator? One easy approach might be to use a stack. Let's see why.

The basic idea behind prefix notation is that an operation operates on the two numbers immediately to its right, and all three (the operator and its so-called __operands__) are then replaced in the line by the answers, moving from right to leftfootnote:[Not __necessarily__ right to left, but in this example it might be easiest to follow doing it that way.].

Here's an example using one fairly straightforward approach:

[source,bash]
----
+ - / 4 2 24 x 8 9
----

The first operation we encounter going right to left is `x` (multiplication). So we look to the two operands to its right (`8 9`), multiply them together, and leave the result where `x 8 9` used to be:

[source,bash]
----
+ - / 4 2 24 72
----

The next operator from right to left is `/`. 4 divided by 2 is of course 2, and so we leave `2` where `/ 4 2` used to be:

[source,bash]
----
+ - 2 24 72
----

Next up is `- 2 24`, replaced by `-22` (the result of `2 - 24`):

[source,bash]
----
+ -22 72
----

And all that then remains is `-22 + 72`, or `50`!

Visually, this approach of "finding the rightmost operator and applying it to the two numbers to its right" is an intuitive way for humans to parse prefix notation, but computers can be a bit smarter about this, without ever having to look at each operand or operator more than once, if instead we store all the information in a stack as we see it.

If the computer parsed this input by starting at the right side (aka the last element of `argv`) and pushing __numbers__ onto a stack as it came across them, then when it came upon an operation all that would need to happen is to pop the top two numbers off the stack, apply the operation, and push the result back on!

== Calculating, Calculating

Like Calc, you will be expected to take all input in the command line. And like Calc, floating point numbers and integers are both fair game. **Unlike** Calc, you may not assume well formatted input. Here is what you can assume:

* There will never be more than 20 numbers in the stack

That's it.

Note that you cannot assume that everything will be a float or an operation, or that the order of numbers and operands will work out nicely. Better check those yourself!

Inside of `calc2.c` (where you should write your calculator), use the following definition of stack:

[source,c]
----
typedef struct
{
   int size;
   float nums[MAXNUMS];
}
stack;
----

And `#define MAXNUMS 20` somewhere above.

That's all you'll have for this one though. No distro, just this specification and a definition of a stack datatype to include in your file!

This was Calc 2.0.
