---
layout: 2018/fall
---

= Survey

== tl;dr

Build a website in Flask that enables a user to:

* fill out a form, the results of which are saved to a comma-separated values (CSV) file in the server; and
* visit a different page where they can view all of the form submissions received.

== Background

TODO

== Getting Started

Here's how to download this problem's "distribution code" (i.e., starter code) into your own CS50 IDE. Log into link:https://cs50.io/[CS50 IDE] and then, in a terminal window, execute each of the below.

1. Execute `update50` to ensure your IDE is up-to-date. That command might take a few minutes to finish.
1. Execute `cd` to ensure that you're in `~/workspace/` (i.e., a directory called `workspace` that's in your home directory, aka `~`).
1. Execute `mkdir pset7` to make (i.e., create) a directory called `pset7` in your home directory, if you haven't already done so.
1. Execute `cd pset7` to change into (i.e., open) that directory.
1. Execute `wget http://cdn.cs50.net/2018/fall/psets/7/survey/survey.zip` to download a (compressed) ZIP file with this problem's distribution.
1. Execute `unzip survey.zip` to uncompress that file.
1. Execute `rm survey.zip` followed by `yes` or `y` to delete that ZIP file.
1. Execute `ls`. You should see a directory called `survey`, which was inside of that ZIP file.
1. Execute `cd survey` to change into that directory.
1. Execute `ls`. You should see this problem's distribution inside.

== Specification

Implement in `application.py` your routing functionality and in the `templates/` directory the necessary HTML files, a website that conforms to the below:

* `/` route:
** The index page of your site, accessible by the `GET` method, should contain two links: One that brings the user to the `/form` route to fill out the form, and one that brings the user to the `/sheet` route to view form submissions.
* `/sheet` route:
** When accessing this page via the `GET` method, the user should be presented with an HTML table of data, gathered from reading the `results.csv` file containing all form submissions.
* `/form` route:
** When accessing this page via the `GET` method, the user should be presented with the form to fill out.
*** The form must contain a minimum of three input fields, and among those three or more fields there should be a total of at least three distinct types. Per the documentation of the `<input>` tag on link:https://www.w3schools.com/tags/tag_input.asp[W3Schools], some valid options for form field types include:
**** `text`
**** `password`
**** `number`
**** `email`
**** `radio`
**** `checkbox`
**** `range`
**** and plenty of others
*** It should not be possible for the user to fill out a form that is only partially-completed. To that end, your form must include some client-side validation with JavaScript. You may, if so inclined, use jQuery or link:http://getbootstrap.com/docs/4.1/components/forms/#validation[Bootstrap's own] JavaScript validation components, in addition to or instead of using plain JavaScript.
** When accessing this page via the `POST` method, which should happen when the form is submitted, the form data should be validated server-side (see below) and written to `results.csv` as a new row, with any subsequent submissions being appended to that same file.
*** Odds are you'll find the link:https://docs.python.org/3/library/csv.html[`csv` module] in Python, and in particular its methods link:https://docs.python.org/3/library/csv.html#csv.writer[`writer`] or link:https://docs.python.org/3/library/csv.html#csv.DictWriter[`DictWriter`], of interest.
*** You should also have server-side validation within the route for `form` when accessed via the `POST` method such that, even if a user has disabled JavaScript which would ordinarily prevent a form submission, your site also checks to ensure all of the requested form data is present and, if not, redirects the user back to submit the form again.

Overall, the UI (user interface) of your site should, as in Problem Set 5, leverage Bootstrap. You will likely find Bootstrap's CSS styling (and, optionally, JavaScript support) for link:http://getbootstrap.com/docs/4.1/content/tables/[tables] and link:http://getbootstrap.com/docs/4.1/components/forms/[forms] of particular interest.

== Testing

=== Correctness

Afraid there's no `check50` for this assignment; it is incumbent upon you to write and test your code using the testing and debugging strategies we have discussed throughout the course. As in past assignments where you have not had access to `check50`, know that your correctness score on this problem will be based on whether you meet the requirements of the specification as outlined above, whether your code is free of bugs, and whether your HTML is well-formed and valid. To ensure that your pages are, you can use link:https://validator.w3.org/#validate_by_input[the W3Schools HTML Validator] service, copying and pasting your HTML directly into the provided text box. Take care to eliminate any warnings or errors suggested by the validator before submitting!

=== Style

[source]
----
style50 application.py
----

Afraid `style50` does not support HTML files, and so it is incumbent upon you to indent and align your HTML tags cleanly, as the per the examples shown in prior weeks' lectures. Know also that you can create an HTML comment with:

```
<!-- Comment goes here -->
```

but commenting your HTML code is not as imperative as it is when commenting code in, say, C, Python, or JavaScript.

== How to Submit

Execute the below, logging in with your GitHub username and password when prompted. For security, you'll see asterisks (`*`) instead of the actual characters in your password.

```
submit50 cs50/2018/fall/survey
```
