---
---
:skip-front-matter:

= Problem: Scramble (Part 2)

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], the `#cs50ap` channel on https://cs50x.slack.com[CS50x Slack] (after signing up), or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

== Objectives

* Extend your code and modify distribution code.
* Explore recursion.
* (Play.)

== Recommended Reading

* Page 17 of http://www.howstuffworks.com/c.htm.
* Chapters 20 and 23 of _Absolute Beginner's Guide to C_.
* Chapters 13, 15, and 18 of _Programming in C_.

== Prerequisites

* This problem requires that you have completed http://cdn.cs50.net/ap/1516/problems/3/7/3-7.html[Problem 3-7]. Unfortunately we are not able to provide a partial staff solution as the basis for this particular problem. 

== Academic Honesty

This course's philosophy on academic honesty is best stated as "be reasonable." The course recognizes that interactions with classmates and others can facilitate mastery of the course's material. However, there remains a line between enlisting the help of another and submitting the work of another. This policy characterizes both sides of that line.

The essence of all work that you submit to this course must be your own. Collaboration on problems is not permitted (unless explicitly stated otherwise) except to the extent that you may ask classmates and others for help so long as that help does not reduce to another doing your work for you. Generally speaking, when asking for help, you may show your code or writing to others, but you may not view theirs, so long as you and they respect this policy's other constraints. Collaboration on quizzes and tests is not permitted at all. Collaboration on the final project is permitted to the extent prescribed by its specification.

Below are rules of thumb that (inexhaustively) characterize acts that the course considers reasonable and not reasonable. If in doubt as to whether some act is reasonable, do not commit it until you solicit and receive approval in writing from your instructor. If a violation of this policy is suspected and confirmed, your instructor reserves the right to impose local sanctions on top of any disciplinary outcome that may include an unsatisfactory or failing grade for work submitted or for the course itself.

=== Reasonable

* Communicating with classmates about problems in English (or some other spoken language).
* Discussing the course's material with others in order to understand it better.
* Helping a classmate identify a bug in his or her code, such as by viewing, compiling, or running his or her code, even on your own computer.
* Incorporating snippets of code that you find online or elsewhere into your own code, provided that those snippets are not themselves solutions to assigned problems and that you cite the snippets' origins.
* Reviewing past years' quizzes, tests, and solutions thereto.
* Sending or showing code that you've written to someone, possibly a classmate, so that he or she might help you identify and fix a bug.
* Sharing snippets of your own solutions to problems online so that others might help you identify and fix a bug or other issue.
* Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problems or your own final project.
* Whiteboarding solutions to problems with others using diagrams or pseudocode but not actual code.
* Working with (and even paying) a tutor to help you with the course, provided the tutor does not do your work for you.

=== Not Reasonable

* Accessing a solution to some problem prior to (re-)submitting your own.
* Asking a classmate to see his or her solution to a problem before (re-)submitting your own.
* Decompiling, deobfuscating, or disassembling the staff's solutions to problems.
* Failing to cite (as with comments) the origins of code, writing, or techniques that you discover outside of the course's own lessons and integrate into your own work, even while respecting this policy's other constraints.
* Giving or showing to a classmate a solution to a problem when it is he or she, and not you, who is struggling to solve it.
* Looking at another individual's work during a quiz or test.
* Paying or offering to pay an individual for work that you may submit as (part of) your own.
* Providing or making available solutions to problems to individuals who might take this course in the future.
* Searching for, soliciting, or viewing a quiz's questions or answers prior to taking the quiz.
* Searching for or soliciting outright solutions to problems online or elsewhere.
* Splitting a problem's workload with another individual and combining your work (unless explicitly authorized by the problem itself).
* Submitting (after possibly modifying) the work of another individual beyond allowed snippets.
* Submitting the same or similar work to this course that you have submitted or will submit to another.
* Using resources during a quiz beyond those explicitly allowed in the quiz's instructions.
* Viewing another's solution to a problem and basing your own solution on it.

== Assessment

Your work on this problem set will be evaluated along four axes primarily.

Scope::
 To what extent does your code implement the features required by our specification?
Correctness::
 To what extent is your code consistent with our specifications and free of bugs?
Design::
 To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?
Style::
 To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Getting Ready

Before diving in, take a few minutes and join Zamyla on a quick foray into recursion, an elegant problem-solving technique that (hint, hint) will probably prove useful as you work on this problem.

video::t4MSwiqfLaY[youtube,height=540,width=960]

== Getting Started

First, log into https://cs50.io/[cs50.io] and execute

[source,bash]
----
update50
----

within a terminal window to make sure your workspace is up-to-date. 

Then, execute

[source,bash]
----
cd ~/workspace/chapter4
----

at your prompt to ensure that you're inside of your `chapter4` directory. Now, we're going to copy your prior solution to `scramble` (which, if you've been adhering to our recommended hierarchy, should be living in `chapter3` inside of your `workspace`) over to `chapter4`. To do so, execute the following:

[source,bash]
----
cp -r ../chapter3/scramble .
----

Whoa... what? What just happened? Well, we just asked the IDE to __recursively copy__ (`cp -r`) the entire contents of `../chapter3/scramble` (that is to say, navigate one level up, to `~/workspace`, then drill down into `chapter3/scramble` from there) into our current directory (`.`). Let's see if it worked. Type

[source,bash]
----
ls
----

and hopefully among the directories you see available to you is one called `scramble`, and if you navigate into that directory some (hopefully!) familiar files await you. Atop the comments to `scramble.c`, be sure to change the problem number you are working on from `Part 1` to `Part 2`.

== Feeling Inspired

Let's take this game up another notch or two. Extend your previously-completed implementation of `scramble` and our distribution code by making the following modifications to the program:

* Extend the implementation of the game in such a way that any time the user types `INSPIRATION`, up to three words are displayed, one of length 5 (if any), one of length 4 (if any), and one of length 3 (if any), all of which are in the dictionary and in the grid but not yet found. Odds are you'll be able to make use of one or more of the functions that we've provided as part of the original distribution to help.
* Implement variable scoring, by which we mean that letters in words found contribute the values below to a user's score, instead of the default where every letter is simply worth 1 point.

[width="80%"]
|==============================
|A = 1|G = 3|L = 2|Q = 10|V = 5
|B = 4|H = 3|M = 4|R = 1|W = 4
|C = 4|I = 1|N = 2|S = 1|X = 8
|D = 2|J = 10|O = 1|T = 1|Y = 3
|E = 1|K = 5|P = 4|U = 2|Z = 10
|F = 4|     |     |     |     
|==============================

Now you can play (well, maybe after some more debugging) a more complete version of `scramble`!

This was Scramble (Part 2).
