---
layout: 2017/x
---
:skip-front-matter:

= Problem Set 7: C$50 Finance

== tl;dr
 
. Watch https://video.cs50.net/2016/fall/lectures/9[Week 9's lecture].
. Implement a stock-trading website.
. Submit a form.

== Help

For help with Week 9 and Problem Set 7:

* Watch Zamyla's walkthroughs herein.
* Start a https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/[discussion] with classmates.

== Getting Started

[source]
----
update50
mkdir ~/workspace/pset7/
cd ~/workspace/pset7/
----

== Problems

Implement link:../../../../problems/finance/finance.html[C$50 Finance] in `pset7/finance/`.

== Hints

* Be sure to use Python 3, not Python 2.
* All code that you write should be consistent with https://www.python.org/dev/peps/pep-0008/[Style Guide for Python Code], otherwise known as PEP 8.
* Insofar as a goal of this problem set is to teach you how to teach yourself a new language, keep in mind that these acts are not only *reasonable*, per the syllabus, but encouraged toward that end:
** Incorporating a few lines of code that you find online or elsewhere into your own code, provided that those lines are not themselves solutions to assigned problems and that you cite the lines' origins.
** Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problem set's problems or your own final project.

== How to Submit

Be sure you've signed up for a https://github.com/join[GitHub account], per Problem Set 0, and that you've logged into and authorized https://cs50.me/[CS50.me] at least once, per Problem Set 1!

=== Step 1 of 2

[source]
----
update50
cd ~/workspace/pset7/finance/
submit50 2017/x/pset7
----

=== Step 2 of 2

Submit https://forms.cs50.net/2017/x/psets/7[this form]!
 
This was Problem Set 7.
