---
layout: 2018/spring
---
:skip-front-matter:

= Final Project

The climax of this course is its final project. The final project is your opportunity to take your newfound savvy with programming out for a spin and develop your very own piece of software. So long as your project draws upon the course's lessons, the nature of your project is entirely up to you, albeit subject to the staff's approval. You may implement your project in any language(s) as long as the staff approves. You are welcome to utilize any infrastructure, provided the staff ultimately has access to any hardware and software that your project requires. All that we ask is that you build something of interest to you, that you solve an actual problem, that you impact campus, or that you change the world. Strive to create something that outlives this course.

Inasmuch as software development is rarely a one-person effort, you are allowed an opportunity to collaborate with one or two classmates for this final project. Needless to say, it is expected that every student in any such group contribute equally to the design and implementation of that group's project. Moreover, it is expected that the scope of a two- or three-person group's project be, respectively, twice or thrice that of a typical one-person project. A one-person project, mind you, should entail more time and effort than is required by each of the course's problem sets. Although no more than three students may design and implement a given project, you are welcome to solicit advice from others, so long as you respect the course's policy on academic honesty.

Extensions on the final project are not ordinarily granted, except in cases of emergency.

== Ideas

Here are just some of the possibilities, organized into (non-exhaustive) "tracks". Discuss any and all with your TF!

If at a loss for ideas, here are some seminars from years past for inpsiration!

* https://www.youtube.com/playlist?list=PLhQjrBD2T381wZBYZUCoFFavyHHhHQmyQ[CS50 Seminars 2017]
* https://www.youtube.com/playlist?list=PLhQjrBD2T382IHcDBSQYC4ZG4C2aTiA6C[CS50 Seminars 2016]
* https://www.youtube.com/playlist?list=PLhQjrBD2T3819vqFDQ-EUVhjBxpU0fwKC[CS50 Seminars 2015]

=== Software Track

* a web-based application using Python and SQL, based in part on Problem Set 7's distribution code
* a web-based application using JavaScript, based in part on Problem Set 8's distribution code
* a web-based application using PHP or Ruby
* a plugin for CS50 IDE using JavaScript
* a Chrome extension using JavaScript
* an iOS app using Swift (or Objective-C)
* an Android app using Java
* a command-line program using C
* ...

=== Cross-Course Track

Like to combine two courses' projects? If taking some other course this semester that has a final project, you are welcome and encouraged to combine this course's project and that course's project into one, toward an end of applying lessons learned in CS50 to some other field, so long as the joint project satisfies this course's and that course's expectations. Before pursuing a joint project, though, you must disclose to both courses and receive approval from both courses (as from your TF in CS50).

=== Hardware Track

Like to integrate hardware into your project? Here are some interesting avenues to consider:

* the https://developer.apple.com/programs/[iOS Developer Program], which allows you to install homemade apps on your own iOS device,
* https://www.arduino.cc/en/Main/arduinoBoardUno[Arduino Uno] boards, for which there's an https://www.arduino.cc/en/Reference/HomePage[API],
* https://www.google.com/get/cardboard/[Google Cardboards], for which there's an developers.google.com/cardboard[API],
* the https://www.vive.com/us/[HTC Vive], for which there's an https://developer.viveport.com/us/develop_portal/[SDK]
* https://docs.particle.io/datasheets/photon-datasheet/[Internet of Things hardware development kits] and https://docs.particle.io/guide/tools-and-features/button/core/[Internet Buttons], for which there's an https://docs.particle.io/guide/tools-and-features/dev/[IDE] and https://docs.particle.io/guide/getting-started/examples/photon/[API],
* https://www.leapmotion.com/[Leap Motion Controllers], for which there's an https://developer.leapmotion.com/[API],
* https://www.microsoft.com/microsoft-hololens/en-us[Microsoft HoloLens], for which there's an https://www.microsoft.com/microsoft-hololens/en-us/developers[SDK]
* https://www.oculus.com/[Oculus Rift] and an https://www3.oculus.com/en-us/dk2/[Oculus DK2], for which there's an https://developer.oculus.com/[SDK]
* http://www2.meethue.com/en-us/productdetail/philips-hue-white-and-color-ambiance-starter-kit-a19[Philips hue bulbs], for which there's an http://www.developers.meethue.com/[API],
* http://www2.meethue.com/en-us/productdetail/philips-hue-lightstrip[Philips hue lightstrips], for which there's an http://www.developers.meethue.com/[API],
* http://www.samsung.com/global/galaxy/gear-vr/[Samsung Gear VRs], for which there's an http://developer.samsung.com/gear/[SDK], and
* http://www.sonos.com/en-us/shop/play1.html[Sonos PLAY:1s], for which there's an http://musicpartners.sonos.com/?q=docs[API].

== Schedule

=== Pre-Proposal

_due by noon on Fri 3/30_

=== Proposal

_due by noon on Fri 4/13_

=== Status Report

_due by noon on Mon 4/30_

=== Implementation

_due by noon on Thu 5/10_

=== CS50 Fair

_from 5:30pm until 7pm on Fri 5/11_

Extensions on the final project are **not** granted, except in cases of emergency.

== Specifications

=== Pre-Proposal

Intended to promote early thought, the pre-proposal is your opportunity to bounce one or more ideas off of your teaching fellow.  Quite simply, by this pre-proposal's deadline, send an email to your teaching fellow describing one or more ideas that you have for your final project.  Short, casual emails are fine, but do explain the motivation behind each of your ideas (i.e., why it interests you).  Treat this requirement as an opportunity for counsel. Certainly include any questions or concerns that you have in this email.

The subject line of your email should be *Pre-Proposal*.

If, incidentally, you have an idea for a final project that you think someone should do (if not you), post it https://discourse.cs50.net/c/cs50-2017[CS50 Discourse]! And if you'd like to solicit one or two collaborators, do post there as well.

=== Proposal

The proposal is your opportunity to receive approval and counsel from your teaching fellow before you proceed to design.  Submitting a proposal amounts to answering a few questions about your idea.  Once you have a project in mind, submit your proposal at TBA. If working with one or two other classmates, it suffices for just one of you to submit the proposal.

Your teaching fellow will either approve your proposal or require modifications on your part for subsequent approval.  Your proposal, even if approved, is not binding; you may alter your plan at any point, provided you obtain the staff's approval for any modifications.  Projects submitted without approval may not receive credit.

After submitting your proposal, a teaching fellow other than your own may be appointed your advisor and grader for the remainder of the final project, depending on your proposal's nature.

=== Status Report

Not only is the status report intended to keep the staff apprised of your progress, it is an opportunity to keep yourself on track.  Submitting a status report amounts to answering a few questions about your project.  Your answers will also influence the setup of the CS50 Fair.  Submit your status report at TBA.

=== Implementation

Ultimately due are implementation and documentation of your final project.  Your submission thereof must include all of the below.

. Documentation for your project in the form of a Markdown file called `README.md`. This documentation is to be a user's manual for your project.  Though the structure of your documentation is entirely up to you, it should be incredibly clear to the staff how and where, if applicable, to compile, configure, and use your project.  Your documentation should be at least several paragraphs in length.  It should not be necessary for us to contact you with questions regarding your project after its submission.  Hold our hand with this documentation; be sure to answer in your documentation any questions that you think we might have while testing your work.
. A "design document" for your project in the form of a Markdown file called `DESIGN.md` that discusses, technically, how you implemented your project and why you made the design decisions you did.  Your design document should be at least several paragraphs in length.  Whereas your documentation is meant to be a user's manual, consider your design document your opportunity to give the staff a technical tour of your project underneath its hood.
. Any and all files required to run your software (even if intended for some infrastructure other than CS50 IDE), including source code as well as, if applicable, configuration files, Makefiles, sample inputs, SQLite databases, and so forth. Needless to say, all source code should be thoroughly commented.
. A short video (that's no more than 2 minutes in length) in which you present your project to the world, as with slides, screenshots, voiceover, and/or live action.  Your video should somehow include your project's title, your name and year, your dorm/house and concentration, and any other details that you'd like to convey to viewers.  See http://www.cs171.org/2015/screencast/[CS171's tips on how to make a "screencast"] though you're welcome to use an actual camera.  Upload your video to YouTube as "public" or "unlisted" and take note of its URL.

==== How to Submit

TBA

== Project Fair

From 5:30pm until 7pm on Fri 5/11 is the Project Fair, an epic display of final projects in both CSCI E-50 as well as the other courses taught by the course’s staff, including CSCI E-23a, CSCI E-33a, and CSCI E-39b. Not only is the Fair a venue at which to see classmates' projects and demo your own, it is an opportunity to mingle with students, faculty, and staff from across campus. Attendance is optional. Snacks will be provided. Family and friends are welcome to join.

The CS50 Fair will take place on the Harvard University campus, location to be announced.

include::../honesty.adoc[]
