---
layout: 2019/x
---

= What's new?

Here's what's new in CS50x 2019 vis-à-vis CS50x 2018!

== Lectures

CS50's lectures are now professionally subtitled not only in English but also in Spanish!

== Problem Sets

Problem Set 6 now includes a new problem in which you will implement a program that censors messages that contain words that appear on a list of supplied "banned words."

Problem Set 7 now asks you to implement a web app that enables a user to (1) fill out a form, a la Google Forms, the results of which are saved to a comma-separated-value file on the server, and (2) view a table of all of the submissions received, a la Google Sheets.

== Seminars

New to CS50x are seminars on:

* 3D World
* A Tale of Two Pizzas: Accelerating Software Delivery with AWS Developer Tools
* Building Products at Uber: How We Bridge the Physical and Digital Worlds
* Computer Vision and Machine Learning
* Create Your Own Virtual Reality
* Drawing React Apps with Pagedraw
* Falling in LÖVE with Lua
* Frontend Development with React
* Fruit Street Telehealth: Technology Changing Healthcare
* Google Apps Script and G Suite APIs
* GUI with Python's Tkinter
* Java SE 8 Programming Basics
* Microsoft's MakeCode and Micro:bit
* Publishing Your Flask App to the Web
* Ship Continuously
* Tools and Techniques for Collaborative Coding

== Software

=== CS50 IDE

New and improved this year are

* `check50`, via which you can improve your code's correctness,
* `debug50`, via which you can debug your C code, and
* `style50`, via which you can improve your code's style!

== Videos

All videos are now playable and downloadable in https://www.edx.org/mobile[edX's mobile app]!
