---
---
:skip-front-matter:

= Problem: Leaky

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], the `#cs50ap` channel on https://cs50x.slack.com[CS50x Slack] (after signing up), or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

==  Objectives

* Learn what memory leaks are
* Learn how to fix memory leaks 
* Become familiar with Valgrind

== Academic Honesty

This course's philosophy on academic honesty is best stated as "be reasonable." The course recognizes that interactions with classmates and others can facilitate mastery of the course's material. However, there remains a line between enlisting the help of another and submitting the work of another. This policy characterizes both sides of that line.

The essence of all work that you submit to this course must be your own. Collaboration on problems is not permitted (unless explicitly stated otherwise) except to the extent that you may ask classmates and others for help so long as that help does not reduce to another doing your work for you. Generally speaking, when asking for help, you may show your code or writing to others, but you may not view theirs, so long as you and they respect this policy's other constraints. Collaboration on quizzes and tests is not permitted at all. Collaboration on the final project is permitted to the extent prescribed by its specification.

Below are rules of thumb that (inexhaustively) characterize acts that the course considers reasonable and not reasonable. If in doubt as to whether some act is reasonable, do not commit it until you solicit and receive approval in writing from your instructor. If a violation of this policy is suspected and confirmed, your instructor reserves the right to impose local sanctions on top of any disciplinary outcome that may include an unsatisfactory or failing grade for work submitted or for the course itself.

=== Reasonable

* Communicating with classmates about problems in English (or some other spoken language).
* Discussing the course's material with others in order to understand it better.
* Helping a classmate identify a bug in his or her code, such as by viewing, compiling, or running his or her code, even on your own computer.
* Incorporating snippets of code that you find online or elsewhere into your own code, provided that those snippets are not themselves solutions to assigned problems and that you cite the snippets' origins.
* Reviewing past years' quizzes, tests, and solutions thereto.
* Sending or showing code that you've written to someone, possibly a classmate, so that he or she might help you identify and fix a bug.
* Sharing snippets of your own solutions to problems online so that others might help you identify and fix a bug or other issue.
* Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problems or your own final project.
* Whiteboarding solutions to problems with others using diagrams or pseudocode but not actual code.
* Working with (and even paying) a tutor to help you with the course, provided the tutor does not do your work for you.

=== Not Reasonable

* Accessing a solution to some problem prior to (re-)submitting your own.
* Asking a classmate to see his or her solution to a problem before (re-)submitting your own.
* Decompiling, deobfuscating, or disassembling the staff's solutions to problems.
* Failing to cite (as with comments) the origins of code, writing, or techniques that you discover outside of the course's own lessons and integrate into your own work, even while respecting this policy's other constraints.
* Giving or showing to a classmate a solution to a problem when it is he or she, and not you, who is struggling to solve it.
* Looking at another individual's work during a quiz or test.
* Paying or offering to pay an individual for work that you may submit as (part of) your own.
* Providing or making available solutions to problems to individuals who might take this course in the future.
* Searching for, soliciting, or viewing a quiz's questions or answers prior to taking the quiz.
* Searching for or soliciting outright solutions to problems online or elsewhere.
* Splitting a problem's workload with another individual and combining your work (unless explicitly authorized by the problem itself).
* Submitting (after possibly modifying) the work of another individual beyond allowed snippets.
* Submitting the same or similar work to this course that you have submitted or will submit to another.
* Using resources during a quiz beyond those explicitly allowed in the quiz's instructions.
* Viewing another's solution to a problem and basing your own solution on it.

== Assessment

Your work on this problem set will be evaluated along four axes primarily.

Scope::
 To what extent does your code implement the features required by our specification?
Correctness::
 To what extent is your code consistent with our specifications and free of bugs?
Design::
 To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?
Style::
 To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Getting Started

Start off by opening up CS50 IDE and then type 

[source,bash]
----
update50
----

within a terminal window to make sure your workspace is up-to-date. 

Next, navigate to your `workspace/chapterA` directory. Once there, execute the following:

[source,bash]
----
wget http://docs.cs50.net/2016/ap/problems/leaky/leaky.zip
----

Unzip that file and navigate to the newly created directory. Inside, you should see four files:

[source,bash]
----
Makefile  leak0.c  leak1.c  leak2.c
----

You can compile each individual `.c` file into a program in the usual way. Or, if you peek inside of `Makefile`, you can see how to compile all three at once!

Finally, take a few minutes to watch Nate's video on Valgrind, a command-line utility that can be used to root out and give you clues on how to fix memory leaks!

video::fvTsFjDuag8[youtube]

== Leaks

Leaks are bad. In real life, we don't want to get wet, so we fix leaks in our roof. As programmers, we are more concerned with __memory leaks__. Not properly allocating and freeing memory can cause programs to suffer segmentation faults, crash your computer, or worse. So in general, they are something to avoid!

In this problem, you'll be tasked with tracking down the leaks in three programs we've written: `leak0`, `leak1` and `leak2`. After making sure the code functions properly (more on that in a second) you'll be expected to make sure that each has a clean bill of health via `valgrind`. That means no leaks, **and** no errors (such as improperly dereferencing a pointer), all of which `valgrind` will tell you about. 

You can run your programs with `valgrind` by typing, e.g.:

[source,bash]
----
valgrind ./leak0
----

which provides a nice summary of what leaks your program is suffered but doesn't particularly provide any decent information on where those errors might live. To do that, we need to explicitly ask `valgrind` to give us more information. More __verbose__ output, as it were. To do so, we can change the command we wish to run slightly:

[source,bash]
----
valgrind -v --leak-check=full ./leak0
----

Notice there are two dash marks before `leak-check=full`, but only a single dash mark before `v`. That's deliberate! Okay, so we know we have to clean these programs up, but what are they actually supposed to do? Compile and run each to test, but you should find that:

* `leak0` seems to generate 50 random numbers and prints them, one per line, to the terminal window.
* `leak1` seems to do the same thing as `leak0`, but does it twice.
* `leak2` seems to print the message `(nil)` 50 times, once per line, then seems to generate 50 random numbers and prints those out as well, one per line.

Opening up `leak0.c`, `leak1.c`, and `leak2.c` will allow you to confirm or detect what the intended behavior of these programs actually is. And of course, it seems that we've neglected to include comments in any of those files and have not exactly given our functions the most intuitive names!footnote:[See how important it is to do these things in your programs??]

Just by running the programs, nothing seems to be amiss. There are no segmentation faults or other obvious crashes. Just to be safe, we should run each through `valgrind` too.

Darn! Well, looks like there's work to be done. And that's where we'll turn to you. Plug these memory leaks for us so that the programs have the behavior their source code intends, in particular making sure that `leak2` does what it should do! 

You are generally free to plug the leaks in any way you wish, bearing in mind the requirement that if the program originally dealt with memory by dynamically allocating it, your fixed version must also use dynamically allocated memory, and cannot thus rely solely on memory from the stack to solve the problem. Once you have a clean bill of health from Valgrind, you're good to go!

To compare your program against the staff solution to see what exactly a clean bill of health looks like (sometimes with the verbose output of `valgrind` it can be difficult to tell!), you may execute the below:

[source,bash]
----
~cs50/chapterA/leakX
----

again, where `X` is replaced by either `0`, `1`, or `2`.

This was Leaky (but hopefully not for long).

