---
layout: 2018/ap
---
:skip-front-matter:

= Problem: Resize

== tl;dr

Implement a program that resizes BMPs, per the below.

[source,subs=quotes]
----
$ [underline]#./resize .25 large.bmp small.bmp#
----

[source,subs=quotes]
----
$ [underline]#./resize 4 small.bmp large.bmp#
----

== Background

Be sure you're familiar with the structure of 24-bit uncompressed BMPs, as introduced in link:../../whodunit/whodunit[Whodunit].

== Assessment

Your work on this problem set will be evaluated along three axes primarily.

Correctness::
  To what extent is your code consistent with our specifications and free of bugs?

Design::
  To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?

Style::
  To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Distribution

=== Downloading

[source,subs="macros"]
----
$ wget https://cdn.cs50.net/ap/2018/problems/resize/resize.zip
$ unzip resize.zip
$ rm resize.zip
$ cd resize
$ ls
bmp.h  copy.c  large.bmp  small.bmp  smiley.bmp
----

== Specification

Implement a program called `resize` that resizes (i.e., enlarges or shrinks) 24-bit uncompressed BMPs by a factor of `f`.

* Implement your program in a file called `resize.c` in a directory called `resize`.
* Your program should accept exactly three command-line arguments, whereby
+
--
** the first (`f`) must be a floating-point value in (0.0, 100.0],
** the second must be the name of a BMP to be resized, and
** the third must be the name of the resized version to be written.
--
+ If your program is not executed with such, it should remind the user of correct usage, as with `fprintf` (to `stderr`), and `main` should return `1`.
* Your program, if it uses `malloc`, must not leak any memory.

== Walkthrough

video::iv9cw-PTSnA[youtube]

== Usage

Your program should behave per the examples below. Assumed that the underlined text is what some user has typed.

[source,subs=quotes]
----
$ [underline]#./resize#
Usage: ./resize n infile outfile
$ [underline]#echo $?#
1
----

[source,subs=quotes]
----
$ [underline]#./resize .5 large.bmp smaller.bmp#
$ [underline]#echo $?#
0
----

[source,subs=quotes]
----
$ [underline]#./resize 2 small.bmp larger.bmp#
$ [underline]#echo $?#
0
----

== Hints

With a program like this, we could have created `large.bmp` out of `small.bmp` by resizing the latter by a factor of 4 (i.e., by multiplying both its width and its height by 4), per the below.

[source]
----
./resize 4 small.bmp large.bmp
----

You're welcome to get started by copying (yet again) `copy.c` and naming the copy `resize.c`. But spend some time thinking about what it means to resize a BMP, particularly if `f` is in (0.0, 1.0). (You may assume that `n` times the size of `infile` will not exceed 2^32^ - 1. As for a value of `1.0` for `f`, the result should indeed be an `outfile` with dimensions identical to ``infile``'s.) How you handle  floating-point imprecision and rounding is entirely up to you, as is how you handle inevitable loss of detail. Decide which of the fields in `BITMAPFILEHEADER` and `BITMAPINFOHEADER` you might need to modify. Consider whether or not you'll need to add or subtract padding to scanlines. And do be sure to support a value of `1` for `n`, the result of which should be an `outfile` with dimensions identical to ``infile``'s.

If you happen to use `malloc`, be sure to use `free` so as not to leak memory. Try using `valgrind` to check for any leaks!

== Testing

If you'd like to peek at, e.g., ``large.bmp``'s headers (in a more user-friendly way than `xxd` allows), you may execute the below.

[source]
----
~cs50/hacker4/peek large.bmp
----

Better yet, if you'd like to compare your outfile's headers against those from the <<staffs-solution,staff's solution>>, you might want to execute commands like the below. (Think about what each is doing.)

[source]
----
./resize 4 small.bmp student.bmp
~cs50/hacker4/resize 4 small.bmp staff.bmp
~cs50/hacker4/peek student.bmp staff.bmp
----

=== Correctness

[source]
----
check50 cs50/problems/2018/ap/resize/more
----

=== Style

[source]
----
style50 resize.c
----

== Staff's Solution

[source]
----
~cs50/unit4/resize/more
----

== How to Submit

=== Step 1 of 3

Update your IDE:

[source]
----
update50
----

=== Step 2 of 3

Ensure you have all of the files below:

* resize.c
* Makefile

Be sure that each of your files are in `~/workspace/unit4/resize`, as with:

[source]
----
cd ~/workspace/unit4/resize
ls
----

If any file is not in `~/workspace/unit4/resize`, move it into that directory, as via `mv` (or via CS50 IDE's lefthand file browser).

=== Step 3 of 3

Submit `resize`:

[source]
----
cd ~/workspace/unit4/resize/
submit50 cs50/2018/ap/resize/more
----

inputting your GitHub username and GitHub password as prompted.

If you run into any trouble, email sysadmins@cs50.harvard.edu!

You may resubmit any problem as many times as you'd like.
 
Your submission should be graded for correctness within 2 minutes, at which point your score will appear at https://cs50.me/[cs50.me]!

This was Resize.