---
layout: default
---
:skip-front-matter:

= Writing Problem: Around the House

== Objectives

* Think critically about computers and computing.
* Learn about how to write with an eye towards a technical audience.

include:: ../../honesty.adoc[]

== Assessment

Your work on this writing problem will be evaluated along three axes primarily.

Scope::
    To what extent does your submission align with the requirements of the specification?
Correctness::
    To what extent is your submission correct and free of factual errors?
Style::
    To what extent is your submission readable (i.e., thoughtfully organized, coherent, words properly spelled)?


To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== OK Computer

If not familiar with what computers are, take a quick look at a more modern spin on them here:

video::WAxH0YHdTuA[youtube,height=540,width=960]

Although they've also been known to be a bit smaller than that:

video::LHdVkPrdRYg[youtube,height=540,width=960]

But perhaps there are some that do not even use electricity?

video::GcDshWmhF4A[youtube,height=540,width=960]

Or perhaps may not even have moving parts?

video::tI0GqYJha1Q[youtube,height=540,width=960]


If you had some preconceived notions about what a computer is, odds are they were challenged somewhat by watching the videos above (particularly the last two!), and that's okay! In fact, you may find that some folks quickly agree that everything shown above is a computer, and some won't. Try speaking with family and friends about it and see if it doesn't spark an interesting discussion.

We'll wait here while you do that.

_(whistles, twiddles thumbs)_

O hai! You're back.

Pull up the definition of the word "computer" a few places online (or in a handy, printed dictionary if you happen to still have one!), and while it's likely you'll find some common threads, it's also quite likely that no two definitions are the same.

For purposes of this course, we define a computer as _a device that accepts input and processes it in some way to produce an output automatically_. Based on that definition, you might see how all four of the devices shown above may be considered computers. You also still may be scratching your head and thinking "Well, wait a minute...". If so, good! You're already beginning the critical-thinking process.

== Writing? I thought I was here to code!

Rest assured, there'll be plenty of time and plenty of opportunity to dive into programming this school year. In fact, the vast majority of the problems you're assigned in this course will require you to program in one or more of the programming languages we'll learn about, such as Scratch, C, PHP, or JavaScript. But occasionally, and a bit more frequently at the very beginning of the course, you'll also be asked to complete some "writing problems" like this. Why? There are two important reasons.

First and foremost, writing is an essential part of your assessment by the College Board for Advanced Placement credit in the course. The assessment consists of three parts:

* The end-of-year multiple-choice examination;
* A through-course assessment called "Create," in which you will independently and with a partner develop programs that solve real-world problems; and
* Another through-course assessment called "Explore," in which you will critically research and investigate an innovation in computing and the impact it has had on the global community.

All the programming problems you'll encounter in this course will adequately prepare you to tackle "Create," and the writing problems are similarly designed to prepare you for "Explore."

Second however, and perhaps more importantly, is that this course aims to educate you more broadly as a _computer scientist_, and not just specifically as a _computer programmer_. Being able to write code is just one tool at your disposal. Among the many characteristics of a computer scientist is his or her ability to communicate effectively with others, both with and without technological backgrounds alike, about computers, emerging technologies, and more. By researching these topics and reading about technology on tech news sites like TechCrunch, Wired, Engadget, and others, you'll not only become more conversant in the jargon that computer scientists use to describe technology, computers, and computing, but you'll also improve in your ability to further relay what you've learned to others.

In some contexts you'll be relaying your newfound knowledge to those with absolutely no background in the subject matter, and to address those individuals you'll need the ability to describe things clearly and, importantly, correctly. In others, you'll be addressing your peers or more technically-oriented audiences, and instead of having to _explain_ a new technology, you will have to _persuade_ that audience about something. Being able to analyze a technology, compare it to others, and point out its relative flaws is an important rhetorical tool to do just that. Organizing your thoughts and communicating them on paper is one of the best ways (particularly if you otherwise might experience stage fright!) to practice this skill.

== OK... Computer?

Have a look around your home. See any computers? Even if you don't have laptops or desktops where you live, odds are you have many more computers in your home than you think. Perhaps you have a smartphone? Maybe you have a flatscreen television or a video game system?

In this problem, we want you to think even more outside the box than that. Recall that we defined a computer as _a device that accepts input, and processes it in some way to produce a result automatically_. Surely there exists some device in your home that adheres to that definition but isn't something that before now you would have readily called a computer. If you can't think of any such device in your home, feel free to venture beyond those four walls and pick any device with which you may be familiar.

In no more than 400 wordsfootnote:[Seriously! In the real world, projects often have specifications just like this one, and it's frequently quite important to adhere to those specifications exactly so that you are in compliance with project scope. So keep it to 400 words, tops!], describe this device in detail. You may wish to consider questions such as:

* What does the device look like?
* What kind of data does it accept?
* How does it process that data?
* What is the result of that processing?

Conduct a little bit of research (formal or informal), and if you suspect others may be skeptical of your assertion that the device you chose is a computer, write persuasively so as to do your best to convince such individuals that you aren't crazy and that you know what you're talking about.

== How to Submit

Submit https://newforms.cs50.net/2016/x/ap/house[this form]!

This was Around the House, your first problem in CS50 AP!
