---
layout: 2017/fall
---
:skip-front-matter:

= CSCI E-50 Syllabus

Introduction to the intellectual enterprises of computer science and the art of programming. This course teaches you how to think algorithmically and solve problems efficiently. Topics include abstraction, algorithms, data structures, encapsulation, resource management, security, software engineering, and web development. Languages include C, Python, SQL, and JavaScript plus CSS and HTML. Problem sets inspired by real-world domains of biology, cryptography, finance, forensics, and gaming. Designed for concentrators and non-concentrators alike, with or without prior programming experience. 68% of CS50 students have never taken CS before.

This course meets on Fridays, 10am-12pm, starting September 1. The course also meets on one Wednesday, September 6, 1pm-2:30pm. Students without conflicts are encouraged to attend all lectures in person this year; students with conflicts may watch later online. All students are expected to attend an orientation meeting in Science Center D on either September 6, 5:30pm-6:30pm, or September 7, 3pm-4pm; students with conflicts may watch later online. See cs50.harvard.edu for FAQs. Required sections to be arranged.

== Expectations

You are expected to:

* attend or watch all lectures,
* attend all sections until the test,
* submit nine problem sets,
* take one test and one quiz, and
* submit a final project.

== Website

https://cs50.harvard.edu/

== Grades

If taking the course for a letter grade, you must ordinarily submit all nine problem sets, take one test and one quiz, and submit a final project in order to be eligible for a satisfactory grade unless granted an exception in writing by the course’s heads.

Final grades are determined using the following weights:

|===
| Problem Sets | 45%
| Test | 25%
| Quiz | 15%
| Final Project| 10%
| Engagement | 5%
|===

Problem sets and the final project are evaluated along axes of correctness, design, and style, with scores ordinarily computed as 3 × correctness + 2 × design + 1 × style. Engagement takes into account participation in sections, office hours, and/or the course's online discussion forum. Scores are normalized across teaching fellows and comfort levels at term's end, so mid-semester comparisons among students of scores are not reliable indicators of standing.

Know that CS50 draws quite the spectrum of students, including "those less comfortable," "those more comfortable," and those somewhere in between. However, what ultimately matters in this course is not so much where you end up relative to your classmates but where you, in Week 11, end up relative to yourself in Week 0.

Each student's final grade is individually determined at term's end. Remarkable effort and upward trending are considered, as is input from the teaching fellows. The course does not have pre-determined cutoffs for final grades. The course is not graded on a curve. Those less comfortable and somewhere in between are not at a disadvantage vis-à-vis those more comfortable.

== Books

No books are required or recommended for this course. However, you might find the below books of interest. Realize that free, if not superior, resources can be found on the course's website.

_C Programming Absolute Beginner's Guide_, Third Edition +
Greg Perry, Dean Miller +
Pearson Education, 2014 +
ISBN 0-789-75198-4

_Hacker's Delight_, Second Edition +
Henry S. Warren Jr. +
Pearson Education, 2013 +
ISBN 0-321-84268-5

_How Computers Work_, Tenth Edition +
Ron White +
Que Publishing, 2014 +
ISBN 0-7897-4984-X

_Programming in C_, Fourth Edition +
Stephen G. Kochan +
Pearson Education, 2015 +
ISBN 0-321-77641-0

CS50 ordinarily meets in Sanders Theatre on Fridays from 10am until 12pm, though the course also meets on Wednesday 9/6 from 1pm until 2:30pm. Students without conflicts are encouraged to attend all lectures in person this year; students with conflicts may watch later online.

A schedule of lectures, subject to change, appears below.

|===
3+| Lecture

| Week 0 | Scratch | Fri 9/1, 10am – 12pm
.2+| Week 1 | C | Wed 9/6, 1pm – 2:30pm
| C, continued | Fri 9/8, 10am – 12pm
| Week 2 | Algorithms | Fri 9/15, 10am – 12pm
| Week 3 | Memory | Fri 9/22, 10am – 12pm
| Week 4 | Data Structures | Fri 9/29, 10am – 12pm
| Week 5 | HTTP | Fri 10/6, 10am – 12pm
.2+| Week 6 | Dynamic Programming | Thu 10/12, 4pm – 5:15pm, streamed from Yale
| Python | Fri 10/13, 10am – 12pm
| Week 7 | Python, continued | Fri 10/20, 10am – 12pm
| Week 8 | SQL | Fri 10/27, 10am – 12pm
| Week 9 | JavaScript | Fri 11/3, 10am – 12pm
| Week 10 | JavaScript, continued | Fri 11/10, 10am – 12pm
| Week 11 | The End | Fri 11/17, 10am – 12pm
|===

== Sections

Lectures are supplemented by weekly, 2-hour sections led by the teaching fellows. You will be asked for your sectioning preferences on Problem Set 0, and you will be assigned to a section (and teaching fellow) shortly thereafter.

Attendance at section is expected up until the test. Sections for CSCI E-50 are held online, by visiting http://cs50.ly/cscie50[cs50.ly/cscie50] at any of the times listed below. Students are welcome to attend any of these three online sessions week to week.

* Sundays, 1–3pm
* Mondays, 8–10pm
* Tuesdays, 7–9pm

A schedule of sections, subject to change, appears below. Recordings of the sections, where available, are linked below as well.

|===
2+| Section

| https://www.youtube.com/watch?v=RJabe6tN3_c[C] | Fri 9/8*
| https://vault.cs50.net/2017/fall/e50/section/2[C, continued] | week of Sun 9/10
| https://vault.cs50.net/2017/fall/e50/section/3[Algorithms] | week of Sun 9/17
| https://vault.cs50.net/2017/fall/e50/section/4[File I/O] | week of Sun 9/24
| Data Structures (https://vault.cs50.net/2017/fall/e50/section/5a[Part 1]), (https://vault.cs50.net/2017/fall/e50/section/5b[Part 2])| week of Sun 10/1
| Review for Test | week of Sun 10/8
| TF's Choice | week of Sun 10/15
| Python | week of Sun 10/22
| SQL | week of Sun 10/29
| JavaScript | week of Sun 11/5
| Review for Quiz | Mon 11/13*
|===

pass:[*] Course-wide and filmed.

== Office Hours

Office hours are opportunities for help with problem sets alongside the course's teaching fellows and course assistants. Office hours for CSCI E-50 are held online, by visiting http://cs50.ly/cscie50[cs50.ly/cscie50] at any of the times listed below.

* Tuesdays, 2–5pm (with Amrit Hothi)
* Tuesdays, 9–10pm (with Pete Gartland)
* Wednesdays, 8–11pm (with Pete Gartland and Teresa Lee)
* Thursdays, 5–6pm (with Teresa Lee)
* Thursdays, 7–9pm (with Eric Twark)
* Fridays, 2–4pm (with Amrit Hothi)
* Fridays, 7–9pm (with Pete Gartland)
* Saturdays, 8–10pm (with Tom Ballatore)

== Tutoring

For students who avail themselves of the course's other resources but still find themselves struggling, the course offers tutoring, to the extent possible, providing opportunities for students to work with the course's staff one-on-one or in particularly small groups. To arrange, contact the course's heads.

== Problem Sets

Nine problem sets are assigned during the semester. Late work is not ordinarily accepted, except in cases of emergency.

A schedule of problem sets appears below.

|===
| Problem Set | Language | Released | Due

| Problem Set 0 | Scratch | Fri 9/1 | Tue 9/5, noon
| Problem Set 1 | C | Wed 9/6 | Mon 9/11, noon
| Problem Set 2 | C | Mon 9/11 | Mon 9/18, noon
| Problem Set 3 | C | Fri 9/15 | Mon 9/25, noon
| Problem Set 4 | C | Fri 9/22 | Mon 10/2, noon
| Problem Set 5 | C | Fri 9/29 | Mon 10/9, noon
| Problem Set 6 | Python | Fri 10/20 | Mon 10/30, noon
| Problem Set 7 | Python, SQL | Fri 10/27 | Mon 11/6, noon
| Problem Set 8 | JavaScript | Fri 11/3 | Mon 11/13, noon
|===

== Test

|===
| Released        | Due

| Fri 10/13, noon | Mon 10/16, noon
|===

Due by noon on Mon 10/16 is a take-home test that will cover Weeks 0 through 5 (and Problem Sets 0 through 5). The test is open-book: you may use any and all non-human resources during the test, but the only humans to whom you may turn for help or from whom you may receive help are the course's heads.

== Quiz

|===
| Released       | Due

| Tue 11/14, noon | Thu 11/16, noon
|===

Due by noon on Thu 11/16 is a take-home quiz that will cover Weeks 0 through 10 (and Problem Sets 0 through 8), with emphasis on Week 6 (and Problem Set 6) onward. The quiz is open-book: you may use any and all non-human resources during the quiz, but the only humans to whom you may turn for help or from whom you may receive help are the course's heads.

== Final Project

The climax of this course is its final project. The final project is your opportunity to take your newfound savvy with programming out for a spin and develop your very own piece of software. So long as your project draws upon this course's lessons, the nature of your project is entirely up to you, albeit subject to the staff's approval. You may implement your project in any language(s) as long as the staff approves. You are welcome to utilize any infrastructure, provided the staff ultimately has access to any hardware and software that your project requires. All that we ask is that you build something of interest to you, that you solve an actual problem, that you impact campus, or that you change the world. Strive to create something that outlives this course.

Inasmuch as software development is rarely a one-person effort, you are allowed an opportunity to collaborate with one or two classmates for this final project. Needless to say, it is expected that every student in any such group contribute equally to the design and implementation of that group's project. Moreover, it is expected that the scope of a two- or three-person group's project be, respectively, twice or thrice that of a typical one-person project. A one-person project, mind you, should entail more time and effort than is required by each of the course's problem sets. Although no more than three students may design and implement a given project, you are welcome to solicit advice from others, so long as you respect the course's policy on academic honesty.

Extensions on the final project are not ordinarily granted, except in cases of emergency. Lateness of submissions is determined down to the minute by submissions' timestamps. Submitting more than seven minutes late is equivalent to not submitting at all.

|===
| Milestone | Date

| Pre-Proposal | Fri 10/27, noon
| Proposal | Fri 11/10, noon
| Status Report | Mon 11/27, noon
| CS50 Hackathon | Thu 11/30, 7pm – Fri 12/1, 7am
| Implementation | Thu 12/7, noon
| CS50 Fair | Fri 12/8, 11am – 4:30pm
|===

== CS50 Hackathon

From 7pm on Thu 11/30 until 7am on Fri 12/1 is the CS50 Hackathon, an epic all-nighter during which you can dive into your final project's implementation alongside classmates (from Harvard and Yale alike!) and staff. If you choose to partake, you'll be asked to propose three milestones for yourself that evening: a "good" one that you intend to achieve no matter what; a "better" one that you think you can achieve; and a "best" one that you hope to achieve.

Dinner will be served around 9pm, second dinner will be served around 1am, and those still standing around 5am will be treated to breakfast at IHOP.

== CS50 Fair

From 11am until 4:30pm on Fri 12/8 is the CS50 Fair, an epic display of final projects. Not only is the CS50 Fair a venue at which to see classmates' projects and demo your own, it is an opportunity to mingle with students, faculty, and staff from across campus as well as recruiters from industry. Attendance is expected of all students.

Also in attendance are popcorn, candy, and a raffle with (fabulous) prizes. Family and friends are welcome to join.

include::../honesty.adoc[]

include::../acknowledgement.adoc[]
