---
published: false
---

== tl;dr

See http://cs50.ly/new[cs50.ly] for what's new and why. See http://cs50.yale.edu/faqs[cs50.yale.edu/faqs] for FAQs. +
Email heads@cs50.yale.edu with questions.

.Lectures
* Thu 9/1 is CS50's first lecture, aka Week 0, 4pm – 5:15pm.
* Students are only expected to attend CS50's first lecture, mid-semester lecture on Thu 10/13, and final lecture on Thu 11/17.
** Watch Week 1's lecture at https://cs50.yale.edu/[cs50.yale.edu] this weekend or early next week.

.Sections
* When submitting Problem Set 0, you'll be asked to section.
* Course-wide "supersections" will be offered next week that anyone can attend (or watch).
** Tue 9/6, 2:30pm – 4pm, in Watson Center B60 for those less comfortable.
** Tue 9/6, 4:30pm – 6pm, in Watson Center B60 for those more comfortable.
* Assigned sections will begin the week after next.

.Problem Sets
* Problem Set 0
** Posted already at https://cs50.yale.edu/[cs50.yale.edu].
** Due by Mon 9/5 at noon. If you add CS50 late, not to worry; email heads@cs50.yale.edu to arrange alternative deadline. All other problem sets have 10-day timeframes.
* Problem Set 1
** To be posted this Fri 9/2 at https://cs50.yale.edu/[cs50.yale.edu].
** Due by Mon 9/12 at noon.

.CS50 Puzzle Day
* This Sat 9/3, 12pm – 3:30pm, at 17 Hillhouse.
* Register at https://cs50.yale.edu/register[cs50.yale.edu/register] (or upon arrival).
