---
layout: default
---
:skip-front-matter:

= Problem: Crack

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

== Objectives

* Become better acquainted with functions and libraries.
* Dabble in cryptanalysis.
* Play the role of an adversary.
* Think more critically about data security.

== Recommended Reading

* Pages 11 – 14 and 39 of http://www.howstuffworks.com/c.htm.
* Chapters 7, 8, and 10 of _Programming in C_.

include::/2016/fall/honesty.adoc[]

== Assessment

Your work on this problem set will be evaluated along four axes primarily.

Scope::
 To what extent does your code implement the features required by our specification?
Correctness::
 To what extent is your code consistent with our specifications and free of bugs?
Design::
 To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?
Style::
 To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Passwords _Et Cetera_

On most, if not all, systems running Linux or UNIX is a file called `/etc/passwd`. By design, this file is meant to contain usernames and passwords, along with other account-related details (e.g., paths to users' home directories and shells). Also by (poor) design, this file is typically world-readable. Thankfully, the passwords therein aren't stored "in the clear" but are instead encrypted using a "one-way hash function."  When a user logs into these systems by typing a username and password, the latter is encrypted with the very same hash function, and the result is compared against the username's entry in `/etc/passwd`. If the two ciphertexts match, the user is allowed in. If you've ever forgotten some password, you may have been told that "I can't look up your password, but I can change it for you."  It could be that person doesn't know how. But, odds are they just can't if a one-way hash function's involved.

Even though passwords in `/etc/passwd` are encrypted, the crypto involved is not terribly strong. Quite often are adversaries, upon obtaining files like this one, able to guess (and check) users' passwords or crack them using brute force (i.e., trying all possible passwords). Only in recent years have (most) system administrators stopped storing passwords in `/etc/passwd`, instead using `/etc/shadow`, which is (supposed to be) readable only by `root`.  (Take a look at `/etc/passwd` in CS50 IDE, for instance; wherever you see `x` a password once was.)  Below, though, are some `username:ciphertext` http://cdn.cs50.net/2015/fall/psets/2/hacker2/passwd[pairs] from an outdated (fake) system.

[source,bash]
----
andi:HALRCq0IBXEPM
caesar:50zPJlUFIYY0o
eli:50MxVjGD7EfY6
hdan:50z2Htq2DN2qs
jason:50CMVwEqJXRUY
john:50TGdEyijNDNY
levatich:50QykIulIPuKI
rob:50q.zrL5e0Sak
skroob:50Bpa7n/23iug
zamyla:HAYRs6vZAb4wo
----

Crack these passwords, each of which has been encrypted with C's DES-based (not MD5-based) crypt function. Specifically, write, in `crack.c`, a program that accepts a single command-line argument: an encrypted password.  (In case you test your code with other ciphertexts, know that command-line arguments with certain characters (e.g., `?`) must be enclosed in single or double quotes; those quotation marks will not end up in `argv` itself.)  If your program is executed without any command-line arguments or with more than one command-line argument, your program should complain and exit immediately, with `main` returning any non-zero `int` (thereby signifying an error that our own tests can detect). Otherwise, your program must proceed to crack the given password, ideally as quickly as possible, ultimately printing to standard output the password in the clear followed by `\n`, nothing more, nothing less, with `main` returning `0`. The underlying design of this program is entirely up to you, but you must explain each and every one of your design decisions, including any implications for performance and accuracy, with profuse comments throughout your source code. Your program must be designed in such a way that it could crack all of the passwords above, even if said cracking might take quite a while. That is to say, it's okay if your code might take several minutes or days or longer to run. What we demand of you is correctness, not necessarily optimal performance. Your program should certainly work on inputs other than these as well; hard-coding into your program the solutions to the above is not acceptable.

Your program must behave per the below; underlined is some sample input.

[source,subs=quotes]
----
:~/workspace/chapter2 $ [underline]#./crack 50Bpa7n/23iug#
12345
----

Assume that users' passwords, as plaintext, are composed of http://en.wikipedia.org/wiki/ASCII#ASCII_printable_characters[printable ASCII characters] and are no longer than four characters long. As for their ciphertexts, you'd best pull up the "man page" (i.e., manual) for `crypt` by executing

[source,bash]
----
man crypt
----

in a terminal window so that you know how the function works. In particular, make sure you understand its use of a "salt."  (According to the man page, a salt "is used to perturb the algorithm in one of 4096 different ways," but why might that be useful?)  As implied by that man page, you'll likely want to put

[source,bash]
----
#define _XOPEN_SOURCE
#include <unistd.h>
----

at the top of your file. Moreover, you'll want to link with `-lcrypt`, as by compiling not with `make` but with:

[source,bash]
----
clang -o crack crack.c -lcrypt
----

You might also want to read up on C's support for file I/O, as there's quite a number of English words in `/usr/share/dict/words` in CS50 IDE that might (or might not) save your program some time. If that file seems to be missing, you can install it with:

[source,bash]
----
sudo apt-get install -y wamerican
----

By design, `/etc/passwd` entrusts the security of passwords to an assumption: that adversaries lack the computational resources with which to crack those passwords. Once upon a time, that may have been true. Perhaps some still do. But when it comes to security, assumptions are dangerous. May that this problem set make that claim all the more real.

We should note that this problem set is no invitation to seek out other passwords to crack.  Do not conflate these Hacker Editions with "black hat" editions. We hope, though, that by understanding better the design of today's systems, you might one day build better systems yourself. Besides acquainting you further with C, this problem set urges you to start questioning designs, as vulnerabilities (if not regrets) often result from poor ones.

If you'd like to play with the staff's own implementation of `crack`, well, sorry! :-) Where'd be the fun in that?

This was Crack.
