---
layout: 2019/ap
---
:skip-front-matter:

= Writing Problem: Be the Teacher

== tl;dr

Think about how to explain Internet-related concepts in layman's terms.

include::../../honesty.adoc[]

== Assessment

Your work on this writing problem will be evaluated along three axes primarily.

Correctness::
    To what extent does your submission align with the requirements of the specification?

Design::
    To what extent is your submission written well (i.e., clearly, efficiently, elegantly, and/or logically)?

Style::
    To what extent is your submission readable (i.e., thoughtfully organized, coherent, words properly spelled)?


To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Throwback

You should now be familiar with all the major components of networks and how they all fit together. Take a minute to think back on everything you've learned. If you need a reminder, these were the topics:

* IP addresses
* DNS
* DHCP
* Routers
* TCP/IP
* HTTP

Remember what each does? Here's your chance to prove it.

Open a text editor and create a file called ‘teacher’ (be sure that the file extension is either .doc, .docx, .pdf, or .txt). In no more than *1500 wordsfootnote:[Seriously! In the real world, projects often have specifications just like this one, and it's frequently quite important to adhere to those specifications exactly so that you are in compliance with project scope. So keep it to 1500 words, tops!], prepare a brief, five- to seven-minute-long speech to give to a class of 3rd graders explaining how the Internet works*. You should cover each of the topics above, but avoid technical jargon - remember, you're teaching elementary school kids! The emphasis is on what each individual component does in practicality and how they all fit together, not teaching terminology and definitions.

Don't be afraid to get creative with your explanations and come up with new analogies and demonstration ideas you haven't yet seen. It's your chance to be the teacher!

== How to Submit

=== Step 1 of 3

Go to https://github.com/me50/USERNAME, substituting `USERNAME` in the URL with your own GitHub username. On the left side of the screen, click on "Branch: master". In the field that says "Find or create a branch...", type `cs50/problems/2019/ap/teacher` and click "Create branch".

=== Step 2 of 3

Click the button that says "Upload files". Drag your `teacher.(doc, docx, pdf, txt)` file into the box that says "Drag files here".

=== Step 3 of 3

Click the green "Commit changes" button and you're done!

If you run into any trouble, email sysadmins@cs50.harvard.edu!

You may resubmit any problem as many times as you'd like before the deadline.

Your submission should be graded for correctness within 2 minutes, at which point your score will appear at https://submit.cs50.io/[submit.cs50.io]!

This was Be the Teacher.
