---
layout: 2018/x
---
:skip-front-matter:

= Problem Set 8: Mashup

== tl;dr
 
[start=0]
. Watch https://video.cs50.net/2018/x/lectures/11[Week 9's lecture].
. Implement a news map.
. Submit your code.

== Getting Started

[source]
----
update50
mkdir ~/workspace/pset8/
cd ~/workspace/pset8/
----

== Problems

Implement link:mashup/mashup.html[Mashup] in `pset8/mashup/`.

== Hints

* Be sure to use Python 3, not Python 2. The former is installed by default on CS50 IDE, but if Google leads you to Python's official documentation, be sure the URLs begin with https://docs.python.org/3/, not https://docs.python.org/2/.
* Insofar as a goal of this problem set is to teach you how to teach yourself a new language, keep in mind that these acts are not only *reasonable*, per the syllabus, but encouraged toward that end:
** Incorporating a few lines of code that you find online or elsewhere into your own code, provided that those lines are not themselves solutions to assigned problems and that you cite the lines' origins.
** Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problem set's problems or your own final project.

== How to Submit

[source]
----
update50
cd ~/workspace/pset8/mashup/
submit50 cs50/2018/x/mashup
----
