---
layout: 2016/x/ap
---
:skip-front-matter:

= Problem: Address Book

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], the `#cs50ap` channel on https://cs50x.slack.com[CS50x Slack] (after signing up), or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

== Objectives

* Further your understanding of HTML and CSS.
* Gain comfort with PHP in a web development context.
* Work with files using PHP.

== Recommended Reading

* http://php.net/manual/en/langref.php
* http://www.w3schools.com/tags/ref_httpmethods.asp
* http://www.w3schools.com/tags/tag_form.asp

include::../../honesty.adoc[]

== Assessment

Your work on this writing problem will be evaluated along four axes primarily.

Scope::
    To what extent does your submission align with the requirements of the specification?
Correctness::
    To what extent is your submission correct and free of factual errors?
Design::
    To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?
Style::
    To what extent is your submission readable (i.e., thoughtfully organized, coherent, words properly spelled)?


To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Getting Ready

Make sure you've taken a good look at the CS50 materials on HTML and PHP.

Here's Doug with a discussion of PHP in a web development context.

video::l5O-HKElXPc[youtube]

And Daven with a few words on HTML!

video::wjkJaQYDxjQ[youtube]

For good measure, take a look at Doug's video on PHP as well, if needing a refresher on the syntax beyond just that used for web development!

video::abUuRqYUUaY[youtube]

Once comfortable, its time to dive in!

== Getting started

Open up your IDE and make sure you have an updated IDE before executing (from within the directory where you are working on problems in Chapter 6, which ordinarily should be `~/workspace/chapter6`):

[source,bash]
----
wget http://docs.cs50.net/2016/ap/problems/address/address.zip
----

Unzip and open up the directory. You should see five files when you list your directory's contents:

[source,bash]
----
contacts.csv  index.html  styles.css submit.php  whoops.html
----

== One Birthday Every Year?

It's the CS50 Muppet's birthday again! As one would expect, he has quite a few friends and, magnanimous muppet that he is, wants to invite them all to his birthday party!

Unfortunately, our friendly neighborhood Muppet has suffered an organizational disaster since his https://docs.cs50.net/2016/ap/problems/party/party.html[last birthday], losing almost all of his contact list. He has a few cobbled together from his phonefootnote:[Yes, Muppets use phones.], others in his emailfootnote:[Yes, Muppets use email.], and a select few he only has on business cardsfootnote:[Yes, Muppets have business cards.]. Instead of sending out lots of individual invitations, our Muppet wants to email all his friends at once (sound familiar?). But to do that, he needs to have all his friends' contact information in the same place, and ideally have a way to add new contacts for safe(r) keeping.

== Contact Me

The good news is, we've volunteered you to help CS50 Muppet out! The task at hand is to create a form in HTML to compile all of the necessary contact information, and make it so that when the form is submitted, the __action__ that form takes is to execute a PHP file that opens up CS50 Muppet's contacts list (stored in a CSV file--do you remember https://en.wikipedia.org/wiki/Comma-separated_values[what that is]?), add a new line to it in that same format, and then close the file. You'll use some of your previous experience working with PHP purely for scripting, as well as drawing upon your newfound knowledge of passing information from a form to a PHP file using `$_GET` or `$_POST`.

How do we do this and what shall you do? Allow us to briefly touch on the five files you've been given and make some suggestions on how to proceed:

=== contacts.csv

Remember that a CSV, or comma separated values file, is quite literally just a list of values separated by commas. Values are grouped together by the line that they are on in the file, thus a newline character separates each row of values. Our file, `contacts.csv`, contains the contact information of CS50 Muppet's friends--or at least it will once you complete this problem!

Our file is structured like this: `first name, last name, street address, city, state, zip code, cake preference`. Notice that these are indeed the column headers that we included in the first line of the file!

As such, CS50's own Milo Banana's contact line would look like this: +
`Milo,Banana,50 CS Way,Cambridge,MA,02138,vanilla`

But how will you fill this file, and ensure that it remains properly organized?

=== index.html

`index.html` will be the portion of the site that the end-user (CS50 Muppet or his friends) will most frequently interact with. It needn't be terribly fancy--though this is a great opportunity to get more practice with CSS--but should simply be a form that collects *all* of the following information:

* first name
* last name
* street address
* city
* state
* zip code
* cake preference

Note again that these are the first few values we've included in `contacts.csv`. As they are the first row, these values aren't actually values, but the column headers! Thus, in every row, we can, and indeed should, expect the value to correspond to that column's header. For example, everything in the first column should have been entered in the "first name" area in the form.

The last question should be a choice between *chocolate* and *vanilla*, but not both. Nor should users be able to enter any other flavors. Unfortunately, CS50 Muppet's favorite bakery is not very flexible with their cake choices.

=== styles.css

This file is simply a basic CSS stylesheet to make our form a little bit easier on CS50 Muppet's eyes. Feel free to play around with it to create your own unique look!

=== submit.php

But how will you get the form results into the CSV file? Well, that's where `submit.php` comes in. Your form in `index.html` should, via `POST`, pass the form information to `submit.php` when the submit button is pressed (naturally). Inside `submit.php`, you should write two things:

. A PHP script that will enter the data from `$_POST` into `contacts.csv`, one row per submission
. A web page with a button that, when clicked, redirects the user back to `index.html` to submit another form

Recall that it is perfectly okay to mix PHP and HTML together, so long as the overall file extension is `.php`, so these two goals can indeed be accomplished in the same file! You'll see that we've provided a very small skeleton to get you started.

Remember also that when you open a file (in C or in PHP) you have to specify the __mode__ in which you are opening it. Be careful not to inadvertently choose the wrong mode! Read up on them a little bit, perhaps checking out the manual page for `fopen`.

One more thing: depending on the way you go about implementing `submit.php`, you may notice that there's a pesky "Submit" in the CSV file at the end of each line. That column doesn't have a header, and is generated by a submit button that you probably used when creating the form. If you see it in the CSV file, find a way to remove it before writing the output! We believe in you.

You will likely find the PHP functions `array_pop`, `header` and `fputcsv` quite helpful. Check out their online manual pages on http://www.php.net[php.net]!

=== whoops.html

But wait, just like an annoying infomercial, there's more. Sometimes, CS50 Muppet types so fast that he misses one of the entry fields for the form. This leads to missing contact information and then missing guests, which no one wants. Add a few lines to `submit.php` to ensure that if any field is empty, the user is instead redirected to `whoops.html`, where there is a button to return to the page and a message that the entry failed. Just like in your earlier version of `submit.php`, you will likely find the PHP function `header` quite useful. Of course, also don't add the incomplete contact to the CSV!

== Party Time

When finished your locally hosted site should be able to:

* Take contact information from CS50 Muppet, entered via a web form
* Ensure that the contact information is complete, redirecting the user to try again if not
* If the contact information is complete, write it to `contacts.csv`

== How to Submit

=== Step 1 of 2

So long as you've previously activated your cs50.me account:

* To submit Address Book, execute
+
[source]
----
cd ~/workspace/chapter6/address
submit50 2016/ap/address
----
+
inputting your GitHub username and GitHub password as prompted.

If you run into any trouble, email sysadmins@cs50.harvard.edu!

You may resubmit any problem as many times as you'd like.

=== Step 2 of 2

Submit https://forms.cs50.net/2016/x/ap/address[this form]!

Your submission should be graded within a few weeks, at which point your score will appear at https://cs50.me/[cs50.me]!

This was Address Book.
