---
layout: default
---
:skip-front-matter:

= Problem: Scratch

== Objectives

* Understand how information can be represented digitally.
* Leverage some fundamental programming constructs.
* Design your own animation, game, or interactive art.
* Impress your friends.

include::../../honesty.adoc[]

== Assessment

Your work on this problem will be evaluated along two axes primarily.

Scope::
    To what extent does your code implement the features required by our specification?
Correctness::
    To what extent is your code free of bugs?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== 1001000 1001001

First curl up with Nate's short on binary, if not too familiar:

video::hacBFrgtQjQ[youtube,height=540,width=960]

And next with Nate's short on ASCII:

video::UPlR4eMMCmI[youtube,height=540,width=960]

Consider these questions rhetorical for now, but odds are they'll come up again! Not to worry if the answers aren't obvious at first. They're meant to induce a bit of thought! The material you've seen so far, along with Nate's videos, should provide you with the building blocks (daresay inputs!) with which to solve these problems.

* How do you represent the (decimal) integer 50 in binary?
* How many bits must be "flipped" (i.e., changed from 0 to 1 or from 1 to 0) in order to capitalize a lowercase `a` that's represented in ASCII?
* How do you represent the (decimal) integer 50 in, oh, "hexadecimal," otherwise known as "base-16"? Know that decimal is considered "base-10" (since it employs 10 digits, 0 through 9), and binary is considered "base-2" (since it employs 2 digits, 0 and 1). Infer from those base systems how to represent base-16! (We'll see base-16 again in the context of graphics and web design later in the course.)

Incidentally, ever seen a _really_ old computer? In the Harvard Science Center, there's a big machine by the main stairwell. It's the link:http://en.wikipedia.org/wiki/Harvard_Mark_I[Harvard Mark I], one of the world's earliest (electro-mechanical) computers, whose purpose was, well, to compute (albeit slowly by today's standards)! You might enjoy this tour by link:http://lewis.seas.harvard.edu/[Prof. Harry Lewis]:

video::4ObouwCHk8w[youtube,height=540,width=960]

== Itching to Program?

Head to http://scratch.mit.edu/ and sign up for an account (if you are 13 or older) on MIT's website by clicking **Join Scratch** atop the page. Any username (that's available) is fine, but take care to remember it and your choice of password.

Then head to http://scratch.mit.edu/help/ and take note of the resources available to you before you dive into Scratch itself. In particular, you might want to skim the link:pass:[http://scratch.mit.edu/scratchr2/static/__1378420408__//pdfs/help/Getting-Started-Guide-Scratch2.pdf][Getting Started Guide].

Next head to http://scratch.mit.edu/projects/26329354/ to see _Pikachu's Pastry Catch_ by Gabe Walker. Click the blue square above the game's top-left corner if you'd like to full-screen the user interface (UI). Then click the green flag. Per Gabe's instructions, as soon as you hit your keyboard's space bar, the game will begin! Feel free to procrastinate a bit. And if you'd like to try out _Ivy's Hardest Game_, by Carlos Peña-Lobel, head to http://scratch.mit.edu/projects/26329347/.

If you've no experience (or comfort) whatsoever with programming, rest assured that Gabe's and Carlos's projects are more complex than what we expect for this problem. (Click *See inside* in Scratch's top-right corner to look at each project's underlying "implementation details.") But they do reveal what you can do with Scratch.

In fact, for a gentler introduction to Scratch (and programming more generally), you might want to review some of the examples that you may have seen previously (and take a look at a few more), the "source code" for which can be found at http://scratch.mit.edu/studios/522341/. Allow David to take you on a tour, though feel free to forge ahead on your own if you'd prefer:

video::tveoFN0NHE0[youtube,height=540,list=PLhQjrBD2T383nc2LUdF5XWbyrsqiYy4nq,width=960]

And you might also want to watch Allison's short on Scratch:

video::52JoFF4HMA4[youtube,height=540,width=960]

Feel free to download the source code for a few more projects from http://scratch.mit.edu/explore/projects/all/ or elsewhere.  For each program, run it to see how it works overall and then look over its scripts to understand how it works underneath the hood. Feel free to make changes to scripts and observe the effects. Once you can say to yourself, "Okay, I think I get this," you're ready to proceed.

Now it's time to choose your own adventure! Your mission is, quite simply, to have fun with Scratch and implement a project of your choice (be it an animation, a game, interactive art, or anything else), subject only to the following requirements (which, to be clear, must all be implemented in order to obtain full Scope points).

* Your project must have at least two sprites, at least one of which must resemble something other than a cat.
* Your project must have at least three scripts total (i.e., not necessarily three per sprite).
* Your project must use at least one condition, one loop, and one variable.
* Your project must use at least one sound.
* Your project should be more complex than some basic examples, but it can be less complex than, say, _Pikachu's Pastry Catch_ and _Ivy's Hardest Game_. As such, your project should probably use at least a few dozen puzzle pieces overall.

Feel free to peruse additional projects online for inspiration, but your own project should not be terribly similar to any of them. Try to think of an idea on your own, and then set out to implement it. But don't try to implement the entirety of your project all at once: pluck off one piece at a time. Gabe, for instance, probably implemented just one pastry first, before he moved onto the game's other sprites. And Carlos probably implemented Yale before he moved on to implementing MIT. In other words, take baby steps: write a bit of code (i.e., drag and drop a few puzzle pieces), test, write a bit more, test, and so forth.

If, along the way, you find it too difficult to implement some feature, try not to fret; alter your design or work around the problem. If you set out to implement an idea that you find fun, you should not find it hard to satisfy this problem's requirements.

Alright, off you go. Make us proud!

Not quite sure how to begin? Feeling a bit overwhelmed? Not to worry. Join Zamyla for a walkthrough of this problem, if you'd like more of a tour:

video::697pD31GCZg[youtube,height=540,width=960]

Incidentally, if you don't have the best Internet access, you're welcome to download Scratch's "offline editor" at http://scratch.mit.edu/scratch2download/. But when done with your project offline, be sure to upload it to your account at http://scratch.mit.edu/ via *File > Share to website* in the offline editor.

Once finished with your project, click *See project page* in Scratch's top-right corner. Ensure your project has a title (in Scratch's top-left corner), some instructions (in Scratch's top-right corner), and some notes and/or credits (in Scratch's bottom-right corner). Then click *Share* in Scratch's top-right corner so that others (e.g., your teacher!) can see your project. Finally, take note of the URL in your browser's address bar. That's your project's URL on MIT's website, and you'll need to know it later.

Oh, and if you'd like to exhibit your project in CS50 AP 1617’s studio with students from around the country taking CS50 AP alongside you, head to https://scratch.mit.edu/studios/3017725/[this link], then click *Add projects*, and paste in your own project's URL.

Incidentally, if curious to learn more about the design of Scratch itself, you might like this segment with our friends from MIT's Media Lab:

video::iLSBUKs4AYU[youtube,height=540,width=960]

== How to Submit

Submit https://newforms.cs50.net/2016/x/ap/scratch[this form]!

This was Scratch!
