---
layout: 2016/ap
---
:skip-front-matter:

= Writing Problem: Degrees of Scalability

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], the `#cs50ap` channel on https://cs50x.slack.com[CS50x Slack] (after signing up), or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

== Objectives

* See how scalable real world applications are.

== Academic Honesty

This course's philosophy on academic honesty is best stated as "be reasonable." The course recognizes that interactions with classmates and others can facilitate mastery of the course's material. However, there remains a line between enlisting the help of another and submitting the work of another. This policy characterizes both sides of that line.

The essence of all work that you submit to this course must be your own. Collaboration on problems is not permitted (unless explicitly stated otherwise) except to the extent that you may ask classmates and others for help so long as that help does not reduce to another doing your work for you. Generally speaking, when asking for help, you may show your code or writing to others, but you may not view theirs, so long as you and they respect this policy's other constraints. Collaboration on quizzes and tests is not permitted at all. Collaboration on the final project is permitted to the extent prescribed by its specification.

Below are rules of thumb that (inexhaustively) characterize acts that the course considers reasonable and not reasonable. If in doubt as to whether some act is reasonable, do not commit it until you solicit and receive approval in writing from your instructor. If a violation of this policy is suspected and confirmed, your instructor reserves the right to impose local sanctions on top of any disciplinary outcome that may include an unsatisfactory or failing grade for work submitted or for the course itself.

=== Reasonable

* Communicating with classmates about problems in English (or some other spoken language).
* Discussing the course's material with others in order to understand it better.
* Helping a classmate identify a bug in his or her code, such as by viewing, compiling, or running his or her code, even on your own computer.
* Incorporating snippets of code that you find online or elsewhere into your own code, provided that those snippets are not themselves solutions to assigned problems and that you cite the snippets' origins.
* Reviewing past years' quizzes, tests, and solutions thereto.
* Sending or showing code that you've written to someone, possibly a classmate, so that he or she might help you identify and fix a bug.
* Sharing snippets of your own solutions to problems online so that others might help you identify and fix a bug or other issue.
* Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problems or your own final project.
* Whiteboarding solutions to problems with others using diagrams or pseudocode but not actual code.
* Working with (and even paying) a tutor to help you with the course, provided the tutor does not do your work for you.

=== Not Reasonable

* Accessing a solution to some problem prior to (re-)submitting your own.
* Asking a classmate to see his or her solution to a problem before (re-)submitting your own.
* Decompiling, deobfuscating, or disassembling the staff's solutions to problems.
* Failing to cite (as with comments) the origins of code, writing, or techniques that you discover outside of the course's own lessons and integrate into your own work, even while respecting this policy's other constraints.
* Giving or showing to a classmate a solution to a problem when it is he or she, and not you, who is struggling to solve it.
* Looking at another individual's work during a quiz or test.
* Paying or offering to pay an individual for work that you may submit as (part of) your own.
* Providing or making available solutions to problems to individuals who might take this course in the future.
* Searching for, soliciting, or viewing a quiz's questions or answers prior to taking the quiz.
* Searching for or soliciting outright solutions to problems online or elsewhere.
* Splitting a problem's workload with another individual and combining your work (unless explicitly authorized by the problem itself).
* Submitting (after possibly modifying) the work of another individual beyond allowed snippets.
* Submitting the same or similar work to this course that you have submitted or will submit to another.
* Using resources during a quiz beyond those explicitly allowed in the quiz's instructions.
* Viewing another's solution to a problem and basing your own solution on it.

== Assessment

Your work on this writing problem will be evaluated along three axes primarily.

Scope::
  To what extent does your submission align with the requirements of the specification?
Correctness::
  To what extent is your submission correct and free of factual errors?
Style::
  To what extent is your submission readable (i.e., thoughtfully organized, coherent, words properly spelled)?


To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Getting Started

No need to open up the IDE for this problem, just get out some good old-fashioned paper and pencilfootnote:[Okay, or open up your IDE and answer these questions in a file called, say, `questions.txt`.].

== Analyze

First, take a look at how Dropbox scales.

video::VECV6r9s5SE[youtube]

Answer the following writing questions, giving both your answer and a justification. There is not necessarily a _correct_ answer to each question, rather the important part is your justification for the choice(s) you make.

. Let's consider the popular social media site, Facebook, and see how scalable it is.
.. Based on your knowledge of Facebook, do you think the website, its applications, and anything else it has are scalable?
.. Do they allow for a large number of users with few bugs? Is all information accurately saved to their database? Would the server crash from overload?
.. How do you think Facebook allows for such a large number of users? How do you think the servers divide the work (e.g., Do they scale vertically? Horizontally? Neither? Both?)?
.. Do you think Facebook is scalable enough that they would no longer have to scale vertically to allow for more users? Remember to justify all answers.
. Now let's look into finance. Consider any online banking service you utilize.
.. Based on your knowledge of your banking service, do you think that it is scalable?
.. Does your banking service allow for a large number of users? Do you think it can handle a large number of users using its service at once or would it crash?
.. With more users, comes more bugs and security risks? Does your banking service ensure security? Does it make sure that no two people can be logged in at once, even if they both try logging in at the same exact time? Can you think of any problems with their service and/or database?
.. Which do you think is more scalable? Facebook or your banking service? Can you think of something that's more scalable than the one you chose?
. Last one! Choose another popular application unrelated to social media and finance and analyze its scalability like we did before.

This was Degrees of Scalability.
