---
layout: 2018/ap
---
:skip-front-matter:

=Syllabus

== Instructor

David J. Malan +
malan@harvard.edu +
http://cs.harvard.edu/malan

== Description

CS50 is Harvard University’s introduction to the intellectual enterprises of computer science and the art of programming for students with a diversity of technological background and experience. CS50 for AP Computer Science Principles is an adaptation of CS50 specifically tailored to align with the AP Computer Science Principles curriculum framework. The course’s assignments, materials, and resources are all identical to the version of the course taught at the college-level, albeit adapted to suit a secondary school audience.

Among this course’s objectives is to supply you with a comprehensive introduction to the fundamentals of the discipline of computer science. We will do so using programming in several different languages as a vehicle to introduce these fundamentals, including such topics as algorithms, abstraction, data, global impact, and internet technologies. Though the course is programming-heavy, it should be stressed that this is not a “programming course”; rather, this course should be considered one of problem-solving, creativity, and exploration. By year’s end, you will have a richer understanding of the key principles of the discipline of computer science. You will be able to speak intelligently about how computers work and how they enable us to become better problem-solvers, and will hopefully be able to communicate that knowledge to others.

Whether you elect to take no other computer science courses in your lifetime or consider this class the first step in a longer course of study, it is our sincere hope that you feel more comfortable with—and indeed sometimes skeptical of—the technologies that surround us each day.

== Expectations

You are expected to submit all problems and coordinate with your high school to complete the http://apcentral.collegeboard.com/apc/public/exam/exam_information/231726.html#anchor2[create and explore tasks].

== Prerequisites

The only background required for CS50 for AP Computer Science Principles is completion of Algebra I or its equivalent.

== Website

This course lives at http://harvard.cs50.edu/ap.

Visit the course's website to watch videos, to get help, to download handouts and software, and to follow links to other resources.

////
== Certificates

Students who earn a satisfactory grade (60% or higher) on every one of the problems will be eligible to receive a certificate from HarvardX as a downloadable, printable PDF.
////

== Books

No books are required for this course. However, you may want to supplement your preparation for or review of some lectures with self-assigned readings relevant to those lectures' content from either of the books below. The first is intended for those inexperienced in (or less comfortable with the idea of) programming. The second is intended for those experienced in (or more comfortable with the idea of) programming.

=== For Those Less Comfortable

_C Programming Absolute Beginner's Guide_, Third Edition +
Greg Perry, Dean Miller +
Pearson Education, 2014 +
ISBN 0-789-75198-4

=== For Those More Comfortable

_Programming in C_, Fourth Edition +
Stephen G. Kochan +
Pearson Education, 2015 +
ISBN 0-321-77641-0

The book below is recommended for those interested in understanding how their own computers work for personal edification.

_How Computers Work_, Ninth Edition +
Ron White +
Que Publishing, 2008 +
ISBN 0-7897-3613-6

This last book below is recommended for aspiring hackers, those interested in programming techniques and low-level optimization of code for applications beyond the scope of this course.

_Hacker's Delight_, Second Edition +
Henry S. Warren Jr. +
Pearson Education, 2013 +
ISBN 0-321-84268-5

== Overview

Consistent with the AP Computer Science Principles curriculum framework, the course’s material is organized around seven so-called “big ideas” as well as six computational thinking practices. The seven big ideas are:

1.	Creativity
2.	Abstraction
3.	Data and Information
4.	Algorithms
5.	Programming
6.	The Internet
7.	Global Impact

And the six computational thinking practices are:

* P1. Connecting Computing
* P2. Creating Computational Artifacts
* P3. Abstracting
* P4. Analyzing Problems and Artifacts
* P5. Communicating (both orally and in writing)
* P6. Collaborating


=== Unit 0 - Computers and Computing

Computers and Computing. How Computers Work. Binary and ASCII. Logic and Processors. Memory. Algorithms.

=== Unit 1 - Building Blocks of Programming

Pseudocode. Scratch. Syntax. Variables. Data Types. Operators. Boolean Expressions and Conditionals. Loops.

=== Unit 2 - Putting the Blocks Together

Compiling. Functions. Arrays and Strings. Command-Line Interaction. Exit Codes. Libraries. Typecasting. Bugs and Debugging.

=== Unit 3 - Thinking Computationally

Linear Search. Bubble Sort. Selection Sort. Insertion Sort. Binary Search. Computational Complexity. Unsolvable Problems. Models and Simulation.

=== Unit 4 - Design, Elegance, and Efficiency

Principles of Good Design. Ncurses. Structures and Encapsulation. Recursion. Merge Sort. Hexadecimal. File I/O. Images. Version Control and Collaboration.

=== Unit 5 - Networking and the Internet

Internet Basics. IP Addresses. DNS and DHCP. Routers. TCP and IP. HTTP. Trust Models. Cybersecurity. HTML. CSS.

=== Unit 6 - Problem Solving in an Interconnected World

Python. Python for Web Programming. SQL. MVC. JavaScript. Ajax. Artificial Intelligence and Machine Learning. Virtual and Augmented Reality.

== Problems

All problems are due on April 30, 2019. You will receive a certificate of completion, if a satisfactory grade (60%) is earned on all problems.

== AP Credit

The completion of this course does not guarantee AP credit through the College Board. To receive credit, you must coordinate with a high school administrator to turn in the additional through assessments, namely the Explore and Create tasks and AP Exam.

== Academic Honesty

This course's philosophy on academic honesty is best stated as "be reasonable." The course recognizes that interactions with classmates and others can facilitate mastery of the course's material. However, there remains a line between enlisting the help of another and submitting the work of another. This policy characterizes both sides of that line.

The essence of all work that you submit to this course must be your own. Collaboration on problem sets is not permitted except to the extent that you may ask classmates and others for help so long as that help does not reduce to another doing your work for you. Generally speaking, when asking for help, you may show your code to others, but you may not view theirs, so long as you and they respect this policy's other constraints. Collaboration on the course's final project is permitted to the extent prescribed by its specification.

Below are rules of thumb that (inexhaustively) characterize acts that the course considers reasonable and not reasonable. If in doubt as to whether some act is reasonable, do not commit it until you solicit and receive approval in writing from the course's heads. Acts considered not reasonable by the course are handled harshly.

=== Reasonable

* Communicating with classmates about problem sets' problems in English (or some other spoken language).
* Discussing the course's material with others in order to understand it better.
* Helping a classmate identify a bug in his or her code at Office Hours, elsewhere, or even online, as by viewing, compiling, or running his or her code, even on your own computer.
* Incorporating snippets of code that you find online or elsewhere into your own code, provided that those snippets are not themselves solutions to assigned problems and that you cite the snippets' origins.
* Reviewing past semesters' quizzes and solutions thereto.
* Sending or showing code that you've written to someone, possibly a classmate, so that he or she might help you identify and fix a bug.
* Sharing snippets of your own code online so that others might help you identify and fix a bug.
* Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problem set's problems or your own final project.
* Whiteboarding solutions to problem sets with others using diagrams or pseudocode but not actual code.
* Working with (and even paying) a tutor to help you with the course, provided the tutor does not do your work for you.

=== Not Reasonable

* Accessing a solution in CS50 Vault to some problem prior to (re-)submitting your own.
* Asking a classmate to see his or her solution to a problem set's problem before (re-)submitting your own.
* Decompiling, deobfuscating, or disassembling the staff's solutions to problem sets.
* Failing to cite (as with comments) the origins of code or techniques that you discover outside of the course's own lessons and integrate into your own work, even while respecting this policy's other constraints.
* Giving or showing to a classmate a solution to a problem set's problem when it is he or she, and not you, who is struggling to solve it.
* Looking at another individual's work during a quiz.
* Paying or offering to pay an individual for work that you may submit as (part of) your own.
* Providing or making available solutions to problem sets to individuals who might take this course in the future.
* Searching for, soliciting, or viewing a quiz's questions or answers prior to taking the quiz.
* Searching for or soliciting outright solutions to problem sets online or elsewhere.
* Splitting a problem set's workload with another individual and combining your work.
* Submitting (after possibly modifying) the work of another individual beyond allowed snippets.
* Submitting the same or similar work to this course that you have submitted or will submit to another.
* Submitting work to this course that you intend to use outside of the course (e.g., for a job) without prior approval from the course's heads.
* Using resources during a quiz beyond those explicitly allowed in the quiz's instructions.
* Viewing another's solution to a problem set's problem and basing your own solution on it.
