---
layout: 2016/fall
---
:skip-front-matter:

= Problem Set 6: Sentimental

== tl;dr
 
. Watch https://video.cs50.net/2016/fall/lectures/8[Week 8's lecture] (and https://video.cs50.net/2016/fall/lectures/6[Week 6's] and https://video.cs50.net/2016/fall/lectures/7[Week 7's], if you haven't already).
. Port some programs from C to Python.
. Analyze some sentiments.
. Submit a form.

include::help-harvard.adoc[]

== Academic Honesty

Do keep in mind the course's policy on http://docs.cs50.net/2016/fall/syllabus/cs50.html#academic-honesty[academic honesty], particularly its "regret clause."

== Getting Started

[source]
----
update50
cd ~/workspace/
wget http://cdn.cs50.net/2016/fall/psets/6/pset6.zip
unzip pset6.zip
rm pset6.zip
----

== Problems

. Implement either of the below exactly as specified but in Python:
+
--
* http://docs.cs50.net/problems/mario/less/mario.html[Mario], less comfortable, in a file called `mario.py` in `pset6/`.
* http://docs.cs50.net/problems/mario/more/mario.html[Mario], more comfortable, in a file called `mario.py` in `pset6/`.
--
+
. Implement either of the below exactly as specified but in Python:
+
--
* http://docs.cs50.net/problems/greedy/greedy.html[Greedy], less comfortable, in a file called `greedy.py` in `pset6/`.
* http://docs.cs50.net/problems/credit/credit.html[Credit], more comfortable, in a file called `credit.py` in `pset6/`.
--
. Implement any (one) of the below exactly as specified but in Python:
+
--
* http://docs.cs50.net/problems/caesar/caesar.html[Caesar], less comfortable, in a file called `caesar.py` in `pset6/`.
* http://docs.cs50.net/problems/vigenere/vigenere.html[Vigenère], less comfortable, in a file called `vigenere.py` in `pset6/`.
* http://docs.cs50.net/problems/crack/crack.html[Crack], more comfortable, in a file called `crack.py` in `pset6/`.
--
. Implement http://docs.cs50.net/problems/sentiments/sentiments.html[Sentiments].

No `check50` for these!

== Hints

* Be sure to use Python 3, not Python 2.
* If a program is in a file called, say, `foo.py`, you can run that program with `python foo.py`.
* For Mario, Greedy, Credit, Caesar, Vigenère, and Crack, it is *reasonable* to look at your own implementations thereof in C and others' implementations thereof in C, including the staff's implementations thereof (and postmortems) in C. It is *not reasonable* to look at others' implementations of the same in Python. It is *not reasonable* to look at others' implementations of Sentiments.
* Insofar as a goal of this problem set is to teach you how to teach yourself a new language, keep in mind that these acts are not only *reasonable*, per the syllabus, but encouraged toward that end:
** Incorporating a few lines of code that you find online or elsewhere into your own code, provided that those lines are not themselves solutions to assigned problems and that you cite the lines' origins.
** Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problem set's problems or your own final project.
* You're welcome to use the CS50 Library for Python, which includes `get_float`, `get_int`, and `get_string`. Just remember to include
+
[source]
import cs50
+
atop your code. Or you can use https://docs.python.org/3/library/functions.html#input[`input`] and validate users' input yourself.
* You might find these references of interest:
** https://docs.python.org/3/reference/index.html[The Python Language Reference]
** https://docs.python.org/3/library/[The Python Standard Library]
** https://docs.python.org/3/tutorial/index.html[The Python Tutorial]

== How to Submit

=== Step 1 of 2

[source]
----
update50
cd ~/workspace/pset6/
submit50 pset6
----

=== Step 2 of 2

Submit https://forms.cs50.net/2016/fall/psets/6[]!
 
This was Problem Set 6.
