---
layout: 2017/fall
title: Instructions
---
:skip-front-matter:

= Instructions

Per the syllabus, CS50 AP is made up of 15 total lectures:
* four "Understanding Technology" lectures, and
* eleven CS50x lectures (Weeks 0-10).

Within each of the above, you'll typically find:

* One lecture. Taught by David in Sanders Theatre at Harvard University, lectures present the week's concepts through examples and demonstrations.
* A short or two (for all comfort levels). Taught by Doug Lloyd '09 in CS50's studio, shorts provide you with opportunities to review a specific topic at slower pace.
* Some notes. A quick guide to lay out the highlights of a given topic.
* A few thought questions. Just some food for thought before you move on to the next topic.
* Additional resources. We’ve linked in some resources outside of CS50 to provide additional scaffolding, especially if you are among those less comfortable.
* Problem(s). Problems include programming and written assignments that challenge you to apply concepts to problems inspired by real-world domains. Embedded in each problem's specification are additional walkthroughs, taught by Zamyla Chan '14 or David in CS50's studio, via which you receive direction on where to begin and how to approach the week's challenges.

== How to Take CS50 AP

To take CS50 AP, then, simply start working your way through the 15 lectures. For each week:
. Watch the week's lecture(s).
. Optionally watch the week's walkthroughs, sections, and shorts.
. If the week includes one or more problems, read their "specifications" and then dive into the problem itself by following the specification's instructions. Note that some of the weeks are accompanied by problems which are entirely **optional**.
. Submit the problem(s) per its directions at the bottom of the problem's specification.

In addition to problems, the course also has https://apcentral.collegeboard.org/pdf/ap-csp-student-task-directions.pdf?course=ap-computer-science-principles[two tasks] required by College Board. Make sure to contact an administrator at your high school to turn in the Explore and Create Tasks. Additionally you will have to coordinate with your school to take the official AP CSP Exam on Friday 15 May 2020.

Of course, if you do not wish to receive AP credit, you’re welcome to take CS50 AP however you'd like! All of CS50 AP’s content will remain available at http://cs50.harvard.edu/ap[CS50 AP] as OpenCourseWare after 30 April 2020, so not to worry if you don't get through it in time!

== Homeschooled Students

If you are taking the course as a homeschooled student, be sure to coordinate with a nearby school, as individuals are not allowed to order exams directly. As per College Board's https://apcentral.collegeboard.org/ap-coordinators/exam-ordering-fees/ordering-materials/home-schooled-student[Homeschooled Students], you must contact an AP coordinator. Your coordinator will create a digital portfolio for the student to enroll in order to submit the performance tasks and arrange a time and place to take the AP CSP exam.

== Enrolled in high school, taking CS50x AP independently

If you are taking the course independently, but enrolled at a high school, be sure to contact your school's AP coordinator for access to the College Board Digital Portfolio and to arrange to take the AP CSP Exam on Friday 15 May 2020. If your school does not offer AP courses or exams, you may have to take your exam at a nearby high school. Contact apstudents@info.collegeboard.org ASAP for more information.

=== Schedule

You are welcome to take CS50 AP at your own pace, so long as you submit all problems and tasks no later than 30 April 2020.

////
=== Certificates

Students who earn a satisfactory grade (70% or higher) on every one of the problems will be eligible to receive a certificate from HarvardX as a downloadable, printable PDF. Note that a certificate is **not** equivalent to AP credit.
////
