---
published: false
---

== tl;dr

See http://cs50.ly/new[cs50.ly] for what's new and why. See http://cs50.ly/faqs[cs50.ly/faqs] for FAQs. +
Email heads@cs50.harvard.edu with questions.

.Lectures
* Wed 8/31 is CS50's first lecture, aka Week 0, 1pm – 2:30pm. Short break around 2pm.
** Aok if you need to leave early to shop; watch rest of lecture at https://cs50.harvard.edu/[cs50.harvard.edu].
* Students are only expected to attend CS50's first lecture and last lecture on Mon 11/21.
** Watch Week 1's lecture at https://cs50.harvard.edu/[cs50.harvard.edu] this weekend or early next week.
* Students may <<simultaneous-enrollment,simultaneously enroll>> in CS50 and another course that meets at the same time.

.Sections
* When submitting Problem Set 0, you'll be asked to section.
* Course-wide "supersections" will be offered next week that anyone can attend (or watch).
* Assigned sections will begin the week after next.

.Problem Sets
* Problem Set 0
** Posted already at https://cs50.harvard.edu/[cs50.harvard.edu].
** Due by Mon 9/5 at noon. If you add CS50 late, not to worry; email heads@cs50.harvard.edu to arrange alternative deadline. All other problem sets have 10-day timeframes.
* Problem Set 1
** To be posted this Fri 9/2 at https://cs50.harvard.edu/[cs50.harvard.edu].
** Due by Mon 9/12 at noon.

.CS50 Puzzle Day
* This Sat 9/3, 12pm – 3:30pm, at i-lab.
* Register at https://cs50.harvard.edu/register[cs50.harvard.edu/register] (or upon arrival).
