---
layout: 2016/fall
---

= Syllabus
:toc: left

version 4

== Description

Introduction to the intellectual enterprises of computer science and the art of programming. This course teaches students how to think algorithmically and solve problems efficiently. Topics include abstraction, algorithms, data structures, encapsulation, resource management, security, software engineering, and web development. Languages include C, PHP, and JavaScript plus SQL, CSS, and HTML. Problem sets inspired by real-world domains of biology, cryptography, finance, forensics, and gaming. Designed for concentrators and non-concentrators alike, with or without prior programming experience

This course ordinarily meets in Sanders Theatre on Mondays and Wednesdays from 1pm until 2pm, but students may simultaneously enroll in another course that meets at the same time. To do so, enroll in the other course via http://my.harvard.edu/[my.harvard.edu], and then email enrollment@fas.harvard.edu to have CS50 added to your study card as well. Undergraduates, GSAS students, and cross-registered students may take CS50 either Satisfactory/Unsatisfactory (SAT/UNS) or for a letter grade. When taken for a letter grade, CS50 meets the General Education requirement for undergraduates for Empirical and Mathematical Reasoning.

== Expectations

You are expected to submit nine problem sets, take two quizzes, and submit a final project.

== Website

This course lives at https://cs50.harvard.edu/.

Visit the course's website to watch videos, to get help, to download handouts and software, and to follow links to other resources.

== Grades

All students, whether taking the course SAT/UNS or for a letter grade, must ordinarily submit all nine problem sets, take both quizzes, and submit a final project in order to be eligible for a satisfactory grade unless granted an exception in writing by the course's heads.

Final grades are determined using the following weights:

[width="40%"]
[grid="none"]
|===
| Problem Sets | 50%
| Quizzes   | 40%
| Final Project| 10%
|===

Problem sets and the final project are evaluated primarily along axes of scope, correctness, design, and style, with scores ordinarily determined by scope × (3 × correctness + 2 × design + 1 × style). Scores are normalized across teaching fellows at term's end, so mid-semester comparisons among students of scores are not reliable indicators of standing.

Although you must submit all nine problem sets, your lowest score among those problem sets on which you received perfect scores for the axis of scope will be dropped when final grades are determined.

Know that CS50 draws quite the spectrum of students, including "those less comfortable," "those more comfortable," and those somewhere in between. However, what ultimately matters in this course is not so much where you end up relative to your classmates but where you, in Week 12, end up relative to yourself in Week 0.

The course is not graded on a curve. The course does not have pre-determined cutoffs for final grades. Those less comfortable and somewhere in between are not at a disadvantage vis-à-vis those more comfortable. Each student's final grade is individually determined at term's end after input from the teaching fellows. Remarkable effort and upward trending are considered. 

== Simultaneous Enrollment

Ordinarily, you may not enroll in courses that meet at the same time or overlapping times. However, you may enroll in CS50 and another course whose meetings overlap fully or partially with CS50’s lectures (and quizzes). *To do so, enroll in the other course via http://my.harvard.edu/[my.harvard.edu], and then email enrollment@fas.harvard.edu to have CS50 added to your study card as well.* You do not need anyone's permission or signature, and you do not need to petition the Administrative Board.

Simultaneously enrolled students are expected to watch videos online and sit for quizzes at 5:30pm instead of 1pm unless otherwise arranged with the course's heads in advance.

== Books 

No books are required for this course. However, you may want to supplement your preparation for or review of some lectures with self-assigned readings relevant to those lectures' content from either of the books below. The first is intended for those inexperienced in (or less comfortable with the idea of) programming. The second is intended for those experienced in (or more comfortable with the idea of) programming. Both are available at the Coop and at sites like http://www.amazon.com/[Amazon.com]. Both have been placed on reserve at http://hcl.harvard.edu/libraries/cabot/[Cabot Library]. Realize that free, if not superior, resources can be found on the https://cs50.harvard.edu/resources[course's website].

=== For Those Less Comfortable 

_C Programming Absolute Beginner's Guide_, Third Edition +
Greg Perry, Dean Miller +
Pearson Education, 2014 +
ISBN 0-789-75198-4

=== For Those More Comfortable 

_Programming in C_, Fourth Edition +
Stephen G. Kochan +
Pearson Education, 2015 +
ISBN 0-321-77641-0

The book below is recommended for those interested in understanding how their own computers work for personal edification. It is available at the Coop and at sites like http://www.amazon.com/[Amazon.com]. And it, too, has been placed on reserve.

_How Computers Work_, Tenth Edition +
Ron White +
Que Publishing, 2014 +
ISBN 0-7897-4984-X

This last book below is recommended for aspiring hackers, those interested in programming techniques and low-level optimization of code for applications beyond the scope of this course. It is also available at the Coop and at sites like http://www.amazon.com/[Amazon.com]. And it, too, has been placed on reserve.

_Hacker's Delight_, Second Edition +
Henry S. Warren Jr. +
Pearson Education, 2013 +
ISBN 0-321-84268-5
 
== Lectures

Most lectures take place at Harvard in Sanders Theatre on Mondays and Wednesdays from 1pm until 2pm. (Four lectures will take place at Yale.) All lectures are live-streamed online and are available on demand immediately thereafter. You are welcome to watch lecture online if you are unable to attend some lecture in person (particularly at Yale!). You are encouraged to watch lectures online for the sake of review. 

A schedule of lectures, subject to change, appears below. 

=== Week 0

__Wed 9/2, Fri 9/4__

Binary. ASCII. Algorithms. Pseudocode. Source code. Compiler. Object code. Scratch. Statements. Boolean expressions. Conditions. Loops. Variables. Functions. Arrays. Threads. Events.

=== Week 1

__Wed 9/9, Fri 9/11__

Linux. C. Compiling. Libraries. Types. Standard output.

=== Week 2

__Mon 9/14, Wed 9/16__

Casting. Imprecision. Switches. Scope. Strings. Arrays. Cryptography.

=== Week 3

__Mon 9/21, Wed 9/23__

Command-line arguments. Searching. Sorting. Bubble sort. Selection sort. Insertion sort. _O_. Ω .Θ. Recursion. Merge Sort.

=== Week 4

__Mon 9/28, Wed 9/30__

Stack. Debugging. File I/O. Hexadecimal. Strings. Pointers. Dynamic memory allocation.

=== Week 5

__Mon 10/5, Wed 10/7__

Heap. Buffer overflow. Linked lists.
Hash tables. Tries. 
Trees. Stacks. Queues.

=== Week 6

__Mon 10/12, Wed 10/14__

TCP/IP. HTTP.
Quiz 0.

=== Week 7

__Mon 10/19, Wed 10/21__

HTML. CSS. PHP.

=== Week 8

__Mon 10/26, Wed 10/28__

MVC. SQL.

=== Week 9

__Mon 11/2, Wed 11/4__

JavaScript. Ajax.

=== Week 10

__Mon 11/9, Wed 11/11__

Security. Artificial intelligence.

=== Week 11

__Mon 11/16, Wed 11/18__

Artificial intelligence, continued. 

Quiz 1.

=== Week 12

__Mon 11/23__

Exciting conclusion.

== Sections

Lectures are supplemented by weekly, 90-minute sections led by the teaching fellows. Sections provide you with opportunities to explore the course's material in a more intimate environment, with only your teaching fellow and a handful of classmates present, as well as to dive into hands-on activities. 

Different sections are offered for those less comfortable, those more comfortable, and those somewhere in between.

Sectioning begins in Week 1. Sections themselves begin in Week 3, with course-wide supersections (open to all students) offered in Week 2.

A schedule of sections (and supersections) will appear on the course's website. 

== Office Hours 

Office hours are opportunities for assistance with problem sets alongside the course's teaching fellows and course assistants. Office hours ordinarily take place from 9pm until midnight in Widener Library on Mondays and Tuesdays and in Annenberg Hall on Wednesdays and Thursdays.

Upon arrival, you'll be greeted by the course's staff, who'll refer you to a particular table for help.

== Walkthroughs

Integrated into problem sets are "walkthroughs," videos via which the course's staff offer direction on where to begin and how to approach a challenge. You are expected to watch walkthroughs before asking questions about problem sets at office hours or via https://cs50.harvard.edu/discuss[CS50 Discuss].

== Postmortems

Available after problem sets' deadlines are "postmortems," videos via which the course's staff explore actual solutions to problem sets. You are expected to watch postmortems for insights into how else you could have (or should have!) implemented your own solutions.

== Tutoring

For students who avail themselves of the course's other resources but still find themselves struggling, the course offers tutoring, to the extent possible, providing opportunities for students to work with the course's staff one-on-one or in particularly small groups. To arrange, contact the course's heads.

== Problem Sets

Nine problem sets are assigned during the semester. Each is due by noon on a Thursday. However, you have nine "late days" that you may "spend" during the semester, each of which provides you with an extension of twenty-four hours. *You may spend no more than one late day on any particular problem set.* You need not inform the staff of your use of a late day; usage of late days is tracked automatically. Lateness of electronic submissions is determined down to the minute by submissions' timestamps. Submitting more than seven minutes late is equivalent to submitting twenty-four hours late. Late work is not ordinarily accepted once you have exhausted your late days, except in cases of medical emergency. These late days cannot be spent on the course's final project.

In order to accommodate students with different backgrounds, some problem sets are released in two editions: a standard edition intended for most students and a "Hacker Edition" intended for some students. Both editions essentially cover the same material. But the Hacker Edition typically presents that material from a more technical angle and poses more sophisticated questions. Hacker Editions are graded separately from standard editions, but those students who submit the former do not receive any form of extra credit outright. When determining grades at term's end, however, we do bear in mind submissions of Hacker Editions.

To be clear, we encourage most students (including aspiring computer scientists) to tackle the standard editions. However, you may choose, week to week, which edition to submit. You may not submit both or some amalgam of the two.

Although you must submit all nine problem sets, your lowest score among those problem sets on which you received a perfect score for the axis of scope will be dropped when final grades are determined.

A schedule of problem sets, subject to change, appears below.

=== Problem Set 0

__due by noon on Thu 9/10__

=== Problem Set 1

__due by noon on Thu 9/17__

=== Problem Set 2

__due by noon on Thu 9/24__

=== Problem Set 3

__due by noon on Thu 10/1__

=== Problem Set 4

__due by noon on Thu 10/8__

=== Problem Set 5

__due by noon on Thu 10/22__

=== Problem Set 6

__due by noon on Thu 10/29__

=== Problem Set 7

__due by noon on Thu 11/5__

=== Problem Set 8

__due by noon on Thu 11/12__

== Quizzes

The course has two 75-minute quizzes. These quizzes are "closed-book," but you may utilize during each quiz one two-sided page (8.5" × 11") of handwritten or typed notes, blank scrap paper, and a pen or pencil, nothing else. 

When final grades are computed, your scores on these two quizzes are weighted equally.

Unless arranged with the course's heads in advance, quizzes cannot ordinarily be taken at alternative times even if missed by accident, except in cases of medical emergency.

A schedule of quizzes, subject to change, appears below. These quizzes take place at 1pm in lieu of lectures on these dates. Simultaneously enrolled students are expected to sit for these quizzes at 5:30pm on these same dates unless otherwise arranged with the course's heads in advance.

=== Quiz 0

__Wed 10/14__

Covers weeks 0 through 5.

=== Quiz 1

__Wed 11/18__

Covers weeks 0 through 11 with emphasis on 6 onward.

== Final Project

The climax of this course is its final project. The final project is your opportunity to take your newfound savvy with programming out for a spin and develop your very own piece of software. So long as your project draws upon this course's lessons, the nature of your project is entirely up to you, albeit subject to the staff's approval. You may implement your project in any language(s) as long as the staff approves. You are welcome to utilize any infrastructure, provided the staff ultimately has access to any hardware and software that your project requires. All that we ask is that you build something of interest to you, that you solve an actual problem, that you impact campus, or that you change the world. Strive to create something that outlives this course.

Inasmuch as software development is rarely a one-person effort, you are allowed an opportunity to collaborate with one or two classmates for this final project. Needless to say, it is expected that every student in any such group contribute equally to the design and implementation of that group's project. Moreover, it is expected that the scope of a two- or three-person group's project be, respectively, twice or thrice that of a typical one-person project. A one-person project, mind you, should entail more time and effort than is required by each of the course's problem sets. Although no more than three students may design and implement a given project, you are welcome to solicit advice from others, so long as you respect the course's policy on academic honesty.

Extensions on the final project are not ordinarily granted, except in cases of medical emergency. Technical difficulties are not considered emergencies. Problem sets' late days cannot be spent on the final project. Lateness of submissions is determined down to the minute by submissions' timestamps. Submitting more than seven minutes late is equivalent to not submitting at all.

=== Pre-Proposal

__due by noon on Mon 11/2__

=== Proposal

__due by noon on Mon 11/9__

=== Status Report

__due by noon on Mon 11/30__

=== CS50 Hackathon

__from 7pm on Thu 12/3 until 7am on Fri 12/4__

=== Implementation

__due by noon on Sun 12/6__

=== CS50 Fair

__from 11am until 4:30pm on Mon 12/7__

== CS50 Hackathon

From 7pm on Thu 12/3 until 7am on Fri 12/4 is the CS50 Hackathon, an epic all-nighter during which you can dive into your final project's implementation alongside classmates (from Harvard and Yale alike!) and staff. If you choose to partake, you'll be asked to propose three milestones for yourself that evening: a "good" one that you intend to achieve no matter what; a "better" one that you think you can achieve; and a "best" one that you hope to achieve.

Dinner will be served around 9pm, second dinner will be served around 1am, and those still standing around 5am will be treated to breakfast at IHOP.

== CS50 Fair

From 11am until 4:30pm on Mon 12/7 is the CS50 Fair, an epic display of final projects. Not only is the CS50 Fair a venue at which to see classmates' projects and demo your own, it is an opportunity to mingle with students, faculty, and staff from across campus as well as recruiters from industry. Attendance is expected of all students.

Also in attendance are popcorn, candy, and a raffle with (fabulous) prizes. Family and friends are welcome to join.

include::../honesty.adoc[]

include::../acknowledgement.adoc[]
