---
layout: 2016/fall
title: CS50 Syllabus
---
:skip-front-matter:

= CS50 Syllabus

Introduction to the intellectual enterprises of computer science and to the art of programming. Students learn how to think algorithmically and solve problems efficiently. Topics include abstraction, algorithms, data structures, encapsulation, resource management, security, software engineering, and web development. Languages include C, Python, SQL, and JavaScript, plus CSS and HTML. Problem sets inspired by real-world domains of biology, cryptography, finance, forensics, and gaming. See
CS50's website, https://cs50.yale.edu, for additional information.

CS50 officially meets on Thursdays, from 4pm until 5:15pm in Sheffield-Sterling-Strathcona Hall (SSS) Room 114, but students are only expected to attend in person the course's first lecture on Thursday 9/1, mid-semester lecture on Thursday 10/13, and final lecture on Thursday 11/17. Sections to be arranged.

Students may take CS50 either Credit/D/Fail or for a letter grade. CS50 satisfies the Quantitative Reasoning Skill requirement. Graduate and professional students are welcome to enroll in CS50.

See http://cs50.ly/new[cs50.ly/new] for what's new and why.

include::yale-tldr.adoc[]

== Expectations

You are expected to

* submit nine problem sets,
* take one test and one quiz, and
* submit a final project.

== Website

https://cs50.yale.edu/

== Grades

You may take this course Credit/D/Fail or for a letter grade.

Whether taking the course Credit/D/Fail or for a letter grade, you must ordinarily submit all nine problem sets, take one test and one quiz, and submit a final project in order to be eligible for a passing grade unless granted an exception in writing by the course's heads. Graduate and professional students are expected to produce a final project that is 50% greater in scope than what is expected of undergraduate students.

Final grades are determined using the following weights:

|===
| Problem Sets | 50%
| Test | 25%
| Quiz | 15%
| Final Project| 10%
|===

Problem sets and the final project are evaluated primarily along axes of scope, correctness, design, and style, with scores ordinarily determined by scope × (3 × correctness + 2 × design + 1 × style). Scores are normalized across teaching assistants at term's end, so mid-semester comparisons among students of scores are not reliable indicators of standing.

Although you must submit all nine problem sets, your lowest score among those problem sets on which you received perfect scores for the axis of scope will be dropped when final grades are determined.

Know that CS50 draws quite the spectrum of students, including "those less comfortable," "those more comfortable," and those somewhere in between. However, what ultimately matters in this course is not so much where you end up relative to your classmates but where you, in Week 11, end up relative to yourself in Week 0.

Each student's final grade is individually determined at term's end. Remarkable effort and upward trending are considered, as is input from the teaching assistants. The course does not have pre-determined cutoffs for final grades. The course is not graded on a curve. Those less comfortable and somewhere in between are not at a disadvantage vis-à-vis those more comfortable. 

== Books 

No books are required or recommended for this course. However, you might find the below books of interest. Realize that free, if not superior, resources can be found on the course's website.

_C Programming Absolute Beginner's Guide_, Third Edition +
Greg Perry, Dean Miller +
Pearson Education, 2014 +
ISBN 0-789-75198-4

_Hacker's Delight_, Second Edition +
Henry S. Warren Jr. +
Pearson Education, 2013 +
ISBN 0-321-84268-5
 
_How Computers Work_, Tenth Edition +
Ron White +
Que Publishing, 2014 +
ISBN 0-7897-4984-X

_Programming in C_, Fourth Edition +
Stephen G. Kochan +
Pearson Education, 2015 +
ISBN 0-321-77641-0

== Lectures

CS50 officially meets on Thursdays, from 4pm until 5:15pm in Sheffield-Sterling-Strathcona Hall (SSS) Room 114, but students are only expected to attend in person the course's first lecture on Thursday 9/1, mid-semester lecture on Thursday 10/13, and final lecture on Thursday 11/17. If you've a conflict, though, you're welcome to watch those lectures online.

Other lectures are filmed a few days in advance, with videos thereof released on Fridays so that you have access to problem sets' material earlier than last year. On Thursdays, CS50 holds "walkthroughs" in SSS 114 for students who would like additional guidance on problem sets; you are welcome but not expected to attend those walkthroughs.

A schedule of lectures, subject to change, appears below. 

|===
2+| Lecture | Date

| Week 0 | Scratch | Thu 9/1, 4pm – 5:15pm
| Week 1 | C | released Fri 9/2, noon
| Week 2 | Arrays | released Fri 9/9, noon
| Week 3 | Algorithms | released Fri 9/16, noon
| Week 4 | Memory | released Fri 9/23, noon
| Week 5 | Data Structures | released Fri 9/30, noon
.2+| Week 6 | ... | released Fri 10/7, noon
| Machine Learning | Thu 10/13, 4pm – 5:15pm
| Week 7 | Python | released Fri 10/14, noon
| Week 8 | HTTP | released Fri 10/21, noon
| Week 9 | SQL | released Fri 10/28, noon
| Week 10 | JavaScript | released Fri 11/4, noon
| Week 11 | The End | Thu 11/17, 4pm – 5:15pm
|===

== Sections

Lectures are supplemented by weekly, 90-minute sections led by the teaching assistants. Different sections are offered for those less comfortable, those more comfortable, and those somewhere in between. You will be asked for your sectioning preferences on Problem Set 0, and you will be assigned to a section (and teaching assistant) shortly thereafter.

A schedule of sections, subject to change, appears below. All teaching assistants' sections are filmed.

|===
| Section | Dates

| C | Tue 9/6*
| Arrays | Mon 9/12, Tue 9/13
| Algorithms | Mon 9/19, Tue 9/20
| File I/O | Mon 9/26, Tue 9/27
| Data Structures | Mon 10/3, Tue 10/4
| Review for Test | Mon 10/10, Tue 10/11
| Python | Mon 10/24, Tue 10/25
| SQL | Mon 10/31, Tue 11/1
| JavaScript | Mon 11/7, Tue 11/8
| Review for Quiz | Mon 11/14, Tue 11/15
|===

pass:[*] Course-wide.

== Office Hours 

Office hours are opportunities for help with problem sets alongside the course's teaching assistants and course assistants.

Office hours begin on Sun 9/4. A schedule of office hours will appear on the course's website.

Each week, the instructors will offer additional time to discuss any and all of students' questions, comments, and concerns about the course or computer science more generally. These dates and times will appear on the aforementioned schedule.

== Walkthroughs

Integrated into problem sets are online "walkthroughs," videos that offer direction on where to begin and how to approach problems. At 4pm on most Thursdays in SSS 114, the course also offers in-person walkthroughs with the instructors for students who would like additional guidance on problem sets; you are welcome but not expected to attend.

== Postmortems

Available after problem sets' deadlines are "postmortems," videos via which the course's staff explore actual solutions to problem sets. You are encouraged to watch postmortems for insights into how else you could have (or should have!) implemented your own solutions.

== Tutoring

For students who avail themselves of the course's other resources but still find themselves struggling, the course offers tutoring, to the extent possible, providing opportunities for students to work with the course's staff one-on-one or in particularly small groups. To arrange, contact the course's heads.

== Problem Sets

Nine problem sets are assigned during the semester. Each is due by noon on a Monday. Late work is not ordinarily accepted, except in cases of emergency. Although you must submit all nine problem sets, your lowest score among those problem sets on which you received a perfect score for the axis of scope will be dropped when final grades are determined.

A schedule of problem sets, subject to change, appears below.

|===
| Problem Set | Language | Released | Due

| Problem Set 0 | Scratch | Wed 8/31 | Mon 9/5, noon
| Problem Set 1 | C | Fri 9/2 | Mon 9/12, noon
| Problem Set 2 | C | Fri 9/9 | Mon 9/19, noon
| Problem Set 3 | C | Fri 9/16 | Mon 9/26, noon
| Problem Set 4 | C | Fri 9/23 | Mon 10/3, noon
| Problem Set 5 | C | Fri 9/30 | Mon 10/10, noon
| Problem Set 6 | Python | Fri 10/21 | Mon 10/31, noon
| Problem Set 7 | Python, SQL | Fri 10/28 | Mon 11/7, noon
| Problem Set 8 | JavaScript | Fri 11/4 | Mon 11/14, noon
|===

== Test

Due by noon on Mon 10/17 is a take-home test that will cover Weeks 0 through 6 (and Problem Sets 0 through 5). The test is open-book: you may use any and all non-human resources during the test, but the only humans to whom you may turn for help or from whom you may receive help are the course's heads.

== Quiz

Due by noon on Thu 11/17 is a take-home quiz that will cover Weeks 0 through 10 (and Problem Sets 0 through 8), with emphasis on Week 7 (and Problem Set 6) onward. The quiz is open-book: you may use any and all non-human resources during the quiz, but the only humans to whom you may turn for help or from whom you may receive help are the course's heads.

== Final Project

The climax of this course is its final project. The final project is your opportunity to take your newfound savvy with programming out for a spin and develop your very own piece of software. So long as your project draws upon this course's lessons, the nature of your project is entirely up to you, albeit subject to the staff's approval. You may implement your project in any language(s) as long as the staff approves. You are welcome to utilize any infrastructure, provided the staff ultimately has access to any hardware and software that your project requires. All that we ask is that you build something of interest to you, that you solve an actual problem, that you impact campus, or that you change the world. Strive to create something that outlives this course.

Inasmuch as software development is rarely a one-person effort, you are allowed an opportunity to collaborate with one or two classmates for this final project. Needless to say, it is expected that every student in any such group contribute equally to the design and implementation of that group's project. Moreover, it is expected that the scope of a two- or three-person group's project be, respectively, twice or thrice that of a typical one-person project. A one-person project, mind you, should entail more time and effort than is required by each of the course's problem sets. Although no more than three students may design and implement a given project, you are welcome to solicit advice from others, so long as you respect the course's policy on academic honesty.

Extensions on the final project are not ordinarily granted, except in cases of emergency. Lateness of submissions is determined down to the minute by submissions' timestamps. Submitting more than seven minutes late is equivalent to not submitting at all.

|===
| Milestone | Date

| Pre-Proposal | Fri 10/28, noon
| Proposal | Fri 11/11, noon
| Status Report | Mon 11/28, noon
| CS50 Hackathon | Thu 12/1, 7pm – Fri 12/2, 7am
| Implementation | Sun 12/11, noon
| CS50 Fair | Mon 12/12, noon – 3pm
|===

== CS50 Hackathon

From 7pm on Thu 12/1 until 7am on Fri 12/2 is the CS50 Hackathon, an epic all-nighter during which you can dive into your final project's implementation alongside classmates (from Yale and Harvard alike!) and staff. If you choose to partake, you'll be asked to propose three milestones for yourself that evening: a "good" one that you intend to achieve no matter what; a "better" one that you think you can achieve; and a "best" one that you hope to achieve.

Dinner will be served around 9pm, second dinner will be served around 1am, and those still standing around 5am will be treated to breakfast at IHOP.

Transportation to and from the CS50 Hackathon in Cambridge will be provided.

== CS50 Fair

From noon until 3pm on Mon 12/12 is the CS50 Fair, an epic display of final projects. Not only is the CS50 Fair a venue at which to see classmates' projects and demo your own, it is an opportunity to mingle with students, faculty, and staff from across campus as well as recruiters from industry. Attendance is expected of all students.

Also in attendance are popcorn, candy, and a raffle with (fabulous) prizes. Family and friends are welcome to join.

include::../honesty.adoc[]

include::../acknowledgement.adoc[]
