= Instructions
:toc: left

Per the syllabus, CS50 AP is made up of 7 chapters, Chapters 0-6. Additionally, if you are among those more comfortable, you can take on two additional chapters, Chapters A and B, that fall between Chapters 4 and 5

Within each chapter, you'll typically find:

* One or two lectures. Taught by David in Sanders Theatre at Harvard Unviersity, lectures present the week's concepts through examples and demonstrations (sometimes followed by cake).
* A few walkthroughs. Taught by David in CS50's studio, walkthroughs walk you through the week's source code (i.e., programming examples) in more detail than in lecture and at a slower pace.
* A section (for all comfort levels). Taught by Doug Lloyd '09 in CS50's studio, sections provide you with opportunities to review the course's material at a slower pace.
* A few shorts. Also filmed in CS50's studio, shorts are bite-sized videos that focus in detail on a particular topic. Presented by CS50's on-campus staff.
* Some notes. A quick guide to lay out the highlights of a given topic.
* A few thought questions. Just some food for thought before you move on to the next topic.
* Additional resources. We’ve linked in some resources outside of CS50 to provide additional scaffolding, especially if you are among those less comfortable.
* Problem(s). Problem sets are programming assignments that challenge you to apply concepts to problems inspired by real-world domains. Embedded in each problem set are additional walkthroughs, taught by Zamyla Chan '14 or David in CS50's studio, via which you receive direction on where to begin and how to approach the week's challenges.

== How to Take CS50 AP

To take CS50 AP, then, simply start working your way through Chapters 0 through 6. For each week:

. Watch the week's lecture(s).
. Optionally watch the week's walkthroughs, sections, and shorts.
. If the week includes a problem, read its "specification" and then dive into the problem itself by following the specification's instructions. Note that some of the problems are accompanied by "Hacker Editions," which are entirely optional.
. Submit the problem(s) per its directions.

In addition to problems, the course also has two tasks required by College Board. Make sure to contact an administrator at your high school to turn in the http://apcsp.org/images/Resources/ExplorePT_2016.pdf[Explore] and http://apcsp.org/images/Resources/CreatePT_2016.pdf[Create] Tasks. Additionally you will have to coordinate with your school to take the official AP CSP Exam on Friday 5 May 2017. 

Of course, if you do not wish to receive AP credit, you’re welcome to take CS50 AP however you'd like! All of CS50 AP’s content will remain available at http://ap.cs50.net[CS50 AP] as OpenCourseWare after 30 April 2017, so not to worry if you don't get through it in time!

=== Schedule

You are welcome to take CS50 AP at your own pace, so long as you submit all problems and tasks no late than 30 April 2017.

////
=== Certificates

Students who earn a satisfactory grade (60% or higher) on every one of the problems will be eligible to receive a certificate from HarvardX as a downloadable, printable PDF. Note that a certificate is not equivalent to AP credit.
////
