---
layout: default
---
:skip-front-matter:

= Problem: Initials

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

==  Objectives

* Become better acquainted with functions and libraries.
* Become comfortable working with strings and arrays.

== Recommended Reading

* Pages 11 – 14 and 39 of http://www.howstuffworks.com/c.htm.
* Chapters 6, 7, 10, 17, 19, 21, 22, 30, and 32 of _Absolute Beginner's Guide to C_.
* Chapters 7, 8, and 10 of _Programming in C_.

include::../../honesty.adoc[]

== Assessment

Your work on this problem set will be evaluated along four axes primarily.

Scope::
 To what extent does your code implement the features required by our specification?
Correctness::
 To what extent is your code consistent with our specifications and free of bugs?
Design::
 To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?
Style::
 To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Getting Ready

First, curl up with the below short on loops...

video::HHmiHx7GGLE[youtube]

Next, take a self-paced tour through a few coding examples that are likely to prove quite useful to you as you work on this and some future problems in this unit, the source code for which can be found at http://cdn.cs50.net/2015/fall/lectures/2/w/src2w/:

video::BYbuuUntOZ4[youtube,list=PLhQjrBD2T380sc-fXwl1sviA-twxFduVU]

You might also find this short on arrays of interest as well!

video::7mOJN1c1JEo[youtube]

== Getting Started

Alright, here we go!

Log into your CS50 IDE workspace and execute

[source,bash]
----
update50
----

within a terminal window to make sure your workspace is up-to-date. If you somehow closed your terminal window (and can't find it!), make sure that *Console* is checked under the *View* menu, then click the green, circled plus (+) in CS50 IDE's bottom half, then select *New Terminal*. If you need a hand, do just ask via the channels noted at the top of this specification.

If you have not done so already, create a new `chapter2` directory, as with

[source,bash]
----
~/workspace/ $ mkdir chapter2
----

Keep in mind that `~` denotes your home directory, `~/workspace` denotes a directory called `workspace` therein, and `~/workspace/chapter2` denotes a directory called `chapter2` within `~/workspace`. After `cd`-ing into `chapter2` (remember how?), your prompt should resemble the below.

[source,bash]
----
~/workspace/chapter2 $
----

Inside of `chapter2`, create a new `initials` directory, as with

[source,bash]
----
~/workspace/chapter2/ $ mkdir initials
----

Now `cd` into the initials directory. If your prompt resembles the below, you're all set!

[source,bash]
----
~/workspace/chapter2/initials/ $
----

If not, retrace your steps and see if you can determine where you went wrong. You can actually execute

[source,bash]
----
history
----

at the prompt to see your last several commands in chronological order if you'd like to do some sleuthing. You can also scroll through the same one line at a time by hitting your keyboard's up and down arrows; hit Enter to re-execute any command that you'd like. If still unsure how to fix, remember that the online forums are your friends!

== Specification

Design and implement a program, `initials`, that, given a person's name, prints a person's initials.

* Implement your program in a file called `initials.c` in a directory called `initials`.
* Your program should prompt a user for their name using `get_string` to obtain their name as a `string`.
* You may assume that the user's input will contain only letters (uppercase and/or lowercase) plus single spaces between words. You don't need to worry about names like `Joseph Gordon-Levitt`, `Conan O'Brien`, or `David J. Malan`!
* Your program should print the user's initials (i.e., the first letter of each word in their name) with no spaces or periods, followed by a newline (`\n`).

== Walkthrough

video::UItYCp0Ivqg[youtube]

== Usage

Your program should behave per the examples below. Assumed that the underlined text is what some user has typed.

[source,subs=quotes]
----
$ [underline]#./initials#
[underline]#Zamyla Chan#
ZC
----

[source,subs=quotes]
----
$ [underline]#./initials#
[underline]#robert thomas bowden#
RTB
----

== Testing

=== `check50`

[source]
----
check50 1718.chapter2.initials initials.c
----

== Staff Solution

[source]
----
~cs50/chapter2/initials
----

== FAQs

Might the user's input start or end with spaces?::
No, you may assume that the only spaces in the user's input will be single spaces between words. A previous version of this problem's walkthrough incorrectly stated that there might be spaces at the start or end of the user's input, but the video has since been fixed! Apologies for any confusion!
