---
layout: 2018/fall
---

= Mario

== tl;dr

Implement a program that prints out a half-pyramid of a specified height, per the below.

[source,subs="macros,quotes"]
----
$ [underline]#python mario.py#
Height: [underline]#5#
    pass:[#]
   pass:[##]
  pass:[###]
 pass:[####]
pass:[#####]

$ [underline]#python mario.py#
Height: [underline]#3#
  pass:[#]
 pass:[##]
pass:[###]
----

== Specification

* Write, in a file called `mario.py` in `~/workspace/pset6/mario/less/`, a program that recreates this half-pyramid using hashes (`#`) for blocks, exactly as you did in link:https://lab.cs50.io/cs50/labs/2018/fall/mario/less/[Problem Set 1], except that your program this time should be written (a) in Python and (b) in CS50 IDE.
* To make things more interesting, first prompt the user for the half-pyramid's height, a non-negative integer no greater than `8`.
* If the user fails to provide a non-negative integer no greater than `8`, you should re-prompt for the same again.
* Then, generate (with the help of `print` and one or more loops) the desired half-pyramid.
* Take care to align the bottom-left corner of your half-pyramid with the left-hand edge of your terminal window.

== Walkthrough

video::syt3NZhllwc[youtube]

== Usage

Your program should behave per the example below. Assumed that the underlined text is what some user has typed.

[source,subs="macros,quotes"]
----
$ [underline]#python mario.py#
Height: [underline]#4#
   pass:[#]
  pass:[##]
 pass:[###]
pass:[####]
----

[source,subs="macros,quotes"]
----
$ [underline]#python mario.py#
Height: [underline]#0#
----

[source,subs="macros,quotes"]
----
$ [underline]#python mario.py#
Height: [underline]#-5#
Height: [underline]#4#
   pass:[#]
  pass:[##]
 pass:[###]
pass:[####]
----

[source,subs="macros,quotes"]
----
$ [underline]#python mario.py#
Height: [underline]#-5#
Height: [underline]#five#
Height: [underline]#40#
Height: [underline]#24#
Height: [underline]#4#
   pass:[#]
  pass:[##]
 pass:[###]
pass:[####]
----

== Testing

=== Correctness

[source]
----
check50 cs50/2018/fall/sentimental/mario/less
----

=== Style

[source]
----
style50 mario.py
----

== Staff Solution

[source]
----
~cs50/pset1/mario
----

== Hints

Try to establish a relationship between (a) the height the user would like the pyramid to be, (b) what row is currently being printed, and (c) how many spaces and how many hashes are in that row. Once you establish the formula, you can translate that to Python!
