---
layout: 2017/x
---
:skip-front-matter:

= Problem Set 5: Mispellings

== tl;dr
 
. Watch https://video.cs50.net/2016/fall/lectures/5[Week 5's lecture].
. Answer some questions about a spell checker.
. Implement a spell checker.
. Submit a form.

== Help

For help with Week 5 and Problem Set 5:

* Watch Zamyla's walkthroughs herein.
* Take advantage of `help50`, `eprintf`, and `debug50`.
* Start a https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/[discussion] with classmates.

== Getting Started

Log into https://cs50.io/[cs50.io] and execute

[source]
----
update50
----

within a terminal window to make sure your workspace is up-to-date. 

Next, execute

[source]
----
mkdir ~/workspace/pset5/
----

at your prompt in order to make a directory called `pset5` in your `workspace` directory.

Now execute

[source]
----
cd ~/workspace/pset5/
----

and your prompt should resemble the below.

[source]
----
~/workspace/pset5/ $
----

== Problems

* Implement link:../../../../problems/speller/speller.html[Speller]

== How to Submit

Be sure you've signed up for a https://github.com/join[GitHub account], per Problem Set 0, and that you've logged into and authorized https://cs50.me/[CS50.me] at least once, per Problem Set 1!

=== Step 1 of 2

* Update your IDE:
+
[source]
----
update50
----
* Submit `speller`:
+
[source]
----
cd ~/workspace/pset5/speller/
submit50 cs50/2017/x/speller
----

=== Step 2 of 2

Submit https://forms.cs50.net/2017/x/psets/5[this form]!
 
This was Problem Set 5.
