---
layout: default
---
:skip-front-matter:

= Writing Problem: Decisions

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], the `#cs50ap` channel on https://cs50x.slack.com[CS50x Slack] (after signing up), or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

== tl;dr

Analyze the pros and cons of various data structures.

include::../../honesty.adoc[]

== Assessment

Your work on this writing problem will be evaluated along three axes primarily.

Scope::
  To what extent does your submission align with the requirements of the specification?
Correctness::
  To what extent is your submission correct and free of factual errors?
Style::
  To what extent is your submission readable (i.e., thoughtfully organized, coherent, words properly spelled)?


To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Getting Started

No need to open up the IDE for this problem, just get out some good old-fashioned paper and pencilfootnote:[Okay, or open up your IDE and answer these questions in a file called, say, `questions.txt`.].

== Decisions
Answer the following writing questions, giving both the answer and a justification. There is not necessarily a __correct__ answer to each question, rather the important part is your justification for the choice(s) you make. Describe both the data structure you would use, your method of implementing it, and why you would choose that data structure over alternatives.

[start=0]
. A school needs to write a program that stores data on its students. The school must be able to easily add students to its list, as new students arrive fairly often, and remove students. The list must also be sorted at all times, and allow for quick searching in case a particular student's information is needed quickly. How should the school store the data on its students?
. A bank needs to come up with a system for serving its customers. There are three levels of accounts a customer can have with the bank, with the highest levels getting priority in line. Each customer fills out a brief check-in form when they arrive. How should the bank store and organize the forms so that it can serve customer's in the proper order?
. A freight company must keep track of its trains. Train cars can be added to the front and back of any train, and removed from the front and back, and the company wants the data for all trains centralized in the same place. How should the company track the cars on its trains, and how should they keep track of all the trains together?

This was Decisions.
