---
layout: 2018/ap
---
:skip-front-matter:

= Problem: Sentimental

== tl;dr

Port some programs from C to Python.

include::../../honesty.adoc[]

== Assessment

Your work on this problem set will be evaluated along three axes primarily.

Correctness::
  To what extent is your code consistent with our specifications and free of bugs?

Design::
  To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?

Style::
  To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Getting Started

Login to your CS50 IDE and execute the following:

[source]
----
update50
mkdir ~/workspace/unit6/
cd ~/workspace/unit6/
mkdir sentimental
----

== Well-Distributed

Here's some good news for you right off the bat: you've seen almost everything we're going to talk about in this problem once before. We're going to revisit three old programs and port them to C.

== Problems

All code that you write should be consistent with https://www.python.org/dev/peps/pep-0008/[Style Guide for Python Code], otherwise known as PEP 8.

. Implement either of the below exactly as specified but in Python:
+
--
* link:../mario/less/mario.html[Mario], less comfortable, in a file called `mario.py` in `unit6/`.
* link:../mario/more/mario.html[Mario], more comfortable, in a file called `mario.py` in `unit6/`.
--
+

== Walkthroughs

video::syt3NZhllwc[youtube]
video::gqS876f0lk0[youtube]

. Implement the problems below exactly as specified but in Python:
+
--
* link:../cash/cash.html[Cash], in a file called `cash.py` in `unit6/`.
* link:../caesar/caesar.html[Caesar], in a file called `caesar.py` in `unit6/`.
--

== Walkthroughs

video::f3iMmGry05Q[youtube]
video::5I7QqTTolHE[youtube]

== Testing

=== Correctness

```
check50 cs50/2018/ap/sentimental/mario/less
check50 cs50/2018/ap/sentimental/mario/more
check50 cs50/2018/ap/sentimental/cash
check50 cs50/2018/ap/sentimental/caesar
```

=== Style

```
style50 mario.py
style50 cash.py
style50 caesar.py
```

== Hints

* Be sure to use Python 3, not Python 2. The former is installed by default on CS50 IDE, but if Google leads you to Python's official documentation, be sure the URLs begin with https://docs.python.org/3/, not https://docs.python.org/2/.
* If a program is in a file called, say, `foo.py`, you can run that program with `python foo.py`.
* For Mario, Cash, and Caesar, it is *reasonable* to look at your own implementations thereof in C and others' implementations thereof in C, including the staff's implementations thereof (and postmortems) in C. It is *not reasonable* to look at others' implementations of the same in Python.
* Consider this problem set an opportunity not only to port your own prior work from C to Python but to improve upon your earlier designs using lessons learned since!
* When porting code from C to Python in CS50 IDE, you might want to select *View > Layout > Horizontal Split* so that you can see both side by side.
* Insofar as a goal of these problems is to teach you how to teach yourself a new language, keep in mind that these acts are not only *reasonable*, per the syllabus, but encouraged toward that end:
** Incorporating a few lines of code that you find online or elsewhere into your own code, provided that those lines are not themselves solutions to assigned problems and that you cite the lines' origins.
** Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problem set's problems or your own final project.
* You're welcome to use the CS50 Library for Python, which includes `get_float`, `get_int`, and `get_string`. Just remember to include any of
+
[source]
----
from cs50 import get_float
from cs50 import get_int
from cs50 import get_string
----
+
atop your code. Or you can use https://docs.python.org/3/library/functions.html#input[`input`] and validate users' input yourself.
* You might find https://docs.python.org/3/library/functions.html#chr[`chr`] and/or https://docs.python.org/3/library/functions.html#ord[`ord`] of help.
* You might find these references of interest:
** https://docs.python.org/3/reference/index.html[The Python Language Reference]
** https://docs.python.org/3/library/[The Python Standard Library]
** https://docs.python.org/3/tutorial/index.html[The Python Tutorial]

== How to Submit

=== Step 1 of 2

Recall that you were asked to create the files below:

* `mario.py`
* `greedy.py`
* `caesar.py`

Be sure that each of your files is in `~/workspace/unit6/sentimental/`, as with:

[source]
----
cd ~/workspace/unit6/sentimental/
ls
----

If any file is not in `~/workspace/unit6/sentimental/`, move it into that directory, as via `mv` (or via CS50 IDE's lefthand file browser).

=== Step 2 of 2

* To submit `mario` (less comfy), execute
+
[source]
----
cd ~/workspace/unit6/sentimental/
submit50 cs50/2018/ap/sentimental/mario/less
----
+
inputting your GitHub username and GitHub password as prompted.
* To submit `mario` (more comfy), execute
+
[source]
----
cd ~/workspace/unit6/sentimental/
submit50 cs50/2018/ap/sentimental/mario/more
----
+
inputting your GitHub username and GitHub password as prompted.
* To submit `greedy`, execute
+
[source]
----
cd ~/workspace/unit6/sentimental/
submit50 cs50/2018/ap/sentimental/greedy
----
+
inputting your GitHub username and GitHub password as prompted.
* To submit `caesar`, execute
+
[source]
----
cd ~/workspace/unit6/sentimental/
submit50 cs50/2018/ap/sentimental/caesar
----
+
inputting your GitHub username and GitHub password as prompted.

If you run into any trouble, email sysadmins@cs50.harvard.edu!

You may resubmit any problem as many times as you'd like before the deadline.

Your submission should be graded for correctness within 2 minutes, at which point your score will appear at https://cs50.me/[cs50.me]!

This was Sentimental.
