---
layout: 2017/x
---
:skip-front-matter:

= Problem Set 6: Sentimental

== tl;dr
 
. Watch https://video.cs50.net/2016/fall/lectures/8[Week 8's lecture] (and https://video.cs50.net/2016/fall/lectures/6[Week 6's] and https://video.cs50.net/2016/fall/lectures/7[Week 7's], if you haven't already).
. Port some programs from C to Python.
. Analyze some sentiments.
. Submit a form.

== Help

For help with Weeks 6 – 8 and Problem Set 6:

* Watch Zamyla's walkthroughs herein.
* Start a https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/[discussion] with classmates.

== Getting Started

[source]
----
update50
mkdir ~/workspace/pset6/
cd ~/workspace/pset6/
----

== Problems

All code that you write should be consistent with https://www.python.org/dev/peps/pep-0008/[Style Guide for Python Code], otherwise known as PEP 8.

. Implement either of the below exactly as specified but in Python:
+
--
* link:../../../../problems/mario/less/mario.html[Mario], less comfortable, in a file called `mario.py` in `pset6/`.
* link:../../../../problems/mario/more/mario.html[Mario], more comfortable, in a file called `mario.py` in `pset6/`.
--
+
. Implement either of the below exactly as specified but in Python:
+
--
* link:../../../../problems/greedy/greedy.html[Greedy], less comfortable, in a file called `greedy.py` in `pset6/`.
* link:../../../../problems/credit/credit.html[Credit], more comfortable, in a file called `credit.py` in `pset6/`.
--
. Implement any (one) of the below exactly as specified but in Python:
+
--
* link:../../../../problems/caesar/caesar.html[Caesar], less comfortable, in a file called `caesar.py` in `pset6/`.
* link:../../../../problems/vigenere/vigenere.html[Vigenère], less comfortable, in a file called `vigenere.py` in `pset6/`.
* link:../../../../problems/crack/crack.html[Crack], more comfortable, in a file called `crack.py` in `pset6/`.
--
. Implement link:../../../../problems/sentiments/sentiments.html[Sentiments] in `pset6/sentiments/`.

No `check50` for these!

== Hints

* Be sure to use Python 3, not Python 2.
* If a program is in a file called, say, `foo.py`, you can run that program with `python foo.py`.
* For Mario, Greedy, Credit, Caesar, Vigenère, and Crack, it is *reasonable* to look at your own implementations thereof in C and others' implementations thereof in C, including the staff's implementations thereof (and postmortems) in C. It is *not reasonable* to look at others' implementations of the same in Python. It is *not reasonable* to look at others' implementations of Sentiments.
* Consider this problem set an opportunity not only to port your own prior work from C to Python but to improve upon your earlier designs using lessons learned since!
* When porting code from C to Python in CS50 IDE, you might want to select *View > Layout > Horizontal Split* so that you can see both side by side.
* Insofar as a goal of this problem set is to teach you how to teach yourself a new language, keep in mind that these acts are not only *reasonable*, per the syllabus, but encouraged toward that end:
** Incorporating a few lines of code that you find online or elsewhere into your own code, provided that those lines are not themselves solutions to assigned problems and that you cite the lines' origins.
** Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problem set's problems or your own final project.
* You're welcome to use the CS50 Library for Python, which includes `get_float`, `get_int`, and `get_string`. Just remember to include
+
[source]
import cs50
+
atop your code. Or you can use https://docs.python.org/3/library/functions.html#input[`input`] and validate users' input yourself.
* You might find https://docs.python.org/3/library/functions.html#chr[`chr`] and/or https://docs.python.org/3/library/functions.html#ord[`ord`] of help.
* You might find these references of interest:
** https://docs.python.org/3/reference/index.html[The Python Language Reference]
** https://docs.python.org/3/library/[The Python Standard Library]
** https://docs.python.org/3/tutorial/index.html[The Python Tutorial]

== Walkthroughs

=== Mario

==== less comfortable

video::syt3NZhllwc[youtube,height=540,width=960]

==== more comfortable

video::gqS876f0lk0[youtube,height=540,width=960]

=== Greedy

video::f3iMmGry05Q[youtube,height=540,width=960]

=== Credit

video::o2nVBm9S3iw[youtube,height=540,width=960]

=== Caesar

_Coming Soon_

=== Vigenère

_Coming Soon_

=== Crack

_Coming Soon_

=== Sentiments

See link:../../../../problems/sentiments/sentiments.html#walkthrough[Sentiments].

== How to Submit

Be sure you've signed up for a https://github.com/join[GitHub account], per Problem Set 0, and that you've logged into https://cs50.me/[CS50.me] at least once, per Problem Set 1!

=== Step 1 of 2

[source]
----
update50
cd ~/workspace/pset6/
submit50 2017/x/pset6
----

=== Step 2 of 2

Submit https://newforms.cs50.net/2017/x/psets/6[this form]!
 
This was Problem Set 6.
