---
layout: 2016/ap
---
:skip-front-matter:

= Problem: Sudoku (Part 2)

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], the `#cs50ap` channel on https://cs50x.slack.com[CS50x Slack] (after signing up), or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

== Objectives

* Continue to use ncurses, a rudimentary library for GUIs.
* Design and implement larger pieces of software.
* Think deliberately about design.
* Become a Sudoku master.

== Recommended Reading

* Sections 1&mdash;13 of http://tldp.org/HOWTO/NCURSES-Programming-HOWTO/.

== Academic Honesty

This course's philosophy on academic honesty is best stated as "be reasonable." The course recognizes that interactions with classmates and others can facilitate mastery of the course's material. However, there remains a line between enlisting the help of another and submitting the work of another. This policy characterizes both sides of that line.

The essence of all work that you submit to this course must be your own. Collaboration on problems is not permitted (unless explicitly stated otherwise) except to the extent that you may ask classmates and others for help so long as that help does not reduce to another doing your work for you. Generally speaking, when asking for help, you may show your code or writing to others, but you may not view theirs, so long as you and they respect this policy's other constraints. Collaboration on quizzes and tests is not permitted at all. Collaboration on the final project is permitted to the extent prescribed by its specification.

Below are rules of thumb that (inexhaustively) characterize acts that the course considers reasonable and not reasonable. If in doubt as to whether some act is reasonable, do not commit it until you solicit and receive approval in writing from your instructor. If a violation of this policy is suspected and confirmed, your instructor reserves the right to impose local sanctions on top of any disciplinary outcome that may include an unsatisfactory or failing grade for work submitted or for the course itself.

=== Reasonable

* Communicating with classmates about problems in English (or some other spoken language).
* Discussing the course's material with others in order to understand it better.
* Helping a classmate identify a bug in his or her code, such as by viewing, compiling, or running his or her code, even on your own computer.
* Incorporating snippets of code that you find online or elsewhere into your own code, provided that those snippets are not themselves solutions to assigned problems and that you cite the snippets' origins.
* Reviewing past years' quizzes, tests, and solutions thereto.
* Sending or showing code that you've written to someone, possibly a classmate, so that he or she might help you identify and fix a bug.
* Sharing snippets of your own solutions to problems online so that others might help you identify and fix a bug or other issue.
* Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problems or your own final project.
* Whiteboarding solutions to problems with others using diagrams or pseudocode but not actual code.
* Working with (and even paying) a tutor to help you with the course, provided the tutor does not do your work for you.

=== Not Reasonable

* Accessing a solution to some problem prior to (re-)submitting your own.
* Asking a classmate to see his or her solution to a problem before (re-)submitting your own.
* Decompiling, deobfuscating, or disassembling the staff's solutions to problems.
* Failing to cite (as with comments) the origins of code, writing, or techniques that you discover outside of the course's own lessons and integrate into your own work, even while respecting this policy's other constraints.
* Giving or showing to a classmate a solution to a problem when it is he or she, and not you, who is struggling to solve it.
* Looking at another individual's work during a quiz or test.
* Paying or offering to pay an individual for work that you may submit as (part of) your own.
* Providing or making available solutions to problems to individuals who might take this course in the future.
* Searching for, soliciting, or viewing a quiz's questions or answers prior to taking the quiz.
* Searching for or soliciting outright solutions to problems online or elsewhere.
* Splitting a problem's workload with another individual and combining your work (unless explicitly authorized by the problem itself).
* Submitting (after possibly modifying) the work of another individual beyond allowed snippets.
* Submitting the same or similar work to this course that you have submitted or will submit to another.
* Using resources during a quiz beyond those explicitly allowed in the quiz's instructions.
* Viewing another's solution to a problem and basing your own solution on it.

== Assessment

Your work on this problem set will be evaluated along four axes primarily.

Scope::
 To what extent does your code implement the features required by our specification?
Correctness::
 To what extent is your code consistent with our specifications and free of bugs?
Design::
 To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?
Style::
 To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Getting Started

Below are two options for getting started with this problem. The first option is for those who wish to start with the staff's implementation of the features from http://cdn.cs50.net/ap/1516/problems/4/0/4-0.html[Problem 4-0] already implemented for them. The second option is for those who wish to complete their own implementation of Sudoku, relying on their own solution to Problem 4-0 as their foundation. **Only choose one of the below two options**.

Then, after having chosen your option and followed all the steps therein, pick up at "The student becomes the teacher".

First, log into https://cs50.io/[cs50.io] and execute

[source,bash]
----
update50
----

within a terminal window to make sure your workspace is up-to-date. 

=== Option 1: Start from a Clean Slate

In your terminal window, execute

[source,bash]
----
cd ~/workspace/chapter4
----

Then execute:

[source,bash]
----
wget http://docs.cs50.net/2016/ap/problems/sudoku/2/sudoku2.zip
----

Confirm you've downloaded that file, then

[source,bash]
----
unzip sudoku2.zip
----

and then remove the ZIP file

[source,bash]
----
rm -f sudoku2.zip
----

Then navigate into the `sudoku2` directory and list its contents (remember how?) and you should find that the directory contains seven files:

[source,bash]
----
Makefile  debug.bin  l33t.bin  n00b.bin  staff.o  sudoku.c  sudoku.h
----

`staff.o` is an object file containing the staff's implementation of the functionality in Sudoku(Part 1). Take care not to delete this file!

=== Option 2: Extend Your Game

Execute

[source,bash]
----
cd ~/workspace/chapter4/sudoku
----

which should have been created in the last problem. Next type

[source,bash]
----
ls
----

and you should see that the directory contains a number of files, among them `sudoku.c`. Be sure that if you compile and run your `sudoku` executable, you can move completely around the board using the arrow keys (including wrapping around), and that you can add and remove numbers from the board.

== The student becomes the teacher

Whether using your own implementation of `sudoku.c` or starting from the staff's solution, the basic implementation of the Sudoku game (being able to move the cursor to all possible locations and enter numbers and/or blanks in any of the board's 81 cells) is complete. Now it's time to augment the game by adding the following additional features:

* Do not allow the user to alter numbers that "came with" the board. (Note that in the first part of the problem, this restriction was not enforced!)
* Any time the user changes the board, check whether the game has been won. If so, display a congratulatory banner, turn all 81 numbers green, and prevent the user from changing the board further.
* Any time the user changes the board, check whether they have inserted a number where it does not belong at the moment (because that same number already exists in the same column, row, or 3x3 box). If so, display a banner warning the user of the problem that disappears the moment the user changes the board again (unless the change introduces a new problem, in which case the user should again be warned).
* Display numbers that "came with" the board in a different color than those that the user has inputted.
* Allow the user to undo the last change made to the board by hitting U or ctrl+Z.

To play with the staff's own implementation of Sudoku, which incorporates all of the features you are expected to have completed, you may execute the below.

[source,bash]
----
~cs50/chapter4/sudoku
----

This was Sudoku(Part 2).
