---
layout: 2016/fall
title: CSCI E-50 Syllabus
---
:skip-front-matter:

= CSCI E-50 Syllabus

Introduction to the intellectual enterprises of computer science and the art of programming. This course teaches students how to think algorithmically and solve problems efficiently. Topics include abstraction, algorithms, data structures, encapsulation, resource management, security, software engineering, and web development. Languages include C, Python, SQL, and JavaScript plus CSS and HTML. Problem sets inspired by real-world domains of biology, cryptography, finance, forensics, and gaming. Designed for concentrators and non-concentrators alike, with or without prior programming experience

CS50 officially meets on Mondays and Wednesdays, from 1pm until 2:30pm in Sanders Theatre. Sections will be arranged at the beginning of the course. Undergraduates, GSAS students, and cross-registered students may take CS50 either Satisfactory/Unsatisfactory (SAT/UNS) or for a letter grade. Under Gen Ed's Current Requirements, CS50 satisfies Empirical and Mathematical Reasoning. Under Gen Ed's Current Requirements with Flexibility, CS50 satisfies Quantitative Reasoning. Under Gen Ed's new requirements, CS50 will satisfy Natural Sciences & SEAS. See https://cs50.harvard.edu/[cs50.harvard.edu] for FAQs.

== Expectations

You are expected to

* submit nine problem sets,
* take one test and one quiz, and
* submit a final project.

== Website

https://cs50.harvard.edu/

== Grades

You may take this course Satisfactory/Unsatisfactory (SAT/UNS) or for a letter grade. Even though first years may not ordinarily enroll in both a Freshman Seminar and another non-letter-graded course in any one term, they may take both CS50 and a Freshman Seminar SAT/UNS.

Whether taking the course SAT/UNS or for a letter grade, you must ordinarily submit all nine problem sets, take one test and one quiz, and submit a final project in order to be eligible for a satisfactory grade unless granted an exception in writing by the course's heads.

Final grades are determined using the following weights:

|===
| Problem Sets | 50%
| Test | 25%
| Quiz | 15%
| Final Project| 10%
|===

Problem sets and the final project are evaluated primarily along axes of scope, correctness, design, and style, with scores ordinarily determined by scope × (3 × correctness + 2 × design + 1 × style). Scores are normalized across teaching fellows at term's end, so mid-semester comparisons among students of scores are not reliable indicators of standing.

Although you must submit all nine problem sets, your lowest score among those problem sets on which you received perfect scores for the axis of scope will be dropped when final grades are determined.

Know that CS50 draws quite the spectrum of students, including "those less comfortable," "those more comfortable," and those somewhere in between. However, what ultimately matters in this course is not so much where you end up relative to your classmates but where you, in Week 11, end up relative to yourself in Week 0.

The course is not graded on a curve. The course does not have pre-determined cutoffs for final grades. Those less comfortable and somewhere in between are not at a disadvantage vis-à-vis those more comfortable. Each student's final grade is individually determined at term's end after input from the teaching fellows. Remarkable effort and upward trending are considered.

== Books

No books are required or recommended for this course. However, you might find the below books of interest. Realize that free, if not superior, resources can be found on the course's website.

_C Programming Absolute Beginner's Guide_, Third Edition +
Greg Perry, Dean Miller +
Pearson Education, 2014 +
ISBN 0-789-75198-4

_Hacker's Delight_, Second Edition +
Henry S. Warren Jr. +
Pearson Education, 2013 +
ISBN 0-321-84268-5

_How Computers Work_, Tenth Edition +
Ron White +
Que Publishing, 2014 +
ISBN 0-7897-4984-X

_Programming in C_, Fourth Edition +
Stephen G. Kochan +
Pearson Education, 2015 +
ISBN 0-321-77641-0

== Lectures

CS50 officially meets on Mondays and Wednesdays, from 1pm until 2:30pm in Sanders Theatre. Most lectures, except those for Week 0 and Week 11, are filmed in Sanders a few days in advance, with videos thereof released on Fridays so that you have access to problem sets' material at the time the problem set is released; you are welcome but not expected to attend those filmings. On Wednesdays, CS50 holds "walkthroughs" in Sanders for students who would like additional guidance on problem sets; you are welcome but not expected to attend those walkthroughs.

A schedule of lectures, subject to change, appears below.

|===
2+| Lecture | Filmed | Released

| Week 0 | Scratch | Wed 8/31, 1pm – 2:30pm | Wed 8/31, 1pm
| Week 1 | C | Fri 8/26, 11am – 2pm | Fri 9/2, noon
| Week 2 | Arrays | Tue 9/6, 12:30pm – 2:30pm  | Fri 9/9, noon
| Week 3 | Algorithms | Mon 9/12, 12:30pm – 3:30pm | Fri 9/16, noon
| Week 4 | Memory | Tue 9/13, 12:30pm – 3:30pm | Fri 9/23, noon
| Week 5 | Data Structures | Mon 9/26, 12pm – 3pm | Fri 9/30, noon
| Week 6 | HTTP | Mon 10/3, 11:30am – 2:30pm | Fri 10/7, noon
| Week 7 | Machine Learning | Thu 10/13, 4pm – 5:15pm | Thu 10/13, 4pm
| Week 8 | Python | Tue 10/18, 12:30pm – 3:30pm | Fri 10/21, noon
| Week 9 | SQL | Thu 10/27, 11:30am – 2:30pm | Fri 10/28, noon
| Week 10 | JavaScript | Wed 11/2, 11:15am – 2:15pm | Fri 11/4, noon
| Week 11 | The End | Mon 11/21, 1pm – 2:30pm | Mon 11/21, 1pm
|===

== Sections

Lectures are supplemented by weekly, 90-minute sections led by the teaching fellows. Different sections are offered for those less comfortable, those more comfortable, and those somewhere in between, enrollment permitting. You will be asked for your sectioning preferences on Problem Set 0, and you will be assigned to a section (and teaching fellow) shortly thereafter.

A schedule of sections appears below. After sectioning is complete, this list will be updated with specific dates within the given weeks.

|===
| Section | Dates

| C | Wed 9/7*
| Arrays | week of Sun 9/11
| Algorithms | week of Sun 9/18
| File I/O | week of Sun 9/25
| Data Structures | week of Sun 10/2
| Review for Test | week of Sun 10/9
| TF's Choice | week of Sun 10/16
| Python | week of Sun 10/23
| SQL | week of Sun 10/30
| JavaScript | week of Sun 11/6
| Review for Quiz | week of Sun 11/13
|===

pass:[*] Course-wide and filmed.

== Office Hours

Office hours are opportunities for help with problem sets alongside the course's teaching fellows and course assistants.

Office hours begin on Wed 9/7. A schedule of office hours will appear on the course's website.

== Walkthroughs

Integrated into problem sets are "walkthroughs," videos that offer direction on where to begin and how to approach problems. At 1pm on most Wednesdays in Sanders Theatre, the course also offers walkthroughs for students who would like additional guidance on problem sets; you are welcome but not expected to attend.

== Postmortems

Available after problem sets' deadlines are "postmortems," videos via which the course's staff explore actual solutions to problem sets. You are encouraged to watch postmortems for insights into how else you could have (or should have!) implemented your own solutions.

== Tutoring

For students who avail themselves of the course's other resources but still find themselves struggling, the course offers tutoring, to the extent possible, providing opportunities for students to work with the course's staff one-on-one or in particularly small groups. To arrange, contact the course's heads.

== Problem Sets

Nine problem sets are assigned during the semester. Each is due by noon on a Monday. Late work is not ordinarily accepted, except in cases of emergency. Although you must submit all nine problem sets, your lowest score among those problem sets on which you received a perfect score for the axis of scope will be dropped when final grades are determined.

A schedule of problem sets, subject to change, appears below.

|===
| Problem Set | Language | Released | Due

| Problem Set 0 | Scratch | Wed 8/31 | Mon 9/5, noon
| Problem Set 1 | C | Fri 9/2 | Mon 9/12, noon
| Problem Set 2 | C | Fri 9/9 | Mon 9/19, noon
| Problem Set 3 | C | Fri 9/16 | Mon 9/26, noon
| Problem Set 4 | C | Fri 9/23 | Mon 10/3, noon
| Problem Set 5 | C | Fri 9/30 | Mon 10/10, noon
| Problem Set 6 | Python | Fri 10/21 | Mon 10/31, noon
| Problem Set 7 | Python, SQL | Fri 10/28 | Mon 11/7, noon
| Problem Set 8 | JavaScript | Fri 11/4 | Mon 11/14, noon
|===

== Test
 
|===
| Released        | Due

| Fri 10/14, noon | Mon 10/17, noon
|===
 
Due by noon on Mon 10/17 is a take-home test that will cover Weeks 0 through 5 (and Problem Sets 0 through 5). The test is open-book: you may use any and all non-human resources during the test, but the only humans to whom you may turn for help or from whom you may receive help are the course's heads.
 
== Quiz
 
|===
| Released       | Due

| Wed 11/16, 6pm | Fri 11/18, 6pm
|===
 
Due by 6pm on Fri 11/18 is a take-home quiz that will cover Weeks 0 through 10 (and Problem Sets 0 through 8), with emphasis on Week 6 (and Problem Set 6) onward. The quiz is open-book: you may use any and all non-human resources during the quiz, but the only humans to whom  you may turn for help or from whom you may receive help are the course's heads.

== Final Project

The climax of this course is its final project. The final project is your opportunity to take your newfound savvy with programming out for a spin and develop your very own piece of software. So long as your project draws upon this course's lessons, the nature of your project is entirely up to you, albeit subject to the staff's approval. You may implement your project in any language(s) as long as the staff approves. You are welcome to utilize any infrastructure, provided the staff ultimately has access to any hardware and software that your project requires. All that we ask is that you build something of interest to you, that you solve an actual problem, that you impact campus, or that you change the world. Strive to create something that outlives this course.

Inasmuch as software development is rarely a one-person effort, you are allowed an opportunity to collaborate with one or two classmates for this final project. Needless to say, it is expected that every student in any such group contribute equally to the design and implementation of that group's project. Moreover, it is expected that the scope of a two- or three-person group's project be, respectively, twice or thrice that of a typical one-person project. A one-person project, mind you, should entail more time and effort than is required by each of the course's problem sets. Although no more than three students may design and implement a given project, you are welcome to solicit advice from others, so long as you respect the course's policy on academic honesty.

Extensions on the final project are not ordinarily granted, except in cases of emergency. Lateness of submissions is determined down to the minute by submissions' timestamps. Submitting more than seven minutes late is equivalent to not submitting at all.

|===
| Milestone | Date

| Pre-Proposal | Fri 10/28, noon
| Proposal | Fri 11/11, noon
| Status Report | Mon 11/28, noon
| CS50 Hackathon | Thu 12/1, 7pm – Fri 12/2, 7am
| Implementation | Thu 12/8, noon
| CS50 Fair | Fri 12/9, 11am – 4:30pm
|===

== CS50 Hackathon

From 7pm on Thu 12/1 until 7am on Fri 12/2 is the CS50 Hackathon, an epic all-nighter during which you can dive into your final project's implementation alongside classmates (from Harvard and Yale alike!) and staff. If you choose to partake, you'll be asked to propose three milestones for yourself that evening: a "good" one that you intend to achieve no matter what; a "better" one that you think you can achieve; and a "best" one that you hope to achieve.

Dinner will be served around 9pm, second dinner will be served around 1am, and those still standing around 5am will be treated to breakfast at IHOP.

== CS50 Fair

From 11am until 4:30pm on Fri 12/9 is the CS50 Fair, an epic display of final projects. Not only is the CS50 Fair a venue at which to see classmates' projects and demo your own, it is an opportunity to mingle with students, faculty, and staff from across campus as well as recruiters from industry. Attendance is strongly encouraged for all students.

Also in attendance are popcorn, candy, and a raffle with (fabulous) prizes. Family and friends are welcome to join.

include::../honesty.adoc[]

include::../acknowledgement.adoc[]
