---
---
:skip-front-matter:

= Problem: Mashup (Part 2)

== Prerequisites

* Javascript
* AJAX
* Mashup (Part 1)

== Objectives

* Introduction to JavaScript, Ajax, JSON.
* Exposure to objects and methods.
* Grapple with real-world APIs and libraries.

== Recommended Reading

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide

== Recommended Viewing

If you feel you need to, take another peek at Doug's video on Javascript!

video::JYIKYnbdu4E[youtube,height=540,width=960]

include::../../../fall/honesty.adoc[]

== Assessment

Your work on this problem set will be evaluated along four axes primarily.

Scope::
  To what extent does your code implement the features required by our specification?
Correctness::
  To what extent is your code consistent with our specifications and free of bugs?
Design::
  To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?
Style::
  To what extent is your code readable (i.e., commented and indented with variables aptly named)?

All students, whether or not taking the course for a letter grade, must ordinarily submit this and all other problem sets to be eligible for a satisfactory grade unless granted an exception in writing by the course's heads.

== No News is Not Good News

In Mashup (Part 1), you implemented the first half of the website seen at 

https://mashup.cs50.net/

Last time, you peeked at the documentation of a few tools that would help you implement such a site. Allow us to add a few more to that list.

=== Google News

If you happen to have a Google Account (e.g., Gmail), head to https://news.google.com/ and click the *Personalize* button at top-right. Below the icon should appear *Personalize Google News*, down below which is *Advanced*. Click the latter, and *Add a local section* should appear at right. Input, say, *Cambridge, Massachusetts* or *New Haven, Connecticut* into that box, then click *Add*. You should find yourself at either of the URLs below?

* https://news.google.com/news/section?cf=all&pz=1&geo=Cambridge,+Massachusetts&ned=us&redirect=true
* https://news.google.com/news/section?cf=all&pz=1&geo=New+Haven,+Connecticut&ned=us&redirect=true

Not to worry if you don't have a Google Account. Just head straight to either URL.

Interesting, it looks like our input is now the value of an HTTP parameter, `geo`, though there's a bunch of other parameters too. (Know that `+` is one way a browser can encode a space in a URL. Another way is with `%20`.) One at a time, delete each of those other key-value pairs plus an ampersand (e.g., first `cf=all&`, then `pz=1&`, then `&ned=us`, then `&redirect=true`, hitting Enter after each deletion so as to reload the page via a shorter and shorter URL. You should find that
Google still returns news for Cambridge or New Haven even when the URL is either of the below?

* https://news.google.com/news/section?geo=Cambridge,+Massachusetts
* https://news.google.com/news/section?geo=New+Haven,+Connecticut

Nice! +1 for trial and error. Now try changing the value of `geo` to, say, `02138` or `06511` and then hit Enter again. You should find yourself at the URL below? The articles might change (since Cambridge and New Haven have more than one postal code each), but the news should still be about Cambridge or New Haven?

* https://news.google.com/news/section?geo=02138
* https://news.google.com/news/section?geo=06511

Nice. Though the page you're looking at, of course, is written in HTML. And all we want, if the staff's solution is any indication, is a bulleted list of articles' titles and links. How to get those without "scraping" this page's (surely complicated) HTML? Scroll down to the page's bottom and look for *RSS*. Click that link, and you should find yourself at one of the URLs below?

* https://news.google.com/news?cf=all&hl=en&pz=1&ned=us&geo=02138&output=rss
* https://news.google.com/news?cf=all&hl=en&pz=1&ned=us&geo=06511&output=rss

As before, delete any parameters that don't feel core to the mission at hand, leaving only, say, `geo` and, now, `output`. You should find yourself at one of the (still fully functional) URLs below.

* https://news.google.com/news/feeds?geo=02138&output=rss
* https://news.google.com/news/feeds?geo=06511&output=rss

Deleting those parameters probably isn't necessary (and, who knows, their absence might break things eventually), but whittling a URL down to its essence does feel like better design, so let's stick with simple.

Now, what's all this markup that's now on your screen? It looks a bit like HTML, but you're actually looking at an "RSS feed," a flavor of XML (a tag-based markup language). For quite some time, RSS was all the rage insofar as it enabled websites to "syndicate" articles in a standard format that "RSS readers" could read. RSS isn't quite as hip anymore these days, but it's still a terrific find for us because it's "machine-readable". Because it adheres to a standard format, we can parse it (pretty easily!) with software. Here's what an RSS feed generally looks like (sans actual data):

[source,xml]
----
<rss version="2.0">
    <channel>
        <title>...</title>
        <description>...</description>
        <link>...</link>
        <item>
            <guid>...</guid>
            <title>...</title>
            <link>...</link>
            <description>...</description>
            <category>...</category>
            <pubDate>...</pubDate>
        </item>
        ...
    </channel>
</rss>
----

In other words, an RSS feed contains a root element called `rss`, the child of which is an element called `channel`.  Inside of `channel` are elements called `title`, `description`, and `link`, followed by one or more elements called `item`, each of which represents an article (or blog post or the like). Each `item`, meanwhile, contains elements called `guid`, `title`, `link`, `description`, `category`, and `pubDate`. Of course, between most of these start tags and end tags should be actual data (e.g., an article's actual title). For more details, see http://cyber.law.harvard.edu/rss/rss.html.

Ultimately, we'll parse RSS feeds from Google News using PHP and then return articles' titles and links to our web app via Ajax as JSON. But more on that in a bit.

=== jQuery

Recall that http://jquery.com/[jQuery] is a super-popular JavaScript library that "makes things like HTML document traversal and manipulation, event handling, animation, and Ajax much simpler with an easy-to-use API that works across a multitude of browsers." To be fair, though, it's not without a learning curve. Read through a few sections of jQuery's documentation.

* http://learn.jquery.com/using-jquery-core/document-ready/[$( document ).ready()]
* http://learn.jquery.com/using-jquery-core/selecting-elements/[Selecting Elements]
* http://learn.jquery.com/ajax/jquery-ajax-methods/[jQuery's Ajax-Related Methods]

jQuery's documentation isn't the most user-friendly, though, so odds are you'll ultimately find https://www.google.com/[Google] and http://stackoverflow.com/[Stack Overflow] handier resources.

Recall that `$` is usually (though not always) an alias for a global object that's otherwise called `jQuery`.

== Set It Up?

As with previous problems, you have two choices here:

. Continue editing your site from the previous problem in which you can skip this setup section
. Download the a new set of code that satisfies Part 1 and work from there. To take this option, simply follow the instructions in this section!

Log into https://cs50.io/[CS50 IDE] and, open a terminal window, and execute `update50` to ensure that your workspace is up-to-date!

Then, within CS50 IDE, download this problem set's distribution code from 

[source,bash]
----
wget http://cdn.cs50.net/2015/fall/psets/8/8-5/8-5.zip
----

Unzip it into `~/workspace`, so that you ultimately have a `8-5` directory in `~/workspace`. Then delete `8-5.zip`. And then download http://cdn.cs50.net/2015/fall/psets/8/8-5/8-5.sql into `~/workspace` as well.

(Remember how?)

Next, execute `ls` within `~/workspace/8-5`, and you should see three subdirectories: `bin`, `includes`, and `public`. Ensure that permissions are as follows:

* `700`
** `bin`
** `bin/import`
** `includes`
** `vendor`
* `711`
** `public`
** `public/css`
** `public/fonts`
** `public/img`
** `public/js`
* `600`
** `includes/*.php`
** `public/*.php`
* `644`
** `public/css/*`
** `public/fonts/*`
** `public/img/*`
** `public/index.html`
** `public/js/*`

(Remember how? Remember why?)

Next, ensure that Apache isn't already running (with some other root) by executing the below.

[source,bash]
----
apache50 stop
----

Then (re)start Apache with the below so that it uses `~/workspace/8-5/public` as its root.

[source,bash]
----
apache50 start ~/workspace/8-5/public
----

Next, ensure MySQL is running by executing the below.

[source,bash]
----
mysql50 start
----

Alright, time for a test! In another tab, visit `pass:[https://ide50-username.cs50.io/]`, where `username` is your own username.

You should find yourself at a map (without much of anything going on)! (If you instead see Forbidden, odds are you missed a step earlier; best to try all those chmod steps again.) Feel free to click on the map and drag it around. Or try searching for your home town via the text box up top. It won't find it yet! Indeed, the mashup itself doesn't do much just yet!

Next, head to `pass:[https://ide50-username.cs50.io/phpmyadmin]`, where `username` is again your own username, to access phpMyAdmin. Log in if prompted. (Recall that you can the ⓘ icon toward CS50 IDE's top-right corner to see your *MySQL Username* and your *MySQL Password*.) You should then find yourself at phpMyAdmin's main page.  

Within CS50 IDE, now, open up `8-5.sql`, which you downloaded earlier. You should see a whole bunch of SQL statements.  Highlight them all, select *Edit > Copy* (or hit control-c), then return to phpMyAdmin.  Click phpMyAdmin's *SQL* tab, and paste everything you copied into that page's big text box (which is below *Run SQL query/queries on server "127.0.0.1"*).  Skim what you just pasted to get a sense of the commands you're about to execute, then click *Go*.  You should then see a greenish banner indicating success (i.e., *1 row affected*).  In phpMyAdmin's top-left corner, you should now see link to a database called *8-5*, beneath which is a link to a table called *places*. (If you don't, try reloading the page.) If you click *places*, you'll find (gasp!) that this table is empty. But we have defined its "schema" (i.e., structure) for you. Click phpMyAdmin's *Structure* tab to see. 

Let's now download the data that we'll ultimately import into this table. In a separate tab, head to http://download.geonames.org/export/zip/, where you'll see a whole bunch of ZIP files, "data dumps" (in `.txt` format) from the http://www.geonames.org/[GeoNames] geographical database, which "covers all countries and contains over eight million placenames that are available for download free of charge." Control- or right-click `US.zip` and select *Copy Link Address* (or your browser's equivalent), and then download that ZIP into `~/workspace` within CS50 IDE, as by typing `wget` into a terminal and then pasting the address you just copied. Alternatively, you're welcome to download another country's data, though this spec will assume the US for the sake of discussion. See http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements if unsure how to interpret the ZIP files' 2-letter "base names." (They're "ISO 3166-1 alpha-2" country codes.)

Next, unzip `US.zip`, which should yield `US.txt`. (Remember how?) And then delete `US.zip`.

Per http://download.geonames.org/export/zip/readme.txt, `US.txt` is quite like a CSV file except that fields are delimited with `\t` (a tab character) instead of a comma. To see the file's contents, you're welcome to open it within CS50 IDE, but take care not to change it.

== Mapping It Out - Again!

Let's take a peek at the code that's new since Part 1!

=== scripts.js

Navigate next to `~/workspace/8-5/public/js` and open up `scripts.js`. Ah, the most interesting file yet! It's this file that implements the mashup's "front-end" UI, relying on Google Maps and some "back-end" PHP scripts for data (that we'll soon explore). Let's walk through this one.

Atop the file are some global variables:

* `map`, which will contain a reference (i.e., a pointer of sorts) to the map we'll soon be instantiating;
* `markers`, an array that will contain references to any markers we add atop the map; and
* `info`, a reference to an "info window" in which we'll ultimately display links to articles.

Below those global variables is an anonymous function that will be called automatically by jQuery when the mashup's DOM is fully loaded (i.e., when `index.html` and all its assets, CSS and JavaScript especially, have been loaded into memory).

Atop this anonymous function is a definition of `styles`, an array of two objects that we'll use to configure our map, as per https://developers.google.com/maps/documentation/javascript/styling. Recall that `[` and `]` denote an array, while `{` and `}` denote an object. The (very pretty) indentation you see is just a stylistic convention to which it's probably ideal to adhere in your code as well.

Below `styles` is `options`, another collection of keys and values that will ultimately be used to configure the map further, as per https://developers.google.com/maps/documentation/javascript/reference#MapOptions.

Next we define `canvas`, by using a bit of jQuery to get the DOM node whose unique `id` is `map-canvas`. Whereas `$("#map-canvas")` returns a jQuery object (that has a whole bunch of functionality built-in), `$("#map-canvas").get(0)` returns the actual, underlying DOM node that jQuery is just wrapping.

Perhaps the most powerful line yet is the next one in which we assign `map` (that global variable) a value. With 

[source,js]
----
new google.maps.Map(canvas, options);
----

we're telling the browser to instantiate a new map, injecting it into the DOM node specified by `canvas`), configured per `options`.

The line below that one, meanwhile, tells the browser to call `configure` (another function we've written) as soon as the map is loaded.

==== addMarker

Uh oh, a `TODO`. Ultimately, given a `place` (i.e., postal code and more), this function will need to add a marker (i.e., icon) to the map.

==== configure

This function, meanwhile, picks up where that anonymous function left off. Recall that `configure` is called as soon as the map has been loaded. Within this function we configure a number of "listeners," specifying what should happen when we "hear" certain events. For instance,

[source,js]
----
google.maps.event.addListener(map, "dragend", function() {
    update();
});
----

indicates that we want to listen for a `dragend` event on the map, calling the anonymous function provided when we hear it. That anonymous function, meanwhile, simply calls `update` (another function we'll soon see). Per https://developers.google.com/maps/documentation/javascript/reference#Map, `dragend` is "fired" (i.e., broadcasted) "when the user stops dragging the map." 

Similarly do we listen for `zoom_changed`, which is fired "when the map zoom property changes" (i.e., the user zooms in or out).

On the other hand, upon hearing `dragstart`, we ultimately call `removeMarkers` so that all markers disappear temporarily as a user drags the map, thereby avoiding the appearance of a flicker that might otherwise happen as markers are removed and then re-added after the maps bounds (i.e., corners) have changed.

Below those listeners is our configuration of that typeahead plugin. Take another look at https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md if unsure what `autoselect`, `highlight`, and `minLength` do here. Most importantly, though, know that the value of `source` (i.e., `search`) is the function that the plugin will call as soon as the user starts typing so that the function can respond with an array of search results based on the user's input. For instance, if the user types `foo` into that text box, the function should ultimately return an array of all places in your database that somehow match `foo`. How to perform those matches will ultimately be left to you! The value of `templates`, meanwhile, is an object with two keys: `empty`, whose value is the HTML that should be displayed when `search` comes back empty (i.e., returns an array of length 0), and `suggestion`, whose value is a "template" that will be used to format each entry in the plugin's dropdown menu. Right now, that template is simply `<p>TODO</p>`, which means that every entry in that dropdown will literally say `TODO`. Ultimately, you'll want to change that tvalue to something like

[source,js]
----
<p><%- place_name %>, <%- admin_name1 %></p>
----

so that the plugin dynamically inserts those values (`place_name` and `admin_name1`) or some others for you. In contrast to `<%=`, which Underscore also supports, the `<%-` ensures that the value will be escaped, a la PHP's `htmlspecialchars`, per http://underscorejs.org/#template.

Next notice these lines, which are admittedly a bit cryptic at first glance:

[source,js]
----
$("#q").on("typeahead:selected", function(eventObject, suggestion, name) {
    map.setCenter({lat: parseFloat(suggestion.latitude), lng: parseFloat(suggestion.longitude)});
    update();
});
----

These lines are saying that if the HTML element whose unique `id` is `q` fires an event called `typeahead:selected`, as will happen when the user selects an entry from the plugin's dropdown menu, we want jQuery to call an anonymous function whose second argument, `suggestion`, will be an object that represents the entry selected. Within that object must be at least two properties: `latitude` and `longitude`. We'll then call `setCenter` in order to re-center the map at those coordinates, after which we'll call `update` to update any markers. 

Below those lines, meanwhile, are these:

[source,js]
----
$("#q").focus(function(eventData) {
    hideInfo();
});
----

If you consult http://api.jquery.com/focus/, hopefully those lines will make sense?

Below those are these:

[source,js]
----
document.addEventListener("contextmenu", function(event) {
    event.returnValue = true;
    event.stopPropagation && event.stopPropagation();
    event.cancelBubble && event.cancelBubble();
}, true);
----

Unfortunately, Google Maps disables ctrl- and right-clicks on maps, which interferes with using Chrome's (amazingly useful) *Inspect Element* feature, so these lines re-enable those.

Last up in `configure` is a call to `update` (which we'll soon look at) and a call to `focus`, this time with no arguments. See http://api.jquery.com/focus/ for why!

==== hideInfo

Thankfully, a short function! This one just calls `close` on our global info window.

==== removeMarkers

Hm, a `TODO`. Ultimately, this function will need to remove any and all markers from the map!

==== search

This function is called by the typeahead plugin every time the user changes the mashup's text box, as by typing or deleting a character. The value of the text box (i.e., whatever the user has typed in total) is passed to `search` as `query`. And the plugin also passes to `search` a second argument, `cb`, a "callback" which is a function that `search` should call as soon as it's done searching for matches. In other words, this passing in of `cb` empowers `search` to be "asynchronous," whereby it will only call `cb` as soon as it's ready, without blocking any of the mashup's other functionality. Accordingly, `search` uses jQuery's `getJSON` method to contact `search.php` asynchronously, passing in one parameter, `geo`, the value of which is `query`. Once `search.php` responds (however many milliseconds or seconds later), the anonymous function passed to `done` will be called and passed `data`, whose value will be whatever JSON that `search.php` has emitted. (Though if something goes wrong, `fail` is instead called.) Finally called is `cb`, to which `search` passes that same `data` so that the plugin can iterate over the places therein (assuming `search.php` found matches) in order to update the plugin's drop-down. Phew.

Notice that we're using ``getJSON``'s "Promise" interface, per http://api.jquery.com/jquery.getjson/. Rather than pass an anonymous function directly to `getJSON` (to be called upon success), we're instead "chaining" together calls to `getJSON`, `done` (whose argument, an anonymous function, will be called upon success), and `fail` (whose argument, another anonymous function, will be called upoon failure). See http://api.jquery.com/jquery.ajax/ for some additional details. And see http://davidwalsh.name/write-javascript-promises for an explanation of promises themselves.

Notice, too, that we're using `console.log` much like you might use `printf` in C to log errors for debugging's sake. You may want to do so as well! Just realize that `console.log` will log messages to the browser's console (i.e., the *Console* tab of Chrome's developer tools), not to your terminal window. See https://developer.mozilla.org/en-US/docs/Web/API/Console.log for tips.

==== showInfo

This function opens the info window at a particular marker with particular content (i.e., HTML). Though if only one argument is supplied (`marker`), `showInfo` simply displays a spinning icon (which is just an animated GIF). Notice, though, how this function is creating a string of HTML dynamically, thereafter passing it to `setContent`. Perhaps keep that technique in mind elsewhere!

==== update

Last up is `update`, which first determines the map's current bounds, the coordinates of its top-right (northeast) and bottom-left (southwest) corners. It then passes those coordinates to `update.php` via a GET request (underneath the hood of `getJSON`) a la:

[source]
----
GET /update.php?ne=37.45215513235332%2C-122.03830380859375&q=&sw=37.39503397352173%2C-122.28549619140625 HTTP/1.1
----

The `%2C` are just commas that have been "URL-encoded." Realize that our use of commas is arbitary; we're expecting `update.php` to parse and extract latitudes and longitudes from these parameters. We could have simply passed in four distinct parameters, but we felt it was semantically cleaner to pass in just one parameter per corner.

As we'll soon see, `update.php` is designed to return a JSON array of places that fall within the map's current bounds (i.e., cities within view). After all, with those two corners alone can you define a rectangle, which is exactly what the map is!

As soon as `update.php` responds, the anonymous function passed to `done` is called and passed `data`, the value of which is the JSON emitted by `update.php`. (Though if something goes wrong, `fail` is instead called.) That anonymous function first removes all markers from the map and then iteratively adds new markers, one for each place (i.e., city) in the JSON.

Phew and phew!

=== update.php

Now navigate your way to `~/workspace/8-5/public` and open up `update.php`. Ah, okay, here's the "back-end" script that outputs a JSON array of up to 10 places (i.e., cities) that fall within the specified bounds (i.e., within the rectangle defined by those corners). You won't need to make changes to this file, but do read through it line by line, Googling any function with which you're not familiar. Of particular interest should be `preg_match`, which allows you to compare strings against "regular expressions." While cryptic at first glance, our two calls to `preg_match` in `update.php` are simply ensuring that both `sw` and `ne` are comma-separated latitudes and longitudes.

Oh, and yes, this file's SQL queries assume that the world is flat for simplity.

=== search.php

Next open up `search.php`. Ah, not much in there now. Just an eventual `TODO`!

=== articles.php

Now open up `articles.php`. This one we've implemented for you. Notice how it expects a GET parameter called `geo`, which it passes to `lookup` (which is defined in `helpers.php`) for localized news, thereafter returning a JSON array of objects, each of which has two keys: `link` and `title`. 

You can actually see this file in action. Go ahead and visit URLs like

* https://ide50-username.cs50.io/articles.php?geo=Cambridge,+Massachusetts
* https://ide50-username.cs50.io/articles.php?geo=02138

or

* https://ide50-username.cs50.io/articles.php?geo=New+Haven,+Connecticut
* https://ide50-username.cs50.io/articles.php?geo=06511

where `username` is your own username. You should see (pretty-printed) JSON arrays of articles!

=== config.php

Let's now take a quick peek at the file that all those other PHP files have required. Navigate your way to `~/workspace/8-5/includes` and open up `config.php`. Ah, a file quite like Problem Set 7's own `config.php`, albeit simpler. It even loads CS50's PHP library, along with `helpers.php`.

=== helpers.php

In this file we've defined just one function, `lookup`. Unlike Problem Set 7's `lookup`, though, this version of `lookup` queries Google News for articles for a particular geography. No need to understand every one this file's lines, but do review its comments!

=== config.json

Next open up `config.json`. Ah, another familiar sight, albeit with for database called `8-5`.

== x MARKS the spot

Alright, it's time to mash Google's two APIs together. Luckily, you've already done half the work!

=== scripts.js

First, toward the top of `scripts.js`, you'll see an anonymous function, inside of which is a definition of `options`, an object, one of whose keys is `center`, the value of which is an object with two keys of its own, `lat`, and `lng`. Per the comment alongside that object, your mashup's map is currently centered on Stanford, California. (D'oh.) Change the coordinates of your map's center to Cambridge (42.3770, -71.1256) or New Haven (41.3184, -72.9318) or anywhere else! (Though be sure to choose coordinates in the US if you downloaded `US.txt`!) Once you save your changes and reload your map, you should find yourself there! Zoom out as needed to confirm visually.

As before, feel free to tinker with the staff's solution at https://mashup.cs50.net/, inspecting its HTTP requests via Chrome's Network tab as needed, if unsure how your own code should work!

==== configure

Now that `search.php` and your text box are (hopefully!) working, modify the value of `suggestion` in `configure`, the function in `scripts.js`, so that it displays matches (i.e., `place_name`, `admin_name1`, and/or other fields) instead of `TODO`. Recall that a value like

[source,js]
----
<p><%- place_name %>, <%- admin_name1 %></p>
----

might do the trick, perhaps coupled with some CSS.

==== addMarker

Implement `addMarker` in `scripts.js` in such a way that it adds a marker for `place` on the map, where `place` is a JavaScript object that represents a row from `places`, your MySQL table. See https://developers.google.com/maps/documentation/javascript/markers for tips. But also see http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerwithlabel/1.1.9/ for an alternative to Google's own markers, which add support for labels beneath markers. (Recall that we're already loading `markerwithlabel_packed.js` for you in `index.html`.)

When a marker is clicked, it should trigger the mashup's info window to open, anchored at that same marker, the contents of which should be an unordered list of links to article for that article's location (unless `articles.php` outputs an empty array)!

Again, not to worry if some of your markers (or labels) overlap others, assuming such is the result of imperfections in `US.txt` and not your own code!

If you'd like to customize your markers' icon, see https://developers.google.com/maps/documentation/javascript/markers#simple_icons. For the URLs of icons built-into Google Maps, see http://www.lass.it/Web/viewer.aspx?id=4. For third-party icons, see http://mapicons.nicolasmollet.com/category/markers/.

==== removeMarkers

Implement `removeMarkers` in such a way that it removes all markers from the map. Odds are you'll need `addMarker` to modify that global variable called `markers` in order for `removeMarkers` to work its own magic!

==== personal touch

Last but not least, add at least one personal touch to your mashup, altering its aesthetics or adding some feature that (ideally!) no classmate has. Any touch that compels you to learn (or Google!) at least one new technique is of reasonable scope.

== Turn It In

. When ready to submit, "export" your MySQL database (i.e., save it into a text file) by executing the commands below, where `username` is your own username, pasting your MySQL password when prompted for a password.  (Recall that you can see your MySQL password by clicking the ⓘ icon toward CS50 IDE's top-right corner.) For security, you won't see the password as you paste it.
+
[source]
----
cd ~/workspace/8-5
mysqldump -u username -p 8-5 > 8-5.sql
----
+
If you type `ls` thereafter, you should see that you have a new file called `8-5.sql` in `~/workspace/8-5`.  (If you realize later that you need to make a change to your database and re-export it, you can delete `8-5.sql` with `rm 8-5.sql`, then re-export as before.) +
Toward CS50 IDE's top-left corner, within its "file browser" (not within a terminal window), control-click or right-click your `8-5` folder and then select *Download*. You should find that your browser has downloaded `8-5.tar.gz`, a "gzipped tarball" that's similar in spirit to a ZIP file.

Await instructions on how to submit the tarball!
 

This was Mashup (Part 2).