---
layout: 2017/x
---

= FAQs

Here are answers to some frequently asked questions (FAQs). For answers to other questions, do just strike up a https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/[discussion] with classmates!

== Can I use CS50 IDE offline?

Yes, if you have particularly slow, expensive, or infrequent Internet access, see https://cs50.readme.io/v2015/docs/offline for details on how you can run your own copy of CS50 IDE locally on your own computer.

== Does CS50x have a test or quiz?

Nope! CS50 at Harvard University and Yale University does have a test and quiz, but CS50x does not.

== Does CS50x have office hours?

No, afraid CS50x is too large, but you can still start a https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/[discussion] with classmates!

== Does CS50x have sections?

No, afraid CS50x is too large, but you can still start a https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/[discussion] with classmates!

== If I paid for a verified certificate before 2017, do I need to pay again?

No, you should be able to re-verify yourself via edX's https://courses.edx.org/dashboard[dashboard].

== If I started CS50x before 2017, can I resume?

Yes, any scores you received on past years' problem sets will (soon) be imported into CS50x 2017. (We're still updating CS50x 2017's gradebook.) However, moving forward, you must submit CS50x 2017's problem sets, per the https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/dfface6ffc1c43e6882a245c945f7feb/[syllabus].

== Is my child too young to take CS50x?

CS50x is perhaps best suited for ages 12 and up. Younger students might need a hand from a parent.

== When are certificates generated?

At the end of each month, CS50's staff provides edX with a list of students who have satisfied CS50x's requirements (by receiving scores of at least 70% on every one of the course's nine problem sets as well as on the final project). Within a few days, edX then generates students' certificates, at which point they should appear automatically on edX's https://courses.edx.org/dashboard[dashboard].

== When are deadlines?

CS50x does not have deadlines for problem sets or for the final project. You are welcome to work on and submit at your own pace.

== Why does edX think my grade 0%?

CS50x doesn't use edX's built-in gradebook, so all students' scores appear (in edX's gradebook) as 0%. Not to worry, see https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/05722c69041f4754ae097af65aae2083/[CS50x's gradebook] for your actual scores.
