---
layout: 2017/spring
title: CSCI E-50b Syllabus
---
:skip-front-matter:

= CSCI E-50b Syllabus

**version 0.01 - draft**

Introduction to the intellectual enterprises of computer science and the art of programming. This course teaches students how to think algorithmically and solve problems efficiently. Topics include abstraction, algorithms, data structures, encapsulation, resource management, security, software engineering, and web development. Languages include C, Python, and JavaScript plus SQL, CSS, and HTML. Problem sets inspired by real-world domains of biology, cryptography, finance, forensics, and gaming. Designed for concentrators and non-concentrators alike, with or without prior programming experience

*This course represents the second half of CSCI E-50. When taken in conjunction with CSCI E-50a, this course effectively allows students twice as much time to work through CSCI E-50's curriculum.*

== Expectations

You are expected to

* submit one warm-up problem set,
* submit four regular problem sets,
* take one quiz, and
* submit a final project.

== Website

https://cs50.harvard.edu/cscie50b

== Grades

If taking the course for a letter grade, you must ordinarily submit the warm-up and the other four problem sets, take one quiz, and submit a final project in order to be eligible for a satisfactory grade unless granted an exception in writing by the course's heads. The first of the course's problem sets is a "warm-up" exercise to reacquaint you with the course material from the tail end of CSCI E-50a, and is weighted less than the other problem sets.

Final grades are determined using the following weights:

|===
| Warm-Up | 5%
| Problem Sets | 50%
| Quiz | 25%
| Final Project| 20%
|===

Problem sets and the final project are evaluated primarily along axes of scope, correctness, design, and style, with scores ordinarily determined by scope × (3 × correctness + 2 × design + 1 × style). Scores are normalized across TFs at term's end, so mid-semester comparisons among students of scores are not reliable indicators of standing.

Know that the course draws quite the spectrum of students, including "those less comfortable," "those more comfortable," and those somewhere in between. However, what ultimately matters in this course is not so much where you end up relative to your classmates but where you, at course's end, end up relative to yourself at the course's start.

The course is not graded on a curve. The course does not have pre-determined cutoffs for final grades. Those less comfortable and somewhere in between are not at a disadvantage vis-à-vis those more comfortable. Each student's final grade is individually determined at term's end after input from the teaching fellows. Remarkable effort and upward trending are considered.

== Books

No books are required or recommended for this course. However, you might find the below books of interest. Realize that free, if not superior, resources can be found on the course's website.

_C Programming Absolute Beginner's Guide_, Third Edition +
Greg Perry, Dean Miller +
Pearson Education, 2014 +
ISBN 0-789-75198-4

_Hacker's Delight_, Second Edition +
Henry S. Warren Jr. +
Pearson Education, 2013 +
ISBN 0-321-84268-5

_How Computers Work_, Tenth Edition +
Ron White +
Que Publishing, 2014 +
ISBN 0-7897-4984-X

_Programming in C_, Fourth Edition +
Stephen G. Kochan +
Pearson Education, 2015 +
ISBN 0-321-77641-0

== Lectures

This semester's lectures were filmed in Fall 2016. All are available on video via the course's website. Below are dates on which (or close to which) we recommend that each week's lecture be viewed, to best prepare you for that week's problem set. Do note that the format of the course is different from CSCI E-50a.

|===
2+| Lecture | Watch on

| Week 5 | Data Structures | Fri 1/27, Fri 2/3
| Week 6 | HTTP | Fri 2/10, Fri 2/17
| Week 7 | Machine Learning | Fri 2/24
| Week 8 | Python | Fri 3/3, Fri 3/10
| Week 9 | SQL | Fri 3/17, Fri 3/24
| Week 10 | JavaScript | Fri 3/31, 4/7
| Week 11 | The End | Fri 4/21
|===

== Sections

Lectures are supplemented by one weekly, 60-minute sections led by the teaching fellows. Sections provide you with opportunities to explore the course's material in a more intimate environment, with only your teaching fellow and a handful of classmates present, as well as to dive into hands-on activities.

A sectioning time preference sheet will be distributed during the first week of the course. Sections themselves begin the first week of February.

|===
| Section | Dates

| Data Structures | week of Sun 2/5
| HTTP I | week of Sun 2/12
| HTTP II | week of Sun 2/19
| Machine Learning | week of Sun 2/26
| Python I | week of Sun 3/5
| Python II | week of Sun 3/12
| SQL I | week of Sun 3/19
| SQL II | week of Sun 3/26
| JavaScript I | week of Sun 4/2
| JavaScript II | week of Sun 4/9
| Review for Quiz | week of Sun 4/16*
|===

pass:[*] Pre-recorded material available to supplement section.

== Office Hours

Office hours are online opportunities for assistance on problem sets with the course's teaching fellows and course assistants. A schedule of office hours will appear on the course's website. Office hours will begin the first week of February.

== Walkthroughs

Integrated into problem sets are "walkthroughs," videos via which the course's staff offer direction on where to begin and how to approach a challenge. You are expected to watch walkthroughs before asking questions about problem sets at office hours or via https://cs50.harvard.edu/discuss[CS50 Discuss].

== Postmortems

Available after problem sets' deadlines are "postmortems," videos via which the course's staff explore actual solutions to problem sets. You are expected to watch postmortems for insights into how else you could have (or should have!) implemented your own solutions.

== Problem Sets

Five problem sets are assigned during the semester. Each is due by noon on a Friday.  Lateness of electronic submissions is determined down to the minute by submissions' timestamps. Submitting more than seven minutes late is equivalent to submitting twenty-four hours late. Late work is not ordinarily accepted, except in cases of medical emergency.

A schedule of problem sets, subject to change, appears below.

|===
| Problem Set | Language | Released | Due

| Warm-Up: Sudoku | C | Fri 1/27 | Fri 2/10, noon
| Problem Set 5: Mispellings | C | Fri 2/10 | Fri 3/3, noon
| Problem Set 6: Sentiments | Python | Fri 3/3 | Fri 3/17, noon
| Problem Set 7: C$50 Finance | Python, SQL | Fri 3/17 | Fri 3/31, noon
| Problem Set 8: Mashup | JavaScript | Fri 3/31 | Fri 4/14, noon
|===

== Quiz

|===
| Released       | Due

| Sat 4/15, noon | Mon 4/17, noon
|===

Due by noon on Mon 4/17 is a take-home quiz that will cover both CSCI E-50a and CSCI E-50b, with an emphasis on the material in CSCI E-50b. The quiz is open-book: you may use any and all non-human resources during the quiz, but the only humans to whom  you may turn for help or from whom you may receive help are the course's heads.

== Final Project

The climax of this course is its final project. The final project is your opportunity to take your newfound savvy with programming out for a spin and develop your very own piece of software. So long as your project draws upon this course's lessons, the nature of your project is entirely up to you, albeit subject to the staff's approval. You may implement your project in any language(s) as long as the staff approves. You are welcome to utilize any infrastructure, provided the staff ultimately has access to any hardware and software that your project requires. All that we ask is that you build something of interest to you, that you solve an actual problem, that you impact campus, or that you change the world. Strive to create something that outlives this course.

Inasmuch as software development is rarely a one-person effort, you are allowed an opportunity to collaborate with one or two classmates for this final project. Needless to say, it is expected that every student in any such group contribute equally to the design and implementation of that group's project. Moreover, it is expected that the scope of a two- or three-person group's project be, respectively, twice or thrice that of a typical one-person project. A one-person project, mind you, should entail more time and effort than is required by each of the course's problem sets. Although no more than three students may design and implement a given project, you are welcome to solicit advice from others, so long as you respect the course's policy on academic honesty.

Extensions on the final project are not ordinarily granted, except in cases of emergency. Lateness of submissions is determined down to the minute by submissions' timestamps. Submitting more than seven minutes late is equivalent to not submitting at all.

|===
| Milestone | Date

| Pre-Proposal | Fri 4/7, noon
| Proposal | Fri 4/14, noon
| Status Report | Mon 5/1, noon
| Implementation | Thu 5/11, noon
| CS50 Fair | Fri 5/12, 5:30pm – 7pm
|===

== CS50 Fair

From 5:30pm until 7pm on Fri 5/12 is the CS50 Fair, an epic display of final projects (albeit smaller than the fall term's). The CS50 Fair will be an optional opportunity to mingle with classmates, enjoy demos, and eat cake. Family and friends are welcome to join.

include::../honesty.adoc[]

include::../acknowledgement.adoc[]
