---
layout: default
---
:skip-front-matter:

= Problem: Fifteen (Part 3)

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], the `#cs50ap` channel on https://cs50x.slack.com[CS50x Slack] (after signing up), or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

== Objectives

* Rewrite your software.
* Learn about more-advanced searching techniques.
* Implement a simple AI (artificial intelligence).

== Recommended Reading

* Page 17 of http://www.howstuffworks.com/c.htm.
* Chapters 20 and 23 of _Absolute Beginner's Guide to C_.
* Chapters 13, 15, and 18 of _Programming in C_.

== Prerequisites

* This problem requires that you have completed http://cdn.cs50.net/ap/1516/problems/3/2/3-2.html[Problem 3-2] by relying upon your own solution to http://cdn.cs50.net/ap/1516/problems/3/1/3-1.html[Problem 3-1], and not the staff's partial solution, for reasons that will become clear by reading the specification. 

== Academic Honesty

This course's philosophy on academic honesty is best stated as "be reasonable." The course recognizes that interactions with classmates and others can facilitate mastery of the course's material. However, there remains a line between enlisting the help of another and submitting the work of another. This policy characterizes both sides of that line.

The essence of all work that you submit to this course must be your own. Collaboration on problems is not permitted (unless explicitly stated otherwise) except to the extent that you may ask classmates and others for help so long as that help does not reduce to another doing your work for you. Generally speaking, when asking for help, you may show your code or writing to others, but you may not view theirs, so long as you and they respect this policy's other constraints. Collaboration on quizzes and tests is not permitted at all. Collaboration on the final project is permitted to the extent prescribed by its specification.

Below are rules of thumb that (inexhaustively) characterize acts that the course considers reasonable and not reasonable. If in doubt as to whether some act is reasonable, do not commit it until you solicit and receive approval in writing from your instructor. If a violation of this policy is suspected and confirmed, your instructor reserves the right to impose local sanctions on top of any disciplinary outcome that may include an unsatisfactory or failing grade for work submitted or for the course itself.

=== Reasonable

* Communicating with classmates about problems in English (or some other spoken language).
* Discussing the course's material with others in order to understand it better.
* Helping a classmate identify a bug in his or her code, such as by viewing, compiling, or running his or her code, even on your own computer.
* Incorporating snippets of code that you find online or elsewhere into your own code, provided that those snippets are not themselves solutions to assigned problems and that you cite the snippets' origins.
* Reviewing past years' quizzes, tests, and solutions thereto.
* Sending or showing code that you've written to someone, possibly a classmate, so that he or she might help you identify and fix a bug.
* Sharing snippets of your own solutions to problems online so that others might help you identify and fix a bug or other issue.
* Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problems or your own final project.
* Whiteboarding solutions to problems with others using diagrams or pseudocode but not actual code.
* Working with (and even paying) a tutor to help you with the course, provided the tutor does not do your work for you.

=== Not Reasonable

* Accessing a solution to some problem prior to (re-)submitting your own.
* Asking a classmate to see his or her solution to a problem before (re-)submitting your own.
* Decompiling, deobfuscating, or disassembling the staff's solutions to problems.
* Failing to cite (as with comments) the origins of code, writing, or techniques that you discover outside of the course's own lessons and integrate into your own work, even while respecting this policy's other constraints.
* Giving or showing to a classmate a solution to a problem when it is he or she, and not you, who is struggling to solve it.
* Looking at another individual's work during a quiz or test.
* Paying or offering to pay an individual for work that you may submit as (part of) your own.
* Providing or making available solutions to problems to individuals who might take this course in the future.
* Searching for, soliciting, or viewing a quiz's questions or answers prior to taking the quiz.
* Searching for or soliciting outright solutions to problems online or elsewhere.
* Splitting a problem's workload with another individual and combining your work (unless explicitly authorized by the problem itself).
* Submitting (after possibly modifying) the work of another individual beyond allowed snippets.
* Submitting the same or similar work to this course that you have submitted or will submit to another.
* Using resources during a quiz beyond those explicitly allowed in the quiz's instructions.
* Viewing another's solution to a problem and basing your own solution on it.

== Assessment

Your work on this problem set will be evaluated along four axes primarily.

Scope::
 To what extent does your code implement the features required by our specification?
Correctness::
 To what extent is your code consistent with our specifications and free of bugs?
Design::
 To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?
Style::
 To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== The Game Concludes

Implement God Mode for the Game of Fifteen.

=== init

First tweak `init` in such a way that the board is initialized to a **pseudorandom but solvable configuration**. That is to say, no longer should your game always start like this:


[source]
----
15 14 13 12

11 10  9  8

 7  6  5  4

 3  1  2  _
----

but rather, it might start from any legal placement of tiles, for example this onefootnote:[Trust us, this is a legal and solvable state of the board]:

[source]
----
15 13 12  _

 9 14  2  1

10  4  3  8

11  7  5  6
----

=== And the Rest

Then embed in the game a cheat, whereby, rather than typing an integer betwen 1 and _d_^2^ – 1, where _d_ is the board’s height and width, the human can also type `GOD` to compel "the computer" to take control of the game and solve it (using any strategy, optimal or non-optimal),
making, say, only four moves per second so that the human can actually watch. 

Presumably, you’ll need to swap out `GetInt` in `main` for something more versatile. It’s fine if your implementation of God Mode only works (bearably fast) for _d_ ≤ 4; you need not worry about testing God Mode for _d_ > 4. 

Oh and you can’t implement God Mode by remembering how `init` initialized the board (as by remembering the sequence of moves that got your program to some pseudorandom but solvable state). Nice try.

To test your implementation, you can certainly try playing it yourself, with or without God Mode enabled. (Know that you can quit your program by hitting ctrl-c.) Be sure that you (and we) cannot crash your program, as by providing bogus tile numbers. And know that, much like you automated input into find, so can you automate execution of this game via input redirection if you store in some file a winning sequence of moves for some configuration. 

Any design decisions not explicitly prescribed herein (e.g., how much space you should leave between numbers when printing the board) are intentionally left to you. Feel free to tweak the appropriate argument to usleep to speed up animation. In fact, you’re welcome to alter the aesthetics of the game. For (optional) fun with "ANSI escape sequences," including color, take a look at our implementation of `clear` and `check` out http://isthe.com/chongo/tech/comp/ansi_escapes.html for more tricks.
    
You're welcome to write your own functions and even change the prototypes of functions we wrote. But we ask that you not alter the flow of logic in `main` so that we can automate some tests of your program.

If you’d like to play with the staff’s own implementation of fifteen on CS50 IDE, including God Mode, you may execute the below.

[source,bash]
----
~cs50/chapter3/fifteen-solver
----

=== Some Light Reading

Speaking of God Mode, where to begin?  Well, first read up on this Game of Fifteen.  Wikipedia is probably a good starting point:

http://en.wikipedia.org/wiki/N-puzzle

Then dive a bit deeper, perhaps reading up on an algorithm called A*.

http://en.wikipedia.org/wiki/A*_search_algorithm

Consider using "Manhattan distance" (aka "city-block distance") as your implementation's heuristic. If you find that A* takes up too much memory (particularly for _d_ ≥ 4), though, you might want to take a look at iterative deepening A* (IDA*) instead:

http://webdocs.cs.ualberta.ca/~tony/RecentPapers/pami94.pdf

The staff's own implementation, meanwhile, utilizes an algorithm like that in this paper:

http://larc.unt.edu/ian/pubs/saml.pdf

You're welcome to expand your search for ideas beyond those in these papers, but take care that your research does not lead you to actual code. Curling up with others' pseudocode is fine, but please click away if you stumble upon actual implementations (whether in C or other languages). Remember the academic honesty policy that sits atop this specification!

This was Fifteen (Part 3).
