---
layout: 2018/fall
---

= Bleep

== tl;dr

Implement a program that censors messages that contain words that appear on a list of supplied "banned words."

[source,subs=quotes]
----
$ [underline]#python bleep.py banned.txt#
[underline]#What the heck#
What the &#42;&#42;&#42;&#42;
$ [underline]#python bleep.py banned.txt#
[underline]#gosh darn it#
&#42;&#42;&#42;&#42; &#42;&#42;&#42;&#42; it
----

== Getting Started

Here's how to download this problem's "distribution code" (i.e., starter code) into your own CS50 IDE. Log into link:https://cs50.io/[CS50 IDE] and then, in a terminal window, execute each of the below.

1. Execute `update50` to ensure your IDE is up-to-date. That command might take a few minutes to finish.
1. Execute `cd ~/workspace/pset6` to ensure that you're in `~/workspace/pset6` (i.e., a directory called `workspace` that's in your home directory, aka `~`). If you haven't yet created that directory, create it now (remember how?).
1. Execute `wget http://cdn.cs50.net/2018/fall/psets/6/bleep/bleep.zip` to download a (compressed) ZIP file with this problem's distribution.
1. Execute `unzip bleep.zip` to uncompress that file.
1. Execute `rm bleep.zip` followed by `yes` or `y` to delete that ZIP file.
1. Execute `ls`. You should see a directory called `bleep`, which was inside of that ZIP file.
1. Execute `cd bleep` to change into that directory.
1. Execute `ls`. You should see this problem's distribution, including `bleep.py` and `banned.txt`.

== Understanding

This program defines only one function, `main`, which gets called per the file's last line. Within `main` ... ugh, looks like that's just a big TODO!

== Specification

Complete the implementation of `bleep` in such a way that it

* Opens the text file (e.g., `banned.txt`) provided as a command line argument, reads from that file the list of words stored therein, and stores each into a Python data structure for later access. While a Python `list` will work well for this, you may also find a link:https://docs.python.org/3/tutorial/datastructures.html#sets[`set`] useful here.
* Prompts the user to provide a message.
* Tokenizes that message into its individual component words, using the link:https://docs.python.org/3/library/stdtypes.html#str.split[`split`] method on the provided string, and then iterates over the `list` of "tokens" (words) that is returned by calling `split`, checking to see whether any of the tokens match, case-insensitively, any of the words in the banned words list.
* Prints back the message that the user provided, except if the message contained any banned words, each of its characters is replaced by a `*`.
  * For example, `gosh` should be replaced with four `*` characters, while `fudge` should be replaced with five.
* You should not censor words that merely contain a banned word as a substring. For example, if **bar** is a banned word in the provided, then none of __**bar**ns__ nor __crow**bar**__ nor __wheel**bar**row__ should be censored.
* You explicitly **do not** need to support input strings that contain punctuation marks. You may assume we will only test your input where each word is only separated by whitespace.

== Usage

Your program should behave per the examples below. Assume that the underlined text is what some user has typed.

[source,subs=quotes]
----
$ [underline]#python bleep.py#
Usage: python bleep.py dictionary
----

[source,subs=quotes]
----
$ [underline]#python bleep.py list1.txt list2.txt list3.txt#
Usage: python bleep.py dictionary
----

[source,subs=quotes]
----
$ [underline]#python bleep.py banned.txt#
[underline]#hello world#
hello world
----

[source,subs=quotes]
----
$ [underline]#python bleep.py banned.txt#
[underline]#what the heck#
what the &#42;&#42;&#42;&#42;
----

[source,subs=quotes]
----
$ [underline]#python bleep.py banned.txt#
[underline]#darn it, world#
&#42;&#42;&#42;&#42; it, world
----

== Testing

=== Correctness

[source]
----
check50 cs50/2018/fall/bleep
----

=== Style

[source]
----
style50 bleep
----

== Staff's Solution

[source]
----
~cs50/pset6/bleep
----

== How to Submit

Execute the below, logging in with your GitHub username and password when prompted. For security, you'll see asterisks (`*`) instead of the actual characters in your password.

```
submit50 cs50/2018/fall/bleep
```

== Hints

* Be sure to test with different banned words lists than the one provided by default -- we will!
* When independently researching how to do things on this problem (which is indeed part of the expectation, as you grow in your comfort with programming overall!), be sure your Google searches and the like include "Python 3" in them, and not just "Python", lest you get code examples written in an earlier version of Python!
* Odds are you'll find https://docs.python.org/3/library/stdtypes.html#str.split[`str.split`] of interest.
* Odds are you'll find https://docs.python.org/3/library/stdtypes.html#str.lower[`str.lower`] of interest.
* Odds are you'll find https://docs.python.org/3/library/stdtypes.html#str.strip[`str.strip`] of interest, to chomp off any trailing newlines that may be attached to words on your "banned words" list.
