---
layout: default
---
:skip-front-matter:

= Problem: Vigenère

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

==  Objectives

* Become better acquainted with functions and libraries.
* Take previously written code and modify it.
* Interact with command-line inputs from users.
* Dabble in cryptography.

== Recommended Reading

* Pages 11 – 14 and 39 of http://www.howstuffworks.com/c.htm.
* Chapters 6, 7, 10, 17, 19, 21, 22, 30, and 32 of _Absolute Beginner's Guide to C_.
* Chapters 7, 8, and 10 of _Programming in C_.

include::../../honesty.adoc[]

== Assessment

Your work on this problem set will be evaluated along four axes primarily.

Scope::
 To what extent does your code implement the features required by our specification?
Correctness::
 To what extent is your code consistent with our specifications and free of bugs?
Design::
 To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?
Style::
 To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Starting Shortly

We'd recommend you get started by watching a few short videos; in particular, these three on functions, command-line arguments, and the Vigenère cipher. If you happen to see (and are confused by!) `char *` in these and other shorts, know for now that `char *` simply means `string`. But more on that soon!

video::Pi0Yf-jn7O8[youtube]

video::X8PmYwnbLKM[youtube]

video::9zASwVoshiM[youtube]

Be sure you're reasonably comfortable answering the below questions before moving too far!

* What's a function?
* Why bother writing functions when you can just copy and paste code as needed?
* What makes Vigenère's cipher more secure than Caesar's?
* What does `undeclared identifier` usually indicate if outputted by `make` (or, really, `clang`)?

Log into your CS50 IDE workspace and execute

[source,bash]
----
update50
----

within a terminal window to make sure your workspace is up-to-date. If you somehow closed your terminal window (and can't find it!), make sure that *Console* is checked under the *View* menu, then click the green, circled plus (+) in CS50 IDE's bottom half, then select *New Terminal*. If you need a hand, do just ask via the channels noted at the top of this specification.

Now execute

[source,bash]
----
cd ~/workspace/chapter2
----

to move yourself into (i.e., open) that directory. Make a new directory called `vigenere`, and you're good to go!

== Background

Vigenère's cipher improves upon link:../caesar/caesar.html[Caesar's cipher] by encrypting messages using a sequence of keys (or, put another way, a keyword). In other words, if _p_ is some plaintext and _k_ is a keyword (i.e., an alphbetical string, whereby A represents 0, B represents 1, C represents 2, ..., and Z represents 25), then each letter, _c~i~_, in the ciphertext, _c_, is computed as:

[latexmath]
++++
c_i = (p_i + k_j) \bmod 26
++++

Note this cipher's use of _k~j~_ as opposed to just _k_. And if _k_ is shorter than _p_, then the letters in _k_ must be reused cyclically as many times as it takes to encrypt _p_.

In other words, if Vigenère himself wanted to say HELLO to someone confidentially, using a keyword of, say, ABC, he would encrypt the H with a key of 0 (i.e., A), the E with a key of 1 (i.e., B), and the first L with a key of 2 (i.e., C), at which point he'd be out of letters in the keyword, and so he'd reuse (part of) it to encrypt the second L with a key of 0 (i.e., A) again, and the O with a key of 1 (i.e., B) again. And so he'd write HELLO as HFNLP.

.Encrypting HELLO with a keyword of ABC (reused cyclically as ABCAB) yields HFNLP.
|===
   | *plaintext*    | H | E | L | L | O
.2+.^| *+ key*        | A | B | C | A | B
   | 0 | 1 | 2 | 0 | 1
   | *= ciphertext* | H | F | N | L | P
|===

== Specification

Design and implement a program that encrypts messages using Vigenère's cipher.

* Implement your program in a file called `vigenere.c` in a directory called `vigenere`.
* Your program must accept a single command-line argument: a keyword, _k_, composed entirely of alphabetical characters.
* If your program is executed without any command-line arguments, with more than one command-line argument, or with one command-line argument that contains any non-alphabetical character, your program should print an error (of your choice) and exit immediately, with `main` returning `1` (thereby signifying an error).
* Otherwise, your program must proceed to prompt the user for a string of plaintext, _p_, (as by a prompt for `plaintext:`) which it must then encrypt according to Vigenère's cipher with _k_, ultimately printing the result (prepended with `ciphertext:` and ending with a newline) and exiting, with `main` returning `0`.
* With respect to the characters in _k_, you must treat `A` and `a` as 0, `B` and `b` as 1, ... , and `Z` and `z` as 25.
* Your program must only apply Vigenère's cipher to a character in _p_ if that character is a letter. All other characters (numbers, symbols, spaces, punctuation marks, etc.) must be outputted unchanged. Moreover, if your code is about to apply the _j^th^_ character of _k_ to the _i^th^_ character of _p_, but the latter proves to be a non-alphabetical character, you must wait to apply that _j^th^_ character of _k_ to the next alphabetical character in _p_; you must not yet advance to the next character in _k_.
* Your program must preserve the case of each letter in _p_.

== Walkthrough

video::iE6jiKRfrEQ[youtube]

== Usage

Your program should behave per the examples below. Assumed that the underlined text is what some user has typed.

[source,subs=quotes]
----
$ [underline]#./vigenere 13#
Usage: ./vigenere k
----

[source,subs=quotes]
----
$ [underline]#./vigenere#
Usage: ./vigenere k
----

[source,subs=quotes]
----
$ [underline]#./vigenere bacon and eggs#
Usage: ./vigenere k
----

[source,subs=quotes]
----
$ [underline]#./vigenere bacon#
plaintext: [underline]#Meet me at the park at eleven am#
ciphertext: Negh zf av huf pcfx bt gzrwep oz
----

== Testing

To help you test `vigenere`, we've written a program called `devigenere` for you that also takes one and only one command-line argument (a keyword) but whose job is to take ciphertext as input and produce plaintext as output. To use our program, execute

[source]
----
~cs50/chapter2/devigenere k
----

at your prompt, where `k` is some keyword. Presumably you'll want to paste your program's output as input to our program; be sure, of course, to use the same key. Note that you do not need to implement `devigenere` yourself, only `vigenere`.

=== `check50`

[source]
----
check50 1718.chapter2.vigenere vigenere.c
----

== Staff Solution

[source]
----
~cs50/chapter2/vigenere
----

== Hints

Not sure where to begin? As luck would have it, this program's pretty similar to link:../caesar/caesar.html[`caesar`]! Only this time, you need to decide which character in _k_ to use as you iterate from character to character in _p_.
