---
layout: 2018/fall
---

= Homepage

== tl;dr

Build a simple homepage using HTML and CSS.

== Background

The internet has empowered us to do incredible things; we can use a search engine to research anything we can imagine, communicate with friends and family members around the globe, play games, take courses, and so much more. But it turns out that nearly all sites we may visit are built on three core languages, each of which serves a slightly different purpose:

  * HTML, or _HyperText Markup Language_, which is used to describe the content of websites;
  * CSS, _Cascading Style Sheets_, which is used to describe the aesthetics of websites; and
  * JavaScript, which is used to make websites interactive and dynamic.

Focusing on just the first of those two languages for now, let's create a simple homepage that introduces yourself, your favorite hobby or extracurricular, or anything else that interests you.

== Getting Started

Here's how to download this problem's "distribution code" (i.e., starter code) into your own CS50 IDE. Log into link:https://cs50.io/[CS50 IDE] and then, in a terminal window, execute each of the below.

1. Execute `update50` to ensure your IDE is up-to-date. That command might take a few minutes to finish.
1. Execute `cd` to ensure that you're in `~/workspace/` (i.e., a directory called `workspace` that's in your home directory, aka `~`).
1. Execute `mkdir pset5` to make (i.e., create) a directory called `pset5` in your home directory.
1. Execute `cd pset5` to change into (i.e., open) that directory.
1. Execute `wget http://cdn.cs50.net/2018/fall/psets/5/homepage/homepage.zip` to download a (compressed) ZIP file with this problem's distribution.
1. Execute `unzip homepage.zip` to uncompress that file.
1. Execute `rm homepage.zip` followed by `yes` or `y` to delete that ZIP file.
1. Execute `ls`. You should see a directory called `homepage`, which was inside of that ZIP file.
1. Execute `cd homepage` to change into that directory.
1. Execute `ls`. You should see this problem's distribution, including `index.html` and `styles.css`.

== Specification

Implement in your `homepage` directory a website which must:

* Contain at least four different `.html` pages, at least one of which is `index.html` (the main page of your website), and it should be possible to get from any page on your website to any other page by following one or more hyperlinks.
* Use at least eight (8) different HTML tags besides `<html>`, `<head>`, `<body>`, and `<title>`.
* Integrate Bootstrap's CSS styling to your site, and incorporate some of Bootstrap's styling options, examples of which exist in link:https://getbootstrap.com/docs/4.1/getting-started/introduction/[Bootstrap's documentation]. Recall that, per that documentation, you can use their stylesheet by adding the following line between your `<head>` tags:
+
```
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
```

* Have at least one stylesheet file of your own creation, which uses at least five (5) different CSS selectors (e.g. tag (`body`), class (`.example`), or ID (`#example`)), and within which you use a total of at least five (5) different CSS properties, such as `font-size`, or `margin`; and
* Ensure that your site looks nice on browsers both on mobile devices as well as laptops and desktops.

== Testing

If you want to view how your site looks while you work on it, there are two options:

1. Within CS50 IDE, navigate to your `homepage` directory (remember how?) and then execute
+
```
http-server
```
1. Within CS50 IDE, right-click (or Ctrl+click, on a Mac) on the `homepage` directory in the file tree at left. From the options that appear, select **Serve**, which should open a new tab in your browser (it may take a second or two) with your site therein.

In either case, you'll be brought to a URL of the form

```
http://ide50-USERNAME.cs50.io:8080
```

Where `USERNAME` is your username on CS50 IDE, and the `8080` at the end refers to the _port number_ on which your web server is listening for requests (instead of the default `80` or `443` for HTTP and HTTPS requests, respectively). At that location, you'll see a listing of all of the files in your `homepage` directory, and from there can navigate to any HTML page you've designed.

Recall also that by opening Developer Tools, you can _simulate_ visiting your page on a mobile device by clicking the phone-shaped icon to the left of *Elements* in the developer tools window, or, once the Developer Tools tab has already been opened, by typing `Ctrl`+`Shift`+`M` on a PC or `Cmd`+`Shift`+`M` on a Mac, rather than needing to visit your site on a mobile device separately!

=== `check50`

Afraid there's no `check50` for this assignment, but your site's correctness will be assessed based on whether you meet the requirements of the specification as outlined above.

=== HTML Validator

To ensure that your HTML is well-designed and valid, you can use link:https://validator.w3.org/#validate_by_input[the W3Schools HTML Validator] service, copying and pasting your HTML directly into the provided text box. Take care to eliminate any warnings or errors suggested by the validator before submitting!

=== `style50`

Afraid `style50` does not support HTML files, and so it is incumbent upon you to indent and align your HTML tags cleanly. Know also that you can create an HTML comment with:

```
<!-- comment goes here -->
```

but commenting your HTML code is not as imperative as it is when commenting code in, say, C or Python.

== Hints

For fairly comprehensive guides on the languages introduced in this problem, check out the documentation for each on W3Schools.

* link:https://www.w3schools.com/html[HTML]
* link:https://www.w3schools.com/css[CSS]
* link:https://www.w3schools.com/js[JavaScript]

== How to Submit

Execute the below, logging in with your GitHub username and password when prompted. For security, you'll see asterisks (`*`) instead of the actual characters in your password.

```
submit50 cs50/2018/fall/homepage
```

== How to Publish

And if you'd like to publish your site publicly so that your classmates, friends, and anyone who knows your GitHub username can visit your page on the web. To do so, execute the below:

```
submit50 cs50/2018/fall/publish
```

This will, after about a minute or so, publish your site to `submit50.github.com/USERNAME`, where `USERNAME` is your own GitHub username. Be sure to check out your own site to make sure it looks right, as well as visiting those of your friends!
