---
layout: 2017/spring
---
:skip-front-matter:

= Warm-Up: Scramble

== tl;dr

[start=0]
. Watch https://video.cs50.net/2016/fall/lectures/5[Week 5's lecture].
. Implement a classic game.
. Submit your code.
. Submit a form.

== Reminders

* Use `help50` as needed.
* Use `eprintf` as needed.
* Use `debug50` as needed.

== Getting Started

Recall that CS50 IDE is a web-based "integrated development environment" that allows you to program "in the cloud," without installing any software locally. Underneath the hood is a popular operating system, Ubuntu Linux, that's been "containerized" with open-source software called Docker, that allows multiple users (like you!) to share the operating system's "kernel" (its nucleus, so to speak) and files, even while having files of their own. Indeed, CS50 IDE provides you with your very own "workspace" (i.e., storage space) in which you can save your own files and folders (aka directories).

Head to https://cs50.io/[cs50.io] and log into CS50 IDE. Toward the bottom of CS50 IDE's UI is a "terminal window" (light blue, by default), a command-line interface (CLI) that allows you to explore your workspace's files and directories, compile code, run programs, and even install new software. You should find that its "prompt" resembles the below.

[source,text]
----
~/workspace/ $
----

== What to Do

. Complete the implementation of link:../../../../../problems/scramble/scramble.html[Scramble]

== How to Submit

Refresh this page on (or after) Mon 2/6 for submission instructions!

This was the Warm-Up.
