---
layout: 2017/spring
---
:skip-front-matter:

= Warm-Up: Scramble

== tl;dr

[start=0]
. Watch https://video.cs50.net/2016/fall/lectures/5[Week 5's lecture].
. Implement a classic game.
. Submit your code.
. Submit a form.

== Reminders

* Use `help50` as needed.
* Use `eprintf` as needed.
* Use `debug50` as needed.

== Getting Started

Recall that CS50 IDE is a web-based "integrated development environment" that allows you to program "in the cloud," without installing any software locally. Underneath the hood is a popular operating system, Ubuntu Linux, that's been "containerized" with open-source software called Docker, that allows multiple users (like you!) to share the operating system's "kernel" (its nucleus, so to speak) and files, even while having files of their own. Indeed, CS50 IDE provides you with your very own "workspace" (i.e., storage space) in which you can save your own files and folders (aka directories).

Head to https://cs50.io/[cs50.io] and log into CS50 IDE. Toward the bottom of CS50 IDE's UI is a "terminal window" (light blue, by default), a command-line interface (CLI) that allows you to explore your workspace's files and directories, compile code, run programs, and even install new software. You should find that its "prompt" resembles the below.

[source,text]
----
~/workspace/ $
----

== What to Do

. Complete the implementation of link:../../../../../problems/scramble/scramble.html[Scramble]

== How to Submit

== How to Submit

For this and future problem sets, we'll be using a submission system based on GitHub, a popular site for storing code. Recall that when you filled out http://forms.cs50.net/2017/spring/e50b/section[the sectioning preference] you signed up (hopefully!) for an account on https://github.com/[github.com]. If you didn't, please go fill out that form now; you won't be able to submit without a GitHub account, and we'll need to know your account name in order to give your teaching fellow access to grading it!

=== Step 1 of 4

Execute

[source]
----
update50
----

to bring your IDE up-to-date.

=== Step 2 of 4

Visit https://cs50.me[cs50.me] and sign in using your GitHub credentials. This will authorize the `submit50` utility to push your code to your GitHub repositories on your behalf so that your work can be commented on and graded by your teaching fellow.

=== Step 3 of 4

Return to your CS50 IDE and navigate to your terminal window. Begin by first executing:
[source]
----
cd ~/workspace/warmup
----

* Then, to submit `scramble`, execute
+
[source]
----
submit50 e50b/2017/spring/scramble
----
+
inputting your GitHub username and GitHub password as prompted. You should be notified that `scramble.c` (along with most other files you may have optionally created) will be submitted, but some files (e.g. `words.txt`) will (intentionally!) not be.

If you run into any trouble, email sysadmins@cs50.harvard.edu, cc'ing heads@cs50.harvard.edu!

You may resubmit any problem as many times as you'd like, up until the problem set deadline.

=== Step 4 of 4

To confirm that your work was indeed submitted, you can either visit the link that is generated at the end of the `submit50` output, or you can view your work in a centralized location at https://cs50.me[cs50.me].

This was the Warm-Up.
