---
layout: 2018/spring
---
:skip-front-matter:

= Problem Set 6: Déjà vu

== tl;dr

[start=0]
. Watch https://video.cs50.net/2017/fall/lectures/6[Lecture 6], https://video.cs50.net/2017/fall/lectures/7[Lecture 7], https://video.cs50.net/2017/fall/lectures/8[Lecture 8], and https://video.cs50.net/2017/fall/lectures/9[Lecture 9], if you haven't already.
. Port some programs from C to Python.
. Detect some similarities.
. Submit your code.
. Submit a form.

include::help-harvard.adoc[]

== Getting Started

[source]
----
update50
mkdir ~/workspace/pset6/
cd ~/workspace/pset6/
----

== Problems

. Implement link:sentimental/sentimental[Sentimental].
. Implement either of:
+
--
* link:similarities/less/similarities.html[Similarities], less comfortable
* link:similarities/more/similarities.html[Similarities], more comfortable
--

== How to Submit

=== Step 1 of 2

. Execute `update50`
. Execute `cd ~/workspace/pset6/hello/ && submit50 cs50/2018/spring/sentimental/hello`
. Execute at least one of:
+
--
* `cd ~/workspace/pset6/mario/ && submit50 cs50/2018/spring/sentimental/mario/less`
* `cd ~/workspace/pset6/mario/ && submit50 cs50/2018/spring/sentimental/mario/more`
--
. Execute at least one of:
+
--
* `cd ~/workspace/pset6/cash/ && submit50 cs50/2018/spring/sentimental/cash`
* `cd ~/workspace/pset6/credit/ && submit50 cs50/2018/spring/sentimental/credit`
--
. Execute at least one of:
+
--
* `cd ~/workspace/pset6/caesar/ && submit50 cs50/2018/spring/sentimental/caesar`
* `cd ~/workspace/pset6/vigenere/ && submit50 cs50/2018/spring/sentimental/vigenere`
* `cd ~/workspace/pset6/crack/ && submit50 cs50/2018/spring/sentimental/crack`
--
. Execute at least one of:
+
--
* `cd ~/workspace/pset6/similarities/ && submit50 cs50/2018/spring/similarities/less`
* `cd ~/workspace/pset6/similarities/ && submit50 cs50/2018/spring/similarities/more`
--

=== Step 2 of 2

Submit https://forms.cs50.net/2018/spring/psets/6[]!

This was Problem Set 6.
