---
layout: 2016/fall
title: Buggy
---
:skip-front-matter:

= Problem: Buggy

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

==  Objectives

* Debug code
* Review capabilities and limitations of C
* Review functions and libraries

== Academic Honesty

This course's philosophy on academic honesty is best stated as "be reasonable." The course recognizes that interactions with classmates and others can facilitate mastery of the course's material. However, there remains a line between enlisting the help of another and submitting the work of another. This policy characterizes both sides of that line.

The essence of all work that you submit to this course must be your own. Collaboration on problems is not permitted (unless explicitly stated otherwise) except to the extent that you may ask classmates and others for help so long as that help does not reduce to another doing your work for you. Generally speaking, when asking for help, you may show your code or writing to others, but you may not view theirs, so long as you and they respect this policy's other constraints. Collaboration on quizzes and tests is not permitted at all. Collaboration on the final project is permitted to the extent prescribed by its specification.

Below are rules of thumb that (inexhaustively) characterize acts that the course considers reasonable and not reasonable. If in doubt as to whether some act is reasonable, do not commit it until you solicit and receive approval in writing from your instructor. If a violation of this policy is suspected and confirmed, your instructor reserves the right to impose local sanctions on top of any disciplinary outcome that may include an unsatisfactory or failing grade for work submitted or for the course itself.

=== Reasonable

* Communicating with classmates about problems in English (or some other spoken language).
* Discussing the course's material with others in order to understand it better.
* Helping a classmate identify a bug in his or her code, such as by viewing, compiling, or running his or her code, even on your own computer.
* Incorporating snippets of code that you find online or elsewhere into your own code, provided that those snippets are not themselves solutions to assigned problems and that you cite the snippets' origins.
* Reviewing past years' quizzes, tests, and solutions thereto.
* Sending or showing code that you've written to someone, possibly a classmate, so that he or she might help you identify and fix a bug.
* Sharing snippets of your own solutions to problems online so that others might help you identify and fix a bug or other issue.
* Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problems or your own final project.
* Whiteboarding solutions to problems with others using diagrams or pseudocode but not actual code.
* Working with (and even paying) a tutor to help you with the course, provided the tutor does not do your work for you.

=== Not Reasonable

* Accessing a solution to some problem prior to (re-)submitting your own.
* Asking a classmate to see his or her solution to a problem before (re-)submitting your own.
* Decompiling, deobfuscating, or disassembling the staff's solutions to problems.
* Failing to cite (as with comments) the origins of code, writing, or techniques that you discover outside of the course's own lessons and integrate into your own work, even while respecting this policy's other constraints.
* Giving or showing to a classmate a solution to a problem when it is he or she, and not you, who is struggling to solve it.
* Looking at another individual's work during a quiz or test.
* Paying or offering to pay an individual for work that you may submit as (part of) your own.
* Providing or making available solutions to problems to individuals who might take this course in the future.
* Searching for, soliciting, or viewing a quiz's questions or answers prior to taking the quiz.
* Searching for or soliciting outright solutions to problems online or elsewhere.
* Splitting a problem's workload with another individual and combining your work (unless explicitly authorized by the problem itself).
* Submitting (after possibly modifying) the work of another individual beyond allowed snippets.
* Submitting the same or similar work to this course that you have submitted or will submit to another.
* Using resources during a quiz beyond those explicitly allowed in the quiz's instructions.
* Viewing another's solution to a problem and basing your own solution on it.

== Assessment

Your work on this problem set will be evaluated along four axes primarily.

Scope::
 To what extent does your code implement the features required by our specification?
Correctness::
 To what extent is your code consistent with our specifications and free of bugs?
Design::
 To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?
Style::
 To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Buggin’ Out

Tell me if this sounds familiar, you’ve written some code and maybe used help50, and your program compiles. Then you run your program with some sample inputs (so long as you know what the output should be) and you get some unexpected results. This is what is referred to as a bug. Fear not, there are many tools specifically designed to help us find and fix these bugs. But more on those later.

You'll be downloading some "distribution code" (otherwise known as a "distro"), written by us, and make modifications to it. You're welcome of course to use all the CS50 tools and resources to help you debug.
Start off by opening up CS50 IDE and then type

[source,bash]
----
update50
----

within a terminal window to make sure your workspace is up-to-date. If you somehow closed your terminal window (and can't find it!), make sure that *Console* is checked under the *View* menu, then click the green, circled plus (+) in CS50 IDE's bottom half, then select *New Terminal*. If you need a hand, do just ask via the channels noted at the top of this specification.

Next, navigate to your `chapter2` directory, as with

[source,bash]
----
cd ~/workspace/chapter2
----

Keep in mind that `~` denotes your home directory, `~/workspace` denotes a directory called `workspace` therein, and `~/workspace/chapter2` denotes a directory called `chapter2` within `~/workspace`. Your prompt should now resemble the below.

[source,bash]
----
~/workspace/chapter2 $
----

Now, at the prompt, type:

[source,bash]
----
wget http://docs.cs50.net/2016/fall/cscie50a/problems/buggy/buggy.zip
----

to download a ZIP of this problem's distro into your workspace (with a command-line program called `wget`). You should see some output followed by:

[source,bash]
----
‘buggy.zip' saved
----

Confirm that you've indeed downloaded `buggy.zip` by executing

[source,bash]
----
ls
----

and then run

[source,bash]
----
unzip buggy.zip
----

to unzip the file. If you then run `ls` again, you should see that you have a newly unzipped directory called `friends` as well. Proceed to execute

[source,bash]
----
cd buggy
----

followed by

[source,bash]
----
ls
----

and you should indeed see five buggy programs!

[source,bash]
----
buggy1.c  buggy2.c  buggy3.c  buggy4.c  buggy5.c
----

== debug50

As mentioned earlier, you are not on your own when it comes to debugging these programs. Here’s David with some information about a tool, debug50, that might help you as you debug these programs.

video::2zPEHYoiyfc[youtube,height=540,width=960,start=1339,end=1742]

== Debugging Buggy


=== Buggy1

We’ve written five programs that seem to act a bit buggy. Let’s go through each one to see what needs to be done. The first program, buggy1, is meant to print: 

[source,bash]
----
*#*#*#*#*#*#*#*#*#*#
----

but instead prints:

[source,bash]
----
***********#
----

Seems easy enough to fix (indeed this should be rather trivial).

=== Buggy2

Buggy2 is a program that is supposed to print out a string, entered by the user, character by character. The program should exit if the string contains a character that is not a letter in the alphabet.

However the program seems to print out the string regardless of if there are symbols or numbers. When Zamyla1 is entered, the program should exit, instead it prints:

[source,bash]
----
Z
a
m
y
l
a
1
----

(hint: take a look at https://reference.cs50.net)

=== Buggy3

Buggy3 should bring back memories of high school (Ah, the nostalgia). If the pythagorean theorem doesn’t ring a bell, it is the formula that two legs of a right triangle (a, b) are related the hypotenuse (c) in the following way, a^2^ + b^2^ = c^2^. 

You may have also learned about pythagorean triples (not to worry if you didn’t). These are lengths of right triangles that are strictly integers, ex. 3, 4, 5. Since 3^2^ + 4^2^ = 9 + 16 = 25 = 5^2^.

In buggy3.c, the same logic was attempted. Looks like part of the function is defined in main and some of it is defined in the function. It also looks like when 3 and 4 are entered as legs of the triangle, 25 is printed. So this is a two step problem, first clean up this program by abstracting out all aspects of the pythagorean theorem into the function `pythag` and change your parameters accordingly, then fix the logic aspect so that 5 would be printed if 3 and 4 are entered. Your program should take in two legs of a triangle and print the hypotenuse. 

=== Buggy4

This is a long one. Take some time to read through it carefully. This program takes in four parameters: min1, min2_10, min11, and s. The first, min1, represents the cost of a phone call (in cents) for the first minute. Likewise, min2_10, represents the cost of minutes 2-10 (inclusive) and as you might have guessed, min11 represents the cost per minute thereafter. Lastly, s, represents how much change the user has. So if I input [3, 1, 2, 4] respectively, the program should print:

[source,bash]
----
The longest phone call that can be made is 2 minutes long.
----

This is because the first minute costs 3 cents and the second minute costs 1 cent. 

Be sure to check corner cases here. Try to intentionally put in strange cases to make sure you get the expected output. One such case is that when s = 0, the program should always return: 

[source,bash]
----
The longest phone call that can be made is 0 minutes long.
----

regardless of the other inputs.

=== Buggy5

This last program takes two integers from the user. The first of which, n, represents the number of children present and the second, m, represents the pieces of candy that the children are going to split amongst themselves. In order to be fair (which we know is usually not the case), each child has to have the same amount of pieces of candy. 

For example if `n = 3` and `m = 2`, buggy5.c should output:

[source,bash]
----
The children ate 0 pieces of candy
----

Since there weren’t enough pieces of candy to go around. Similar if `n = 3` and `m = 10`, buggy5.c should output 9, since each child could eat 3 pieces and there are 3 children. Again be sure to check corner cases here as well, to make sure your fixes work in all cases.

This was Buggy.
