---
layout: 2019/spring
---
:skip-front-matter:

= Final Project

The climax of this course is its final project. The final project is your opportunity to take your newfound savvy with programming out for a spin and develop your very own piece of software. So long as your project draws upon the course's lessons, the nature of your project is entirely up to you, albeit subject to the staff's approval. You may implement your project in any language(s) as long as the staff approves. You are welcome to utilize any infrastructure, provided the staff ultimately has access to any hardware and software that your project requires. All that we ask is that you build something of interest to you, that you solve an actual problem, that you impact campus, or that you change the world. Strive to create something that outlives this course.

Inasmuch as software development is rarely a one-person effort, you are allowed an opportunity to collaborate with one or two classmates for this final project. Needless to say, it is expected that every student in any such group contribute equally to the design and implementation of that group's project. Moreover, it is expected that the scope of a two- or three-person group's project be, respectively, twice or thrice that of a typical one-person project. A one-person project, mind you, should entail more time and effort than is required by each of the course's problem sets. Although no more than three students may design and implement a given project, you are welcome to solicit advice from others, so long as you respect the course's policy on academic honesty.

__Extensions on the final project are not ordinarily granted, except in cases of emergency.__

== Ideas

Here are just some of the possibilities, organized into (non-exhaustive) "tracks". Discuss any and all with your TF! And if you'd like to solicit collaborators for an idea you have, do post to https://discourse.cs50.net/[Discourse]!

If at a loss for ideas, here are some seminars from years past for inpsiration!

* https://www.youtube.com/playlist?list=PLhQjrBD2T3827WgJGDFuK2cKnPBNOdIwa[CS50 Seminars 2018]
* https://www.youtube.com/playlist?list=PLhQjrBD2T381wZBYZUCoFFavyHHhHQmyQ[CS50 Seminars 2017]
* https://www.youtube.com/playlist?list=PLhQjrBD2T382IHcDBSQYC4ZG4C2aTiA6C[CS50 Seminars 2016]

=== Software Track

* a web-based application using JavaScript, Python, and SQL, based in part on Problem Set 8's distribution code
* a web-based application using PHP or Ruby
* a plugin for CS50 IDE using JavaScript
* a Chrome extension using JavaScript
* an iOS app using Swift (or Objective-C)
* an Android app using Java
* a command-line program using C
* ...

=== Cross-Course Track

Like to combine two courses' projects? If taking some other course this semester that has a final project, you are welcome and encouraged to combine this course's project and that course's project into one, toward an end of applying lessons learned in CS50 to some other field, so long as the joint project satisfies this course's and that course's expectations. Before pursuing a joint project, though, you must disclose to both courses and receive approval from both courses (as from your TF in CS50).

=== Hardware Track

Like to integrate hardware into your project? Know that CS50 has the following hardware with which you're welcome to create something amazing:

* an https://developer.apple.com/programs/[iOS Developer Program], which allows you to install homemade apps on your own iOS device,
* some https://www.arduino.cc/en/Main/arduinoBoardUno[Arduino Uno] boards, for which there's an https://www.arduino.cc/en/Reference/HomePage[API],
* some https://www.google.com/get/cardboard/[Google Cardboards], for which there's an developers.google.com/cardboard[API],
* an https://www.vive.com/us/[HTC Vive], for which there's an https://developer.viveport.com/us/develop_portal/[SDK]
* some https://docs.particle.io/datasheets/photon-datasheet/[Internet of Things hardware development kits] and https://docs.particle.io/guide/tools-and-features/button/core/[Internet Buttons], for which there's an https://docs.particle.io/guide/tools-and-features/dev/[IDE] and https://docs.particle.io/guide/getting-started/examples/photon/[API],
* some https://www.leapmotion.com/[Leap Motion Controllers], for which there's an https://developer.leapmotion.com/[API],
* a https://www.microsoft.com/microsoft-hololens/en-us[Microsoft HoloLens], for which there's an https://www.microsoft.com/microsoft-hololens/en-us/developers[SDK]
* an https://www.oculus.com/[Oculus Rift] and an https://www3.oculus.com/en-us/dk2/[Oculus DK2], for which there's an https://developer.oculus.com/[SDK]
* some http://www2.meethue.com/en-us/productdetail/philips-hue-white-and-color-ambiance-starter-kit-a19[Philips hue bulbs], for which there's an http://www.developers.meethue.com/[API],
* some http://www.samsung.com/global/galaxy/gear-vr/[Samsung Gear VRs], for which there's an http://developer.samsung.com/gear/[SDK], and
* some http://www.sonos.com/en-us/shop/play1.html[Sonos PLAY:1s], for which there's an http://musicpartners.sonos.com/?q=docs[API].

If you'd like to borrow something for a project, email heads@cs50.harvard.edu, and we'll do our best to oblige, sharing hardware across classmates as needed. Let us know, too, if there's some other hardware or software you'd like to utilize for a project, and we'll do our best to find it.

== Specifications

Extensions on the final project are not granted, except in cases of emergency.

=== Preproposal

_due by Tue 4/16, 11:59pm_

Intended to promote early thought, the preproposal is your opportunity to bounce one or more ideas off of your teaching fellow. If collaborating with one or two classmates, each of you should submit a preproposal, even if identical.

Here's how to submit your preproposal. Log into link:https://ide.cs50.io/[CS50 IDE] and then, in a terminal window:

1. Execute `cd` to ensure that you're in `~`.
1. Execute `mkdir project` to make (i.e., create) a directory called `project` in your `~` directory.
1. Execute `cd project` to change into (i.e., open) that directory.
1. Execute `wget http://cdn.cs50.net/2018/fall/project/preproposal.zip` to download a (compressed) ZIP file.
1. Execute `unzip preproposal.zip` to uncompress that file.
1. Execute `rm preproposal.zip` followed by `yes` or `y` to delete that ZIP file.
1. Execute `ls`. You should see a directory called `preproposal`, which was inside of that ZIP file.
1. Execute `cd preproposal` to change into that directory.
1. Execute `ls`. You should see a file called `README.md` therein.

Edit that file in CS50 IDE, answering the questions therein.

Then execute the below from within your `~/project/preproposal` directory, logging in with your GitHub username and password when prompted. For security, you'll see asterisks (`*`) instead of the actual characters in your password.

```
submit50 cs50/2019/spring/project/preproposal
```
=== Proposal

_due by Fri 4/26, 11:59pm_

The proposal is your opportunity to receive approval and counsel from your teaching fellow before you proceed to design. **If collaborating with one or two classmates, each of you should submit a proposal, even if identical.**

Your teaching fellow will either approve your proposal or require modifications on your part for subsequent approval.  Your proposal, even if approved, is not binding; you may alter your plan at any point, provided you obtain your teaching fellow's approval for any modifications.  Projects submitted without approval may not receive credit.

After submitting your proposal, a teaching fellow other than your own may be appointed your advisor and grader for the remainder of the final project, depending on your proposal's nature.

Here's how to submit your proposal.

==== Step 1 of 2

Submit https://forms.cs50.io/cab12d6f-79dd-40bf-a840-ec7742118953[this form].

==== Step 2 of 2

Here's how to submit your proposal. Log into link:https://ide.cs50.io/[CS50 IDE] and then, in a terminal window:

1. Execute `cd` to ensure that you're in `~`.
1. Execute `mkdir project` to make (i.e., create) a directory called `project` in your `~` directory.
1. Execute `cd project` to change into (i.e., open) that directory.
1. Execute `wget http://cdn.cs50.net/2018/fall/project/proposal.zip` to download a (compressed) ZIP file.
1. Execute `unzip proposal.zip` to uncompress that file.
1. Execute `rm proposal.zip` followed by `yes` or `y` to delete that ZIP file.
1. Execute `ls`. You should see a directory called `proposal`, which was inside of that ZIP file.
1. Execute `cd proposal` to change into that directory.
1. Execute `ls`. You should see a file called `README.md` therein.

Edit that file in CS50 IDE, answering the questions therein.

Then execute the below from within your `~/project/proposal` directory, logging in with your GitHub username and password when prompted. For security, you'll see asterisks (`*`) instead of the actual characters in your password.

```
submit50 cs50/2019/spring/project/proposal
```


=== Status Report

_due by Tue 5/7, 11:59pm_

Not only is the status report intended to keep the staff apprised of your progress, it is an opportunity to keep yourself on track. If collaborating with one or two classmates, each of you should submit a status report, even if identical.

Here's how to submit your status report. Log into link:https://ide.cs50.io/[CS50 IDE] and then, in a terminal window:

1. Execute `cd project` to change into (i.e., open) your project directory.
1. Execute `wget http://cdn.cs50.net/2018/fall/project/status.zip` to download a (compressed) ZIP file.
1. Execute `unzip status.zip` to uncompress that file.
1. Execute `rm status.zip` followed by `yes` or `y` to delete that ZIP file.
1. Execute `ls`. You should see a directory called `status`, which was inside of that ZIP file.
1. Execute `cd status` to change into that directory.
1. Execute `ls`. You should see a file called `status.md` therein.

Edit that file in CS50 IDE, answering the questions therein.

Then execute the below from within your `~/project/status` directory, logging in with your GitHub username and password when prompted. For security, you'll see asterisks (`*`) instead of the actual characters in your password.

```
submit50 cs50/2019/spring/project/status
```

=== Implementation

Ultimately due are implementation and documentation of your final project.  Your submission thereof must include all of the below.

. Documentation for your project in the form of a Markdown file called `README.md`. This documentation is to be a user's manual for your project.  Though the structure of your documentation is entirely up to you, it should be incredibly clear to the staff how and where, if applicable, to compile, configure, and use your project.  Your documentation should be at least several paragraphs in length.  It should not be necessary for us to contact you with questions regarding your project after its submission.  Hold our hand with this documentation; be sure to answer in your documentation any questions that you think we might have while testing your work.
. A "design document" for your project in the form of a Markdown file called `DESIGN.md` that discusses, technically, how you implemented your project and why you made the design decisions you did.  Your design document should be at least several paragraphs in length.  Whereas your documentation is meant to be a user's manual, consider your design document your opportunity to give the staff a technical tour of your project underneath its hood.
. Any and all files required to run your software (even if intended for some infrastructure other than CS50 IDE), including source code as well as, if applicable, configuration files, Makefiles, sample inputs, SQLite databases, and so forth. Needless to say, all source code should be thoroughly commented.
. A short video (that's no more than 3 minutes in length) in which you present your project to the world, as with slides, screenshots, voiceover, and/or live action.  Your video should somehow include your project's title, your name and year, your dorm/house and concentration, and any other details that you'd like to convey to viewers.  See http://www.cs171.org/2015/screencast/[CS171's tips on how to make a "screencast"] though you're welcome to use an actual camera.  Upload your video to YouTube as "public" or "unlisted" and take note of its URL.

==== How to Submit

*If you have collaborated with one or two other students, each of you should submit via this same process.*

*If your project requires (for execution and testing) hardware or software other than that offered by CS50 IDE, be sure that the TF advising you is aware of and has approved your project's needs.*

===== Step 1 of 2

[source]
----
cd ~/project/ # or wherever you've stored your project
submit50 cs50/2019/spring/project/implementation
----

===== Step 2 of 2

Submit https://forms.cs50.io/1ff8fdaf-a0d6-4fc4-8394-bdffc6dbe7dd[]!

**This last form is on the longer side, so no worries if you start it before the deadline but finish a bit after.**


=== App Party

_Fri 5/17, 5:30pm – 7pm_

The App Party is an opportunity to display final projects in person in a celebratory atmosphere, alongside classmates from not only CSCI E-50 but also CSCI E-23a and CSCI E-33a; your opportunity to showcase your work not only to us but also to others on campus. Attendance, while strongly encouraged by those local, is not required. Attendees will be expected to bring to the App Party a laptop with which to demonstrate your project.  Plan to tell attendees what you have done and why you have done it.  And perhaps have in mind a few anecdotes about lessons you learned, roadblocks you hit, or the like.

The CS50 Fair will take place in a location on Harvard's campus to be announced. You'll be able to register in advance for the App Party after the course staff sends an email with details.

include::../honesty.adoc[]
