---
layout: default
---
:skip-front-matter:

= Writing Problem: Be the Teacher

Questions? Feel free to head to https://www.reddit.com/r/cs50[CS50 on Reddit], http://cs50.stackexchange.com[CS50 on StackExchange], the `#cs50ap` channel on https://cs50x.slack.com[CS50x Slack] (after signing up), or the https://www.facebook.com/groups/cs50[CS50 Facebook group].

== Objectives

* Ensure you're familiar with all components of the Internet.
* Think about how to talk about technical topics in layman's terms.

include::../../honesty.adoc[]

== Assessment

Your work on this writing problem will be evaluated along three axes primarily.

Scope::
    To what extent does your submission align with the requirements of the specification?
Correctness::
    To what extent is your submission correct and free of factual errors?
Style::
    To what extent is your submission readable (i.e., thoughtfully organized, coherent, words properly spelled)?


To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Throwback

You should now be familiar with all the major components of networks and how they all fit together. Take a minute to think back on everything you've learned. If you need a reminder, these were the topics:

* IP addresses
* DNS
* DHCP
* Routers
* TCP/IP
* HTTP

Remember what each does? Here's your chance to prove it.

In no more than *1500 wordsfootnote:[Seriously! In the real world, projects often have specifications just like this one, and it's frequently quite important to adhere to those specifications exactly so that you are in compliance with project scope. So keep it to 1500 words, tops!], prepare a brief, five- to seven-minute-long speech to give to a class of 3rd graders explaining how the Internet works*. You should cover each of the topics above, but avoid technical jargon - remember, you're teaching elementary school kids! The emphasis is on what each individual component does in practicality and how they all fit together, not teaching terminology and definitions.

Don't be afraid to get creative with your explanations and come up with new analogies and demonstration ideas you haven't yet seen. It's your chance to be the teacher!

== How to Submit

Submit https://forms.cs50.net/2016/x/ap/teacher[this form]!

This was Be the Teacher.
