---
layout: 2019/ap
---
:skip-front-matter:

= Problem: Credit

== tl;dr

Implement a program that determines whether a provided credit card number is valid according to Luhn’s algorithm.

[source, subs=quotes]
----
$ [underline]#./credit#
Number: [underline]#378282246310005#
AMEX
----

include::../../honesty.adoc[]

== Assessment

Your work on this problem set will be evaluated along three axes primarily.

Correctness::
  To what extent is your code consistent with our specifications and free of bugs?

Design::
  To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?

Style::
  To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Background

Odds are you or someone you know has a credit card. That card has a number, both printed on its face and embedded (perhaps with some other data) in the magnetic stripe on back.  That number is also stored in a database somewhere, so that when your card is used to buy something, the creditor knows whom to bill. There are a lot of people with credit cards in this world, so those numbers are pretty long: American Express uses 15-digit numbers, MasterCard uses 16-digit numbers, and Visa uses 13- and 16-digit numbers.  And those are decimal numbers (0 through 9), not binary, which means, for instance, that American Express could print as many as 10^(15) = 1,000,000,000,000,000 unique cards! (That's, ahem, a quadrillion.)

Now that's a bit of an exaggeration, because credit card numbers actually have some structure to them.  American Express numbers all start with 34 or 37; MasterCard numbers all start with 51, 52, 53, 54, or 55; and Visa numbers all start with 4.  But credit card numbers also have a "checksum" built into them, a mathematical relationship between at least one number and others.  That checksum enables computers (or humans who like math) to detect typos (e.g., transpositions), if not fraudulent numbers, without having to query a database, which can be slow.  (Consider the awkward silence you may have experienced at some point whilst paying by credit card at a store whose computer uses a dial-up modem to verify your card.)  Of course, a dishonest mathematician could certainly craft a fake number that nonetheless respects the mathematical constraint, so a database lookup is still necessary for more rigorous checks.

So what's the secret formula?  Well, most cards use an algorithm invented by Hans Peter Luhn, a nice fellow from IBM.  According to Luhn's algorithm, you can determine if a credit card number is (syntactically) valid as follows:

[start=0]
. Multiply every other digit by 2, starting with the number's second-to-last digit, and then add those products' digits together.
. Add the sum to the sum of the digits that weren't multiplied by 2.
. If the total's last digit is 0 (or, put more formally, if the total modulo 10 is congruent to 0), the number is valid!

That's kind of confusing, so let's try an example with David's Visa: 4003600000000014.

[start=0]
. For the sake of discussion, let's first underline every other digit, starting with the number's second-to-last digit:

[underline]##4##0[underline]##0##3[underline]##6##0[underline]##0##0[underline]##0##0[underline]##0##0[underline]##0##0[underline]##1##4
+
Okay, let's multiply each of the underlined digits by 2:
+
1•2 + 0•2 + 0•2 + 0•2 + 0•2 + 6•2 + 0•2 + 4•2
+
That gives us:
+
2 + 0 + 0 + 0 + 0 + 12 + 0 + 8
+
Now let's add those products' digits (i.e., not the products themselves) together:
+
2 + 0 + 0 + 0 + 0 + 1 + 2 + 0 + 8 = 13
+
. Now let's add that sum (13) to the sum of the digits that weren't multiplied by 2 (starting from the end):
+
13 + 4 + 0 + 0 + 0 + 0 + 0 + 3 + 0 = 20
+
. Yup, the last digit in that sum (20) is a 0, so David's card is legit!

So, validating credit card numbers isn't hard, but it does get a bit tedious by hand. Let's write a program.


== Specification

* In `credit.c` in `~chapter1/credit`, write a program that prompts the user for a credit card number and then reports (via `printf`) whether it is a valid American Express, MasterCard, or Visa card number, per the definitions of each's format herein.
* So that we can automate some tests of your code, we ask that your program's last line of output be `AMEX\n` or `MASTERCARD\n` or `VISA\n` or `INVALID\n`, nothing more, nothing less, and that `main` always return `0`.
* For simplicity, you may assume that the user's input will be entirely numeric (i.e., devoid of hyphens, as might be printed on an actual card).
* Do not assume that the user's input will fit in an `int`! Best to use `get_long` from CS50's library to get users' input. (Why?)

== Walkthrough

video::06wNhN54P6k[youtube]

== Usage

Consider the below representative of how your own program should behave when passed a valid credit card number (sans hyphens).

[source,subs=quotes]
----
$ [underline]#./credit#
Number: [underline]#4003600000000014#
VISA
----

Now, `get_long` itself will reject hyphens (and more) anyway:

[source,subs=quotes,text]
----
$ [underline]#./credit#
Number: [underline]#4003-6000-0000-0014#
Number: [underline]#foo#
Number: [underline]#4003600000000014#
VISA
----

But it's up to you to catch inputs that are not credit card numbers (e.g., a phone number), even if numeric:

[source,subs=quotes,text]
----
$ [underline]#./credit#
Number: [underline]#6176292929#
INVALID
----

== Testing

Test out your program with a whole bunch of inputs, both valid and invalid. (We certainly will!) Here are a few card numbers that PayPal recommends for testing:

https://developer.paypal.com/docs/classic/payflow/payflow-pro/payflow-pro-testing/#credit-card-numbers-for-testing

Google (or perhaps a roommate's wallet) should turn up more. (If your roommate asks what you're doing, don't mention us.) If your program behaves incorrectly on some inputs (or doesn't compile at all), time to debug!

=== Correctness

[source,text]
----
check50 cs50/problems/2019/ap/credit
----

=== Style

[source]
----
style50 credit.c
----

== Staff Solution

[source]
----
~cs50/chapter1/credit
----

== How to Submit

=== Step 1 of 2

Ensure that `credit.c` is in `~/chapter1/credit`, as with:

[source]
----
cd ~/chapter1/credit
ls
----

If `credit.c` is not in `~/chapter1/credit`, move it into that directory, as via `mv` (or via CS50 IDE's lefthand file browser).

=== Step 2 of 2

* To submit `credit`, execute
+
[source]
----
cd ~/chapter1/credit
submit50 cs50/problems/2019/ap/credit
----
+

If you run into any trouble, email sysadmins@cs50.harvard.edu!

You may resubmit any problem as many times as you'd like before the deadline.

Your submission should be graded for correctness within 2 minutes, at which point your score will appear at https://submit.cs50.io/[submit.cs50.io]!

This was Credit.

== Hints

Test out your program with a whole bunch of inputs, both valid and invalid. (We certainly will!) Here are a few card numbers that PayPal recommends for testing:

https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm

Google (or perhaps a roommate's wallet) should turn up more. (If your roommate asks what you're doing, don't mention us.) If your program behaves incorrectly on some inputs (or doesn't compile at all), time to debug!
