---
layout: default
---
:skip-front-matter:

= Writing Problem: Tech Spotlight

== Objectives

* Become familiar with popular tech news sites.
* Incorporate multiple sources into your writing.
* Understand and reflect on some of the real-world implications of new technologies.

include::../../honesty.adoc[]

== Assessment

Your work on this Writing problem will be evaluated along three axes primarily.

Scope::
    To what extent does your submission align with the requirements of the specification?
Correctness::
    To what extent is your submission correct and free of factual errors?
Style::
    To what extent is your submission readable (i.e., thoughtfully organized, coherent, words properly spelled)?


To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Cats. And Viral Videos. And Viral Videos Starring Cats.

Odds are, at some point in your life, you've used the Internet. In fact, more likely than not you use it many times a day, every single day, and have done so for as far back as you can remember. Given that level of real-world Internet experience, it won't surprise you to know that the Web contains a lot of very useful data... and also some data that might not be quite so useful:

video::QH2-TGUlwu4[youtube,height=540,width=960]

Good luck getting that out of your head.

In this writing problem, we're going to try to home in on some of the corners of the Internet to keep your eye on as we begin to explore computer science in more depth.

The great thing about living what is commonly (mostly in non-tech circles) called the Digital Age is that there is always some new device or technology emerging that promises to revolutionize the way we live our lives. Some of these technologies do.footnote:[https://www.facebook.com/] Some... not so much.footnote:[https://en.wikipedia.org/wiki/Betamax]. Also fortunately for us, despite the Internet being a pretty big place, there are plenty of sites that dedicate themselves to reporting the latest tech-oriented news, product reviews, and commentary on how technologies impact our lives.

Sites like http://www.techcrunch.com[TechCrunch], http://www.wired.com[Wired], http://www.gizmodo.com[Gizmodo], http://www.mashable.com[Mashable], and http://www.techradar.com[TechRadar] are just a few of these websites that we at CS50 keep bookmarked in our browsers so we can always stay on top of the latest developments. Frequently these articles inform our understanding of new products, make us rethink previously-held opinions, or cause us to think about some of the implications of the technology that might not have seemed apparent at first glance. It's particularly the last item that we're focusing on in this assignment.

== Okay, So What Do I Do?

Pick some piece of technology with which you are familiar and that you might use everyday. It needn't be a piece of hardware; software, websites, and the like are perfectly fine too. Explore it in depth. Find some articles about recent developments (i.e., within the last three months) in this technology that have been posted on sites like the ones described earlier. Specifically, you should read a minimum of three (3) articles about the technology you've chosen, and include your list of sources at the end of your paper.footnote:[Your list of sources needn't be prepared as a bibliography following any particular citation style, but do be sure to include for each the name of the article read, name of the website or publication where you found the article, date the article was written, author's name, and URL, if found online.]

Then, in no more than *600 words*, expound on this technology. Assume for the purposes of this assignment that your audience is someone who has no prior knowledge about the technology you are describing, and so your objective is to provide them with a well-rounded, unbiased summary. In writing your response, you should consider this (non-exhaustive) list of questions a good starting point:

* What is this technology called?
* What does it do?
* How does someone use this technology?
* How is its quality of performance commonly measured? (e.g. in megabytes (MB), gigahertz (GHz), etc.)
* How does the recent news about the technology change the product or service?
* What older form of technology does it replace, if any?
* How has this technology impacted your life, for better or worse?
* How has this technology impacted society at large, for better or worse?

It's worth mentioning here that other than reporting on some technical specifications, which you may not have previously known but which may be listed in the articles themselves, you shouldn't be using text from your sources in your assignment directly. Rather, the articles you read will hopefully provide slightly different perspectives on the technology you've chosen, and you should synthesize those perspectives to comment on the technology more broadly.

To be clear, you're not standing in the role of a salesperson. Make sure to speak factually for the most part, and if you do cite or offer an opinion on the product (e.g., "I think this product is great because..."), be sure that your paper is balanced by offering the opposing opinion too (e.g., "Some people might dislike this product because...").

== How to Submit

Submit https://newforms.cs50.net/2016/x/ap/tech[this form]!

This was Tech Spotlight. And unfortunately, the Nyan Cat song is still stuck in our heads. :\
