---
layout: 2018/x
title: CS50x Syllabus
---
:skip-front-matter:

= Syllabus

Introduction to the intellectual enterprises of computer science and the art of programming. This course teaches students how to think algorithmically and solve problems efficiently. Topics include abstraction, algorithms, data structures, encapsulation, resource management, security, software engineering, and web development. Languages include C, Python, SQL, and JavaScript plus CSS and HTML. Problem sets inspired by real-world domains of biology, cryptography, finance, forensics, and gaming. Designed for majors and non-majors alike, with or without prior programming experience.

== Expectations

You are expected to

* submit nine problem sets and
* submit a final project.

== Website

https://cs50.edx.org/

== Certificates

CS50x is free to take, and you are welcome to submit the course's nine problem sets and final project for automated feedback. To be eligible for a https://www.edx.org/verified-certificate[verified certificate] from edX, however, you must receive a satisfactory score (at least 70%) on each problem you submit as part of one of the course's nine problem sets as well as on the course's final project.

== Books 

No books are required or recommended for this course. However, you might find the below books of interest. Realize that free, if not superior, resources can be found on the course's website.

_C Programming Absolute Beginner's Guide_, Third Edition +
Greg Perry, Dean Miller +
Pearson Education, 2014 +
ISBN 0-789-75198-4

_Hacker's Delight_, Second Edition +
Henry S. Warren Jr. +
Pearson Education, 2013 +
ISBN 0-321-84268-5
 
_How Computers Work_, Tenth Edition +
Ron White +
Que Publishing, 2014 +
ISBN 0-7897-4984-X

_Programming in C_, Fourth Edition +
Stephen G. Kochan +
Pearson Education, 2015 +
ISBN 0-321-77641-0

== Lectures

The course's lectures were filmed in Fall 2016 at Harvard University and Yale University.

A summary of lectures appears below. 

|===
3+| Lecture

| Week 0 | https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/bdc606f10e7347f6a61a341c4544bbf7/179cbcd8dbbb4ac39d922c40d5c06ced/[Scratch]
.2+| Week 1 | https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/bdc606f10e7347f6a61a341c4544bbf7/179cbcd8dbbb4ac39d922c40d5c06ced/[C]
| https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/8c2763b2b26046eda9dbd807f28adf29/[C, continued]
| Week 2 | https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/513631b4d14a489fa6b33a5c21160bee/[Algorithms]
| Week 3 | https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/6832a88122784712a00616fb7f4d65cc/[Memory]
| Week 4 | https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/2e621776158d4de9b0ddb5dbe35b2df7/[Data Structures]
| Week 5 | https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/e53e591bb5ff49449dd1640c2147d756/[HTTP]
.2+| Week 6 | https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/040ae45c5cd446d69ea391a351bff78c/[Dynamic Programming]
| https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/1578406d0f704629a3dedfc372b906c8/[Python]
| Week 7 | https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/1cb42923056a44bc9d6f6244eea86c3a/[Python, continued]
| Week 8 | https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/d46daa332c284c6582c9fa3077b0452c/[SQL]
| Week 9 | https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/eeca03b77330438ca68f404a136e02bd/[JavaScript]
| Week 11 | https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/b3a373c224534dea9e7630566af461e6/[The End]
|===

== Walkthroughs

Integrated into problem sets are "walkthroughs," videos that offer direction on where to begin and how to approach problems. 

== Problem Sets

A summary of problem sets appears below. CS50x does not have deadlines for problem sets. You are welcome to work on and submit them at your own pace. To be eligible for a verified certificate from edX, however, you must submit (and receive a score of at least 70% on) all problem sets by 31 December 2017.

|===
2+| Problem Set | Language

| https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/bdc606f10e7347f6a61a341c4544bbf7/179cbcd8dbbb4ac39d922c40d5c06ced/[Problem Set 0] | Scratch | Scratch
| https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/bdc606f10e7347f6a61a341c4544bbf7/71a3739357a54a0e81348468341214b3/[Problem Set 1] | C | C
| https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/bdc606f10e7347f6a61a341c4544bbf7/8c2763b2b26046eda9dbd807f28adf29/[Problem Set 2] | Crypto | C
| https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/bdc606f10e7347f6a61a341c4544bbf7/513631b4d14a489fa6b33a5c21160bee/[Problem Set 3] | Game of Fifteen | C
| https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/bdc606f10e7347f6a61a341c4544bbf7/6832a88122784712a00616fb7f4d65cc/[Problem Set 4] | Forensics | C
| https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/bdc606f10e7347f6a61a341c4544bbf7/2e621776158d4de9b0ddb5dbe35b2df7/[Problem Set 5] | Mispellings | C
| https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/bdc606f10e7347f6a61a341c4544bbf7/1cb42923056a44bc9d6f6244eea86c3a/[Problem Set 6] | Sentimental | Python
| https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/bdc606f10e7347f6a61a341c4544bbf7/d46daa332c284c6582c9fa3077b0452c/[Problem Set 7] | C$50 Finance | Python, SQL
| https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/courseware/bdc606f10e7347f6a61a341c4544bbf7/eeca03b77330438ca68f404a136e02bd/[Problem Set 8] | Mashup | JavaScript
|===

== Final Project

The climax of this course is its final project. The final project is your opportunity to take your newfound savvy with programming out for a spin and develop your very own piece of software. So long as your project draws upon this course's lessons, the nature of your project is entirely up to you. You may implement your project in any language(s). You are welcome to utilize infrastructure other than the CS50 IDE. All that we ask is that you build something of interest to you, that you solve an actual problem, that you impact your community, or that you change the world. Strive to create something that outlives this course.

Inasmuch as software development is rarely a one-person effort, you are allowed an opportunity to collaborate with one or two classmates for this final project. Needless to say, it is expected that every student in any such group contribute equally to the design and implementation of that group's project. Moreover, it is expected that the scope of a two- or three-person group's project be, respectively, twice or thrice that of a typical one-person project. A one-person project, mind you, should entail more time and effort than is required by each of the course's problem sets. Although no more than three students may design and implement a given project, you are welcome to solicit advice from others, so long as you respect the course's policy on academic honesty.

CS50x does not have a deadline for the final project. You are welcome to work on and submit it at your own pace. To be eligible for a verified certificate from edX, however, you must submit (and receive a score of at least 70% on) it by 31 December 2018.

== Academic Honesty

This course's philosophy on academic honesty is best stated as "be reasonable." The course recognizes that interactions with classmates and others can facilitate mastery of the course's material. However, there remains a line between enlisting the help of another and submitting the work of another. This policy characterizes both sides of that line.

The essence of all work that you submit to this course must be your own. Collaboration on problem sets is not permitted except to the extent that you may ask classmates and others for help so long as that help does not reduce to another doing your work for you. Generally speaking, when asking for help, you may show your code to others, but you may not view theirs, so long as you and they respect this policy's other constraints. Collaboration on the course's final project is permitted to the extent prescribed by its specification.

Below are rules of thumb that (inexhaustively) characterize acts that the course considers reasonable and not reasonable. If in doubt as to whether some act is reasonable, do not commit it. If the course determines that you have commited an act that is not reasonable, you may be deemed ineligible for a certificate. If you commit some act that is not reasonable but bring it to the attention of the course's instructor within 72 hours, the course may reconsider that outcome.

=== Reasonable

* Communicating with classmates about problem sets' problems in English (or some other spoken language).
* Discussing the course's material with others in order to understand it better.
* Helping a classmate identify a bug in his or her code in person or online, as by viewing, compiling, or running his or her code, even on your own computer.
* Incorporating a few lines of code that you find online or elsewhere into your own code, provided that those lines are not themselves solutions to assigned problems and that you cite the lines' origins.
* Sending or showing code that you've written to someone, possibly a classmate, so that he or she might help you identify and fix a bug.
* Sharing a few lines of your own code online so that others might help you identify and fix a bug.
* Turning to the web or elsewhere for instruction beyond the course's own, for references, and for solutions to technical difficulties, but not for outright solutions to problem set's problems or your own final project.
* Whiteboarding solutions to problem sets with others using diagrams or pseudocode but not actual code.
* Working with (and even paying) a tutor to help you with the course, provided the tutor does not do your work for you.

=== Not Reasonable

* Accessing a solution to some problem prior to (re-)submitting your own.
* Asking a classmate to see his or her solution to a problem set's problem before (re-)submitting your own.
* Decompiling, deobfuscating, or disassembling the staff's solutions to problem sets.
* Failing to cite (as with comments) the origins of code or techniques that you discover outside of the course's own lessons and integrate into your own work, even while respecting this policy's other constraints.
* Giving or showing to a classmate a solution to a problem set's problem when it is he or she, and not you, who is struggling to solve it.
* Paying or offering to pay an individual for work that you may submit as (part of) your own.
* Searching for or soliciting outright solutions to problem sets online or elsewhere.
* Splitting a problem set's workload with another individual and combining your work.
* Submitting (after possibly modifying) the work of another individual beyond the few lines allowed herein.
* Submitting the same or similar work to this course that you have submitted or will submit to another.
* Viewing another's solution to a problem set's problem and basing your own solution on it.
