---
layout: 2017/x
---
:skip-front-matter:

= Problem Set 4: Forensics

== tl;dr
 
. Watch https://video.cs50.net/2016/fall/lectures/4[Week 4's lecture].
. Figure out whodunit.
. Resize some images.
. Recover some photos.
. Submit your code.
. Submit a form.

== Help

For help with Week 4 and Problem Set 4:

* Watch Zamyla's walkthroughs herein.
* Take advantage of `help50`, `eprintf`, and `debug50`.
* Start a https://courses.edx.org/courses/course-v1:HarvardX+CS50+X/a7ec0c0a7b6e460f877da0734811c4cd/[discussion] with classmates.

== Getting Started

Alright, here we go again!

Log into https://cs50.io/[cs50.io] and execute

[source]
----
update50
----

within a terminal window to make sure your workspace is up-to-date. 

Next, execute

[source]
----
mkdir ~/workspace/pset4/
----

at your prompt in order to make a directory called `pset4` in your `workspace` directory.

Now execute

[source]
----
cd ~/workspace/pset4/
----

and your prompt should resemble the below.

[source]
----
~/workspace/pset4/ $
----

== What to Do

. Implement link:../../../../problems/whodunit/whodunit.html[Whodunit]
. Implement either of:
+
--
* link:../../../../problems/resize/less/resize.html[Resize], less comfortable
* link:../../../../problems/resize/more/resize.html[Resize], more comfortable
--
+
. Implement link:../../../../problems/recover/recover.html[Recover]

== How to Submit

Be sure you've signed up for a https://github.com/join[GitHub account], per Problem Set 0, and that you've logged into and authorized https://cs50.me/[CS50.me] at least once, per Problem Set 1!

=== Step 1 of 2

* Update your IDE:
+
[source]
----
update50
----
* Submit `whodunit`:
+
[source]
----
cd ~/workspace/pset4/whodunit/
submit50 2017/x/whodunit
----
* Submit the less-comfortable version of `resize` (if you implemented it):
+
[source]
----
cd ~/workspace/pset4/resize/
submit50 2017/x/resize/less
----
* Submit the more-comfortable version of `resize` (if you implemented it):
+
[source]
----
cd ~/workspace/pset4/resize/
submit50 2017/x/resize/more
----
* Submit `recover`:
+
[source]
----
cd ~/workspace/pset4/recover/
submit50 2017/x/recover
----

=== Step 2 of 2

Submit https://forms.cs50.net/2017/x/psets/4[this form]!
 
This was Problem Set 4.
