---
layout: 2016/fall
title: Problem Set 2
---
:skip-front-matter:

= Problem Set 2: Crypto

== tl;dr
 
[start=0]
. Watch https://video.cs50.net/2016/fall/lectures/2[Week 2's lecture].
. TODO
. Submit a form.

include::help-harvard.adoc[]

== Reminders

* Use `help50` as needed.
* Use `eprintf` as needed.
* Use `debug50` as needed.

== Getting Started

Alright, here we go again!

Log into https://cs50.io/[cs50.io] and execute

[source,bash]
----
update50
----

within a terminal window to make sure your workspace is up-to-date. If you somehow closed your terminal window (and can't find it!), make sure that *Console* is checked under the *View* menu, then click the green, circled plus (+) in CS50 IDE's bottom half, then select *New Terminal*. If you need a hand, do just ask via https://cs50.net/discuss[CS50 Discuss]!

Next, execute

[source,bash]
----
mkdir ~/workspace/pset2
----

at your prompt in order to make a directory called `pset2` in your `workspace` directory. Take care not to overlook the space between `mkdir` and `~/workspace/pset2` or any other character for that matter!  Keep in mind that `~` denotes your home directory, `~/workspace` denotes a directory called `workspace` therein, and `~/workspace/pset2` denotes a directory called `pset2` within `~/workspace`.

Now execute

[source,bash]
----
cd ~/workspace/pset2
----

to move yourself into (i.e., open) that directory. Your prompt should now resemble the below.

[source,bash]
----
~/workspace/pset2 $
----

If not, retrace your steps and see if you can determine where you went wrong. You can actually execute

[source,bash]
----
history
----

at the prompt to see your last several commands in chronological order if you'd like to do some sleuthing. You can also scroll through the same one line at a time by hitting your keyboard's up and down arrows; hit Enter to re-execute any command that you'd like. If still unsure how to fix, remember that https://cs50.net/discuss[CS50 Discuss] is your friend!

All of the work that you do for this problem set must ultimately reside in your `pset2` directory for submission.

== Initializing

Alright, let's get more comfortable with `string`. 

Create a "subdirectory" within `~/workspace/pset2/` called `initials` as follows.

[source,bash]
----
cd ~/workspace/pset2
mkdir initials
cd initials
----

Your prompt should now resemble the below.

[source,bash]
----
~/workspace/pset2/initials/ $
----

Within that directory, in a file called `initials.c`, implement a program that:

* prompts a user for their name, using `get_string` to obtain their name as a `string`, and
* prints their initials (i.e., the first letter of each word in their name) with no spaces or periods, followed by a newline (`\n`).

You may assume that the user's input will contain only letters (uppercase and/or lowercase) plus single spaces between words. You don't need to worry about names like `Joseph Gordon-Levitt`, `Conan O'Brien`, or `David J. Malan`!

So that we can automate some tests of your code, your program must behave per the examples below. Assumed that the underlined text is what some user has typed.

[source,subs=quotes]
----
~/workspace/pset2/initials/ $ [underline]#./initials#
[underline]#Zamyla Chan#
ZC
~/workspace/pset2/initials/ $ [underline]#./initials#
[underline]#robert thomas bowden#
RTB
----

If you'd like to check the correctness of your program with `check50`, you may execute the below.

[source,bash]
----
check50 2016.initials initials.c
----

And if you'd like to play with the staff's own implementation of `initials`, you may execute the below.

[source,bash]
----
~cs50/pset2/initials
----

Not sure where to begin? Here's Zamyla with a walkthrough:

video::TODO[youtube,height=540,width=960]

== Hail, Caesar!

Recall that a "cipher" is an algorithm for encrypting (i.e., concealing) information. One such cipher is named after Caesar, who supposedly encrypted military messages by "shifting" letters of the alphabet, whereby he wrote 'A' as 'D', 'B' as 'E', and so forth, wrapping around from 'Z' to 'C'. Not particularly secure by modern standards, but, hey, if you're perhaps the first in the world to do it, pretty secure!

More formally, Caesar's cipher encrypts messages by "rotating" each letter by _k_ positions, wrapping around from `Z` to `A` as needed (cf. http://en.wikipedia.org/wiki/Caesar_cipher). In other words, if _p_ is some plaintext (i.e., an unencrypted message), _p~i~_ is the _i^th^_ character in _p_, and _k_ is a secret key (i.e., a non-negative integer), then each letter, _c~i~_, in the ciphertext, _c_, is computed as:

_c~i~_ = (_p~i~_ + _k_) % 26

This formula perhaps makes the cipher seem more complicated than it is, but it's really just a nice way of expressing the algorithm precisely and concisely. And computer scientists love precision and, er, concision. 

For example, suppose that the secret key, _k_, is 13 and that the plaintext, _p_, is "be sure to drink your Ovaltine"  Let's encrypt that _p_ with that _k_ in order to get the ciphertext, _c_, by rotating each of the letters in _p_ by 13 places, whereby:

[source,text]
----
be sure to drink your Ovaltine
----

becomes:

[source,text]
----
or fher gb qevax lbhe Binygvar
----

We've deliberately printed the above in a monospaced font so that all of the letters line up nicely. Notice how `o` (the first letter in the ciphertext) is 13 letters away from `B` (the first letter in the plaintext). Similarly is `r` (the second letter in the ciphertext) 13 letters away from `e` (the second letter in the plaintext). Meanwhile, `f` (the third letter in the ciphertext) is 13 letters away from `s` (the third letter in the plaintext), though we had to wrap around from `z` to `a` to get there. And so on. Not the most secure cipher, to be sure, but fun to implement!

Incidentally, a Caesar cipher with a key of 13 is generally called ROT13 (cf. http://en.wikipedia.org/wiki/ROT13). Don't use http://www.urbandictionary.com/define.php?term=ROT26[ROT26].

Anyhow, your next goal is to write, in `caesar.c`, a program that encrypts messages using Caesar's cipher. 

* Your program must accept a single command-line argument, a non-negative integer. Let's call it _k_ for the sake of discussion.
* If your program is executed without any command-line arguments or with more than one command-line argument, your program should print an error message (of your choice) and return (from `main`) a value of `1` (which tends to signify an error) immediately.
* You can assume that the command-line argument that the user provides will be entirely numeric (e.g., `13` and not `foo`).
* Otherwise, your program must proceed to prompt the user for a string of plaintext and then output that text with each alphabetical character "rotated" by _k_ positions; non-alphabetical characters should be outputted unchanged.
* Your program must preserve case: capitalized letters, though rotated, must remain capitalized letters; lowercase letters, though rotated, must remain lowercase letters.
* After outputting ciphertext, your program should exit by returning `0` from `main`.

Recall that, if you don't explicitly return an `int` from within `main`, `0` is actually returned for you automatically. (Indeed, per its "return type," `main` does need to return an `int`.) Now that you're returning `1` explicitly to signify errors, it's best to return `0` (by convention) explicitly to signify success. Whereas `0` generally represents success, any non-`0` `int` generally represents an error. That way, you can represent (gasp) upwards of four billion errors (since an `int` is generally 32 bits)!

Anyhow, even though there exist only 26 letters in the English alphabet, you may not assume that _k_ will be less than or equal to 26; your program should work for all non-negative integral values of _k_ less than 2^31^ - 26. In other words, you don't need to worry if your program eventually breaks if the user chooses a value for _k_ that's too big or almost too big to fit in an `int`. (Recall that an `int` can overflow.) But, even if _k_ is greater than 26, alphabetical characters in your program's input should remain alphabetical characters in your program's output. For instance, if _k_ is 27, `A` should not become `[` even though `[` is 27 positions away from `A` in ASCII, per http://www.asciichart.com/[asciichart.com]; `A` should become `B`, since "27 modulo 26" is 1, as a computer scientists might say. In other words, values like _k_ = 1 and _k_ = 27 are effectively equivalent. Put more simply, be sure to wrap around from `Z` to `A` (and from `z` to `a`).

Where to begin?  Well, this program needs to accept a command-line argument, _k_, so this time you'll want to declare `main` with:

[source,c]
----
int main(int argc, string argv[])
----

Recall that `argv` is an "array" of ++string++s. You can think of an array as row of gym lockers, inside each of which is some value (and maybe some socks). In this case, inside each such locker is a `string`. To open (i.e., "index into") the first locker, you use syntax like `argv[0]`, since arrays are "zero-indexed." To open the next locker, you use syntax like `argv[1]`. And so on. Of course, if there are `n` lockers, you'd better stop opening lockers once you get to `argv[n - 1]`, since `argv[n]` doesn't exist!  (That or it belongs to someone else, in which case you still shouldn't open it.)  

And so you can access _k_ with code like

[source,c]
----
string k = argv[1];
----

assuming it's actually there! Recall that `argc` is an `int` that equals the number of strings that are in `argv`, so you'd best check the value of `argc` before opening a locker that might not exist!  Ideally, `argc` will be `2`. Why? Well, recall that inside of `argv[0]`, by default, is a program's own name. So `argc` will always be at least `1`. But for this program you want the user to provide a command-line argument, `k`, in which case `argc` should be `2`. Of course, if the user provides more than one command-line argument at the prompt, `argc` could be greater than `2`, in which case, again, your program should print an error and return `1`.

Now, just because the user types an integer at the prompt, that doesn't mean their input will be automatically stored in an `int`. Au contraire, it will be stored as a `string` that just so happens to look like an `int`!  And so you'll need to convert that `string` to an actual `int`. As luck would have it, a function, https://reference.cs50.net/stdlib/atoi[`atoi`], exists for exactly that purposes. Here's how you might use it:

[source,c]
----
int k = atoi(argv[1]);
----

Notice, this time, we've declared `k` as an actual `int` so that you can actually do some arithmetic with it. 

Because `atoi` is declared in `stdlib.h`, you'll want to `#include` that header file atop your own code. (Technically, your code will compile without it there, since we already `#include` it in `cs50.h`. But best not to trust another library to `#include` header files you know you need.)

Okay, so once you've got `k` stored as an `int`, you'll need to ask the user for some plaintext. Odds are CS50's own `get_string` can help you with that.

Once you have both `k` and some plaintext, it's time to encrypt the latter with the former. Recall that you can iterate over the characters in a `string`, printing each one at a time, with code like the below:

[source,c]
----
for (int i = 0, n = strlen(p); i < n; i++)
{
    printf("%c", p[i]);
}
----

In other words, just as `argv` is an array of ++string++s, so is a `string` an array of ++char++s. And so you can use square brackets to access individual characters in ++string++s just as you can individual ++string++s in `argv`. Neat, eh?  Of course, printing each of the characters in a string one at a time isn't exactly cryptography. Well, maybe technically if _k_ is 0. But the above should help you help Caesar implement his cipher! For Caesar!

Incidentally, you'll need to `#include` yet another header file in order to use https://reference.cs50.net/string/strlen[`strlen`]. 

So that we can automate some tests of your code, your program must behave per the below. Assumed that the underlined text is what some user has typed.

[source,subs=quotes]
----
~/workspace/pset2 $ [underline]#./caesar 13#
[underline]#Be sure to drink your Ovaltine!#
Or fher gb qevax lbhe Binygvar!
----

Besides `atoi`, you might find some handy functions documented at https://reference.cs50.net/ under *ctype.h* and *stdlib.h*. For instance, `isdigit` sounds interesting. And, with regard to wrapping around from `Z` to `A` (or `z` to `a`), don't forget about `%`, C's modulo operator. You might also want to check out http://asciitable.com/, which reveals the ASCII codes for more than just alphabetical characters, just in case you find yourself printing some characters accidentally.

If you'd like to check the correctness of your program with `check50`, you may execute the below.

[source,bash]
----
check50 2016.caesar caesar.c
----

And if you'd like to play with the staff's own implementation of `caesar`, you may execute the below.

[source,bash]
----
~cs50/pset2/caesar
----

Here's Zamyla if you'd like a walkthrough as well:

video::TODO[youtube,height=540,width=960]

== Parlez-vous français?

Well that last cipher was hardly secure. Fortunately, there's a more sophisticated algorithm out there. Suffice it to say it's French.

https://en.wikipedia.org/wiki/Vigen%C3%A8re_cipher[Vigenère's cipher] improves upon Caesar's by encrypting messages using a sequence of keys (or, put another way, a keyword). In other words, if _p_ is some plaintext and _k_ is a keyword (i.e., an alphbetical string, whereby `A` and `a` represent 0, while `Z` and `z` represent 25), then each letter, _c~i~_, in the ciphertext, _c_, is computed as:

_c~i~_ = (_p~i~_ + _k~j~_) % 26

Note this cipher's use of _k~j~_ as opposed to just _k_. And recall that, if _k_ is shorter than _p_, then the letters in _k_ must be reused cyclically as many times as it takes to encrypt _p_.

Your final challenge this week is to write, in `vigenere.c`, a program that encrypts messages using Vigenère's cipher. This program must accept a single command-line argument: a keyword, _k_, composed entirely of alphabetical characters. If your program is executed without any command-line arguments, with more than one command-line argument, or with one command-line argument that contains any non-alphabetical character, your program should complain and exit immediately, with main returning `1` (thereby signifying an error that our own tests can detect). Otherwise, your program must proceed to prompt the user for a string of plaintext, _p_, which it must then encrypt according to Vigenère's cipher with _k_, ultimately printing the result and exiting, with `main` returning `0`.

As for the characters in _k_, you must treat `A` and `a` as 0, `B` and `b` as 1, ... , and `Z` and `z` as 25. In addition, your program must only apply Vigenère's cipher to a character in _p_ if that character is a letter. All other characters (numbers, symbols, spaces, punctuation marks, etc.) must be outputted unchanged. Moreover, if your code is about to apply the _j^th^_ character of _k_ to the _i^th^_ character of _p_, but the latter proves to be a non-alphabetical character, you must wait to apply that _j^th^_ character of _k_ to the next alphabetical character in _p_; you must not yet advance to the next character in _k_. Finally, your program must preserve the case of each letter in _p_.

Not sure where to begin?  As luck would have it, this program's pretty similar to `caesar`!  Only this time, you need to decide which character in _k_ to use as you iterate from character to character in _p_.

And here's Zamyla again with some tips:

video::TODO[youtube,height=540,width=960]

So that we can automate some tests of your code, your program must behave per the below; highlighted in bold are some sample inputs.

[source,subs=quotes]
----
~/workspace/pset2/vigenere/ [underline]#./vigenere bacon#
[underline]#Meet me at the park at eleven am#
Negh zf av huf pcfx bt gzrwep oz
----

How to test your program, besides predicting what it should output, given some input?  Well, recall that we're nice people. And so we've written a program called `devigenere` that also takes one and only one command-line argument (a keyword) but whose job is to take ciphertext as input and produce plaintext as output. 

To use our program, execute

[source,bash]
----
~cs50/pset2/devigenere k
----

at your prompt, where `k` is some keyword. Presumably you'll want to paste your program's output as input to our program; be sure, of course, to use the same key. Note that you do not need to implement `devigenere` yourself, only `vigenere`.

If you'd like to check the correctness of your program with `check50`, you may execute the below.

[source,bash]
----
check50 2016.vigenere vigenere.c
----

And if you'd like to play with the staff's own implementation of `vigenere`, you may execute the below.

[source,bash]
----
~cs50/pset2/vigenere
----

## How to Submit

_Coming Wed 9/14. Reload this page then!_
