---
layout: 2016/fall
title: Problem Set 2
---
:skip-front-matter:

= Problem Set 2: Crypto

== tl;dr
 
[start=0]
. Watch https://video.cs50.net/2016/fall/lectures/2[Week 2's lecture].
. Infer a user's initials from their name with `initials.c`.
. Choose two adventures:
+
--
* Implement Caesar's cipher.
* Implement Vigenère's cipher.
* Crack passwords.
--
+
. Submit your code.
. Submit a form.

include::help-yale.adoc[]

== Reminders

Per https://video.cs50.net/2016/fall/lectures/2[Week 2's lecture]:

* Use `help50` as needed.
* Use `eprintf` as needed.
* Use `debug50` as needed.

== Getting Started

Alright, here we go again!

Log into https://cs50.io/[cs50.io] and execute

[source]
----
update50
----

within a terminal window to make sure your workspace is up-to-date. If you somehow closed your terminal window (and can't find it!), make sure that *Console* is checked under the *View* menu, then click the green, circled plus (+) in CS50 IDE's bottom half, then select *New Terminal*.

Next, execute

[source]
----
mkdir ~/workspace/pset2
----

at your prompt in order to make a directory called `pset2` in your `workspace` directory. Take care not to overlook the space between `mkdir` and `~/workspace/pset2` or any other character for that matter!  Keep in mind that `~` denotes your home directory, `~/workspace` denotes a directory called `workspace` therein, and `~/workspace/pset2` denotes a directory called `pset2` within `~/workspace`.

Now execute

[source]
----
cd ~/workspace/pset2
----

to move yourself into (i.e., open) that directory. Your prompt should now resemble the below.

[source]
----
~/workspace/pset2/ $
----

If not, retrace your steps and see if you can determine where you went wrong. You can actually execute

[source,bash]
----
history
----

at the prompt to see your last several commands in chronological order if you'd like to do some sleuthing. You can also scroll through the same one line at a time by hitting your keyboard's up and down arrows; hit Enter to re-execute any command that you'd like. 

== What to Do

. Implement either of:
+
--
* link:../../../../problems/initials/less/initials.html[Initials], less comfortable
* link:../../../../problems/initials/more/initials.html[Initials], more comfortable
--
+
. Implement any two (2) of:
+
--
* link:../../../../problems/caesar/caesar.html[Caesar], less comfortable
* link:../../../../problems/vigenere/vigenere.html[Vigenere], less comfortable
* link:../../../../problems/crack/crack.html[Crack], more comfortable
--

== How to Submit

For this problem set, we'll be using a new submission system based on GitHub, a popular site for storing code. Recall that for Problem Set 0 you signed up (hopefully!) for an account on https://github.com/[github.com]. The new system's still in "beta" (a testing phase), so please forgive any bugs! We'll keep an eye on https://cs50.net/discuss[CS50 Discuss] and email over the weekend in case anything goes wrong so that we can fix right away!

=== Step 1 of 4

Execute

[source]
----
sudo apt-get install -y expect
update50
----

again to ensure that your IDE is up-to-date.

=== Step 2 of 4

* Recall that you were asked to implement the less-comfortable or more-comfortable version of `initials`. 
** Be sure that `initials.c` is in `~/workspace/pset2/initials`, as with:
+
[source]
----
cd ~/workspace/pset2/initials/
ls
----
* Recall that you were asked to implement any two (2) of `caesar`, `vigenere`, and `crack`.
** If you implemeneted `caesar`, be sure that `caesar.c` is in `~/workspace/pset2/caesar/`.
** If you implemeneted `vigenere`, be sure that `vigenere.c` is in `~/workspace/pset2/vigenere/`.
** If you implemeneted `crack`, be sure that `crack.c` is in `~/workspace/pset2/crack/`.

If not sure how to confirm or fix something, do just reach out to your TA or via https://cs50.net/discuss[CS50 Discuss]!

=== Step 3 of 4

* To submit `initials`, execute
+
[source]
----
cd ~/workspace/pset2/initials/
submit50 initials
----
+
inputting your GitHub username and GitHub password as prompted.
* To submit `caesar` (if you implemented it), execute:
+
[source]
----
cd ~/workspace/pset2/caesar/
submit50 caesar
----
* To submit `vigenere` (if you implemented it), execute:
+
[source]
----
cd ~/workspace/pset2/vigenere/
submit50 vigenere
----
* To submit `crack` (if you implemented it), execute:
+
[source]
----
cd ~/workspace/pset2/crack/
submit50 crack
----

If you run into any trouble, email sysadmins@cs50.harvard.edu!

You may resubmit any problem as many times as you'd like.

Incidentally, the white and yellow output from `submit50` will soon be simplified; it's some short-term diagnostic output!

=== Step 4 of 4
  
Submit https://forms.cs50.net/2016/fall/psets/2[]!
 
This was Problem Set 2.
