---
layout: 2019/ap
---
:skip-front-matter:

= Problem: Resize

== tl;dr

Implement a program that resizes BMPs, per the below.

[source,subs=quotes]
----
$ [underline]#./resize 4 small.bmp large.bmp#
----

include::../../honesty.adoc[]

== Introduction

video::HmBtQJDiVm8[youtube]

== Getting Started

Here's how to download this problem's "distribution code" (i.e., starter code) into your own CS50 IDE. Log into link:https://ide.cs50.io/[CS50 IDE] and then, in a terminal window, execute each of the below.

1. Execute `cd` to ensure that you're in `~/` (i.e., your home directory, aka `~`).
1. Execute `mkdir chapter3` to make (i.e., create) a directory called `chapter3` in your home directory.
1. Execute `cd chapter3` to change into (i.e., open) that directory.
1. Execute `wget http://cdn.cs50.net/ap/2019/problems/resize/less/resize.zip` to download a (compressed) ZIP file with this problem's distribution.
1. Execute `unzip resize.zip` to uncompress that file.
1. Execute `rm resize.zip` followed by `yes` or `y` to delete that ZIP file.
1. Execute `ls`. You should see a directory called `resize`, which was inside of that ZIP file.
1. Execute `cd resize` to change into that directory.
1. Execute `ls`. You should see a directory called `less`.
1. Execute `cd less` to change into that directory.
1. Execute `ls`. You should see this problem's distribution, including `bmp.h`, `copy.c`, `large.bmp`, `small.bmp`, and `smiley.bmp`.

== Background

First, be sure you're familiar with the structure of 24-bit uncompressed BMPs, as introduced in link:https://lab.cs50.io/cs50/labs/2019/ap/whodunit[Whodunit].

To reiterate a bit from that lab, recall that a file is just a sequence of bits, arranged in some fashion. A 24-bit BMP file, then, is essentially just a sequence of bits, (almost) every 24 of which happen to represent some pixel's color. But a BMP file also contains some "metadata," information like an image's height and width. That metadata is stored at the beginning of the file in the form of two data structures generally referred to as "headers," not to be confused with C's header files. (Incidentally, these headers have evolved over time. This problem only expects that you support the latest version of Microsoft's BMP format, 4.0, which debuted with Windows 95.) The first of these headers, called `BITMAPFILEHEADER`, is 14 bytes long. (Recall that 1 byte equals 8 bits.) The second of these headers, called `BITMAPINFOHEADER`, is 40 bytes long. Immediately following these headers is the actual bitmap: an array of bytes, triples of which represent a pixel's color. (In 1-, 4-, and 16-bit BMPs, but not 24- or 32-, there's an additional header right after `BITMAPINFOHEADER` called `RGBQUAD`, an array that defines "intensity values" for each of the colors in a device's palette.) However, BMP stores these triples backwards (i.e., as BGR), with 8 bits for blue, followed by 8 bits for green, followed by 8 bits for red. (Some BMPs also store the entire bitmap backwards, with an image's top row at the end of the BMP file. But we've stored this problem set's BMPs as described herein, with each bitmap's top row first and bottom row last.) In other words, were we to convert the 1-bit smiley above to a 24-bit smiley, substituting red for black, a 24-bit BMP would store this bitmap as follows, where `0000ff` signifies red and `ffffff` signifies white; we've highlighted in red all instances of `0000ff`.

== Assessment

Your work on this problem set will be evaluated along three axes primarily.

Correctness::
  To what extent is your code consistent with our specifications and free of bugs?

Design::
  To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?

Style::
  To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Distribution

=== Downloading

[source,subs="macros"]
----
$ wget https://cdn.cs50.net/ap/2019/problems/resize/resize.zip
$ unzip resize.zip
$ rm resize.zip
$ cd resize
$ ls
bmp.h  copy.c  large.bmp  small.bmp  smiley.bmp
----

== Specification

Implement a program called `resize` that resizes (i.e., enlarges) 24-bit uncompressed BMPs by a factor of `n`.

* Implement your program in a file called `resize.c` inside of `~/chapter3/resize/less/`.
* Your program should accept exactly three command-line arguments, whereby
+
--
** the first (`n`) must be a positive integer less than or equal to `100`,
** the second must be the name of a BMP to be resized, and
** the third must be the name of the resized version to be written.
--
+ If your program is not executed with such, it should remind the user of correct usage, as with `fprintf` (to `stderr`), and `main` should return `1`.
* Your program, if it uses `malloc`, must not leak any memory.

== Walkthrough

video::zOylgRdzv_U[youtube]

== Usage

Your program should behave per the examples below. Assumed that the underlined text is what some user has typed.

[source,subs=quotes]
----
$ [underline]#./resize#
Usage: ./resize n infile outfile
$ [underline]#echo $?#
1
----

[source,subs=quotes]
----
$ [underline]#./resize 2 small.bmp larger.bmp#
$ [underline]#echo $?#
0
----

== Hints

With a program like this, we could have created `large.bmp` out of `small.bmp` by resizing the latter by a factor of 4 (i.e., by multiplying both its width and its height by 4), per the below.

[source]
----
./resize 4 small.bmp large.bmp
----

You're welcome to get started by copying (yet again) `copy.c` and naming the copy `resize.c`. But spend some time thinking about what it means to resize a BMP. (You may assume that `n` times the size of `infile` will not exceed 2^32^ - 1.) Decide which of the fields in `BITMAPFILEHEADER` and `BITMAPINFOHEADER` you might need to modify. Consider whether or not you'll need to add or subtract padding to scanlines. And do be sure to support a value of `1` for `n`, the result of which should be an `outfile` with dimensions identical to ``infile``'s.

If you happen to use `malloc`, be sure to use `free` so as not to leak memory. Try using `valgrind` to check for any leaks!

== Testing

If you'd like to peek at, e.g., ``large.bmp``'s headers (in a more user-friendly way than `xxd` allows), you may execute the below.

[source]
----
~cs50/chapter3/peek large.bmp
----

Better yet, if you'd like to compare your outfile's headers against those from the <<staffs-solution,staff's solution>>, you might want to execute commands like the below. (Think about what each is doing.)

[source]
----
./resize 4 small.bmp student.bmp
~cs50/chapter3/resize 4 small.bmp staff.bmp
~cs50/chapter3/peek student.bmp staff.bmp
----

=== Correctness

[source]
----
check50 cs50/problems/2019/ap/resize/less
----

=== Style

[source]
----
style50 resize.c
----

== Staff's Solution

[source]
----
~cs50/unit4/resize/less
----

== How to Submit

=== Step 1 of 2

Ensure you have all of the files below:

* resize.c
* Makefile

Be sure that each of your files are in `~/unit4/resize`, as with:

[source]
----
cd ~/unit4/resize
ls
----

If any file is not in `~/unit4/resize`, move it into that directory, as via `mv` (or via CS50 IDE's lefthand file browser).

=== Step 2 of 2

Submit `resize`:

[source]
----
cd ~/unit4/resize/
submit50 cs50/problems/2019/ap/resize/less
----

inputting your GitHub username and GitHub password as prompted.

If you run into any trouble, email sysadmins@cs50.harvard.edu!

You may resubmit any problem as many times as you'd like.
 
Your submission should be graded for correctness within 2 minutes, at which point your score will appear at https://cs50.me/[cs50.me]!

This was Resize.

