---
layout: 2018/ap
---
:skip-front-matter:

= Problem: Old Friends

== tl;dr

Improve upon older problems.

[source,subs=quotes]
----
$ [underline]#./hello Milo#
Hello, Milo!
$ [underline]#./fahrenheit 0#
F: 32.0
$ [underline]#./pennies 28 1#
$2684354.55
----

include::../../honesty.adoc[]

== Assessment

Your work on this problem set will be evaluated along three axes primarily.

Correctness::
  To what extent is your code consistent with our specifications and free of bugs?

Design::
  To what extent is your code written well (i.e., clearly, efficiently, elegantly, and/or logically)?

Style::
  To what extent is your code readable (i.e., commented and indented with variables aptly named)?

To obtain a passing grade in this course, all students must ordinarily submit all assigned problems unless granted an exception in writing by the instructor.

== Well-Distributed

Here's some good news for you right off the bat: you've seen almost everything we're going to talk about in this problem once before. We're going to revisit three old programs and rewrite them so that instead of taking input from the user while the program is running, they will instead accept input from the user at the command-line, before the program is even run.

Even better, to ensure everyone is on a level playing field while solving this problem, you'll be downloading some "distribution code" (otherwise known as a "distro"), written by us, and make modifications to it. You're welcome of course to use the code you wrote for a prior problem (if it worked!) and re-work it for this problem, but if you struggled with the problems we'll be reimplementing this time around, know that we will otherwise be supplying you with fully-functional code. All you have to do is change the way that the user inputs data.

Start off by opening up CS50 IDE and then type

[source,bash]
----
update50
----

within a terminal window to make sure your workspace is up-to-date. If you somehow closed your terminal window (and can't find it!), make sure that *Console* is checked under the *View* menu, then click the green, circled plus (+) in CS50 IDE's bottom half, then select *New Terminal*. If you need a hand, do just ask via the channels noted at the top of this specification.

Next, navigate to your `unit2` directory, as with

[source,bash]
----
cd ~/workspace/unit2
----

Keep in mind that `~` denotes your home directory, `~/workspace` denotes a directory called `workspace` therein, and `~/workspace/unit2` denotes a directory called `unit2` within `~/workspace`. Your prompt should now resemble the below.

[source,bash]
----
~/workspace/unit2 $
----

To download a ZIP of this problem's distro into your workspace (with a command-line program called `wget`), type:

[source,bash]
----
wget https://cdn.cs50.net/ap/2018/problems/friends/friends.zip
----

You should see some output followed by:

[source,bash]
----
'friends.zip' saved
----

Confirm that you've indeed downloaded `friends.zip` by executing

[source,bash]
----
ls
----

and then run

[source,bash]
----
unzip friends.zip
----

to unzip the file. If you then run `ls` again, you should see that you have a newly unzipped directory called `friends` as well. Proceed to execute

[source,bash]
----
cd friends
----

followed by

[source,bash]
----
ls
----

and you should indeed see a few old friends!

[source,bash]
----
fahrenheit.c  hello.c  pennies.c
----

How nice to see them again!

Lastly, have a look at Christopher's short video on command-line arguments. Since we'll be converting all three of the programs listed above to accept command-line arguments (none of them currently do!), this video should come in handy.

video::X8PmYwnbLKM[youtube]

If you happen to see (and are confused by!) `char *` in this and other shorts, know for now that `char *` simply means `string`. But more on that soon!

== Hello, again!

In http://docs.cs50.net/2018/ap/problems/hello/hello.html[Hello] you were asked to write a program that very simply printed the message `hello, world\n` to the screen when run. It's not too much of a leap to extend this program to say hello to a specific person by asking for the user to type a name at the prompt instead, so the program behaves like this.

[source,subs=quotes]
----
~/workspace/unit2/friends $ [underline]#./hello#
Your name: [underline]#Zamyla#
hello, Zamyla
----

In fact, the distro you downloaded contains a file, `hello.c`, with exactly this behavior. What we want, though, is a program that has this behavior instead:

[source,subs=quotes]
----
~/workspace/unit2/friends $ [underline]#./hello Zamyla#
hello, Zamyla
----

See the slight difference? Instead of prompting the user for information **after** the program has started running, we collect the desired information from the user **before** they run the program, and then use that information once the program has started. How do we do so?

Recall that our programs are capable of knowing information about what the user typed at the command line by modifying the way we write the start of our `main` function. Instead of

[source,c]
----
int main(void)
----

if we start `main` off by typing

[source,c]
----
int main(int argc, string argv[])
----

we then have access to two special variables that we can use inside of `main`. First is `argc`, which is an integer variable that tells us how many things the user typed in at the command line, and second is `argv`, which is an array of strings representing exactly what the user typed.

Knowing this, and from the information in Christopher's short, can you now modify `hello.c` so that it prints out the name provided at the command line, instead of collecting a `string` from the user after the program has started?

One more wrinkle. How do you make sure the user in fact did provide you with one (and only one) additional argument, so that you can print it out? Well remember that's what our new friend `argc` can manage for us. If the user doesn't supply a command-line argument, best to terminate the program and have them try again. One way to accomplish this might be to have this near the top of our code:

[source,c]
----
if (argc != 2)
{
    printf("Usage: ./hello <name>\n");
    return 1;
}
----

Note what this accomplishes? We check to make sure that the user has supplied the proper number of command-line arguments (2). If not, we tell the user how they __should__ run the program, and then we `return 1;`, which is our way of indicating that our program finished running, but not successfully. We use nonzero return values from `main`, also known as __exit codes__, to report back to the system that something went awry.

== Testing

=== Correctness

If you'd like to check the correctness of your program with `check50`, you may execute the below.

[source,bash]
----
check50 cs50/2018/ap/friends/hello
----

=== Style

[source]
----
style50 hello.c
----

== Staff Solution

If you'd like to play with the staff's own implementation of `hello`, you may execute the below.

[source,bash]
----
~cs50/unit2/hello
----

== Chill Out

In http://docs.cs50.net/2018/ap/problems/fahrenheit/fahrenheit.html[Fahrenheit] you were asked to write a program that asked the user for a temperature in Celsius (which they provided via `get_float`) and which then printed out the equivalent temperature on the Fahrenheit scale.

[source,subs=quotes]
----
~/workspace/unit2/friends $ [underline]#./fahrenheit#
C: [underline]#0#
F: 32.0
----

In `fahrenheit.c` you will find a fully-functioning version of the code you were tasked with writing in that problem. Convert that program so that it accepts the Celsius temperature from the command line instead.

[source,subs=quotes]
----
~/workspace/unit2/friends $ [underline]#./fahrenheit 0#
F: 32.0
----

There's a catch, though.

Just because the user types a real number at the prompt, that doesn't mean their input will be automatically stored in a `float`. Actually, it will be stored as a `string` that just so happens to look like an `float`; after all, remember the data type of `argv`? It's an array where each element is a `string`!  And so you'll need to convert that `string` to an actual `float`. As luck would have it, a function, https://reference.cs50.net/stdlib.h/atof[`atof`], exists for exactly that purpose! Here's how you might use it:

[source,c]
----
float celsius = atof(argv[1]);
----

Notice, this time, we've declared `celsius` as an actual `float` so that you can do some arithmetic with it. Incidentally, you can assume that the user will only type real numbers at the command line.

Because `atof` is declared in `stdlib.h`, you'll want to `#include` that header file atop your own code. And, as with `hello.c` earlier, you'll want to make sure the user provides exactly the correct number of command-line arguments to your program before doing any calculations, returning 1 should they fail to.

== Testing

=== Correctness

If you'd like to check the correctness of your program with `check50`, you may execute the below.

[source,bash]
----
check50 cs50/2018/ap/friends/fahrenheit
----

=== Style

[source]
----
style50 fahrenheit.c
----

== Staff Solution

If you'd like to play with the staff's own implementation of `fahrenheit`, you may execute the below.

[source,bash]
----
~cs50/unit2/fahrenheit
----

== Makin' Bank

In http://docs.cs50.net/2018/ap/problems/pennies/pennies.html[Pennies] you were asked to write a program that demonstrated the power of exponentiation by showing how much money you would have if a person gave you __x__ pennies on a particular day, and then doubled the amount they gave you every day for a period of __y__ days.

[source,subs=quotes]
----
~/workspace/unit2/friends $ [underline]#./pennies#
Days in month: [underline]#31#
Pennies on first day: [underline]#1#
$21474836.47
----

As you might expect, we'd now like the program to work as follows.

[source,subs=quotes]
----
~/workspace/unit2/friends $ [underline]#./pennies 31 1#
$21474836.47
----

Notice a few differences with this program from the previous two. How many command line arguments does __this__ one accept? Be sure to modify your check against `argc` accordingly. And also know that in `stdlib.h` alongside of the function `atof` exists another, `atoi`, that converts a `string` to an `int` in much the same way that `atof` converts a `string` to a `float`.

Incidentally, you can assume that the user will only type integers at the command line; there's no need for you to anticipate a rogue user this time around!

== Testing

=== Correctness

If you'd like to check the correctness of your program with `check50`, you may execute the below.

[source,bash]
----
check50 cs50/2018/ap/friends/pennies
----

=== Style

[source]
----
style50 pennies.c
----

== Staff Solution

If you'd like to play with the staff's own implementation of `pennies`, you may execute the below.

[source,bash]
----
~cs50/unit2/pennies
----

== How to Submit

=== Step 1 of 2

Recall that you were asked to create the files below:

* `hello.c`
* `fahrenheit.c`
* `pennies.c`

Be sure that each of your files is in `~/workspace/unit2/friends`, as with:

[source]
----
cd ~/workspace/unit2/friends
ls
----

If any file is not in `~/workspace/unit2/friends`, move it into that directory, as via `mv` (or via CS50 IDE's lefthand file browser).

=== Step 2 of 2

* To submit `hello`, execute
+
[source]
----
cd ~/workspace/unit2/friends
submit50 cs50/2018/ap/friends/hello
----
+
inputting your GitHub username and GitHub password as prompted.
* To submit `fahrenheit`, execute
+
[source]
----
cd ~/workspace/unit2/friends
submit50 cs50/2018/ap/friends/fahrenheit
----
+
inputting your GitHub username and GitHub password as prompted.
* To submit `pennies`, execute
+
[source]
----
cd ~/workspace/unit2/friends
submit50 cs50/2018/ap/friends/pennies
----
+
inputting your GitHub username and GitHub password as prompted.

If you run into any trouble, email sysadmins@cs50.harvard.edu!

You may resubmit any problem as many times as you'd like.
 
Your submission should be graded for correctness within 2 minutes, at which point your score will appear at https://cs50.me/[cs50.me]!

This was Old Friends.
